//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTUserInterfaceKit/DVTFindPatternSearchField.h>

#import <DVTSourceEditor/_TtP12SourceEditor34SourceEditorTextFindPanelFieldType_-Protocol.h>

@class MISSING_TYPE, _TtC12SourceEditor25SourceEditorTextFindPanel;

__attribute__((visibility("hidden")))
@interface _TtC15DVTSourceEditor28DVTSourceEditorTextFindField : DVTFindPatternSearchField <_TtP12SourceEditor34SourceEditorTextFindPanelFieldType_>
{
    MISSING_TYPE *panel;
    MISSING_TYPE *insets;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)cancelOperation:(id)arg1;
- (struct CGRect)rectForSearchTextWhenCentered:(BOOL)arg1;
- (struct CGRect)rectForCancelButtonWhenCentered:(BOOL)arg1;
@property(nonatomic) struct NSEdgeInsets insets; // @synthesize insets;
@property(nonatomic, copy) id textFindValue;
- (id)font;
@property(nonatomic) __weak _TtC12SourceEditor25SourceEditorTextFindPanel *panel; // @synthesize panel;

@end

