//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _DVTInfoPlistValueCellToken : NSObject
{
    NSString *_displayString;
    NSString *_representedString;
    BOOL _editable;
    struct _NSRange _range;
}

@property(readonly, getter=isEditable) BOOL editable; // @synthesize editable=_editable;
@property struct _NSRange range; // @synthesize range=_range;
@property(copy) NSString *displayString; // @synthesize displayString=_displayString;
@property(copy) NSString *representedString; // @synthesize representedString=_representedString;
- (void).cxx_destruct;
- (id)description;
- (id)initWithRepresentedString:(id)arg1 displayString:(id)arg2 range:(struct _NSRange)arg3 editable:(BOOL)arg4;

@end

