//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <DVTKit/NSCopying-Protocol.h>
#import <DVTKit/NSSecureCoding-Protocol.h>

@interface _DVTFilterTokenFieldValue : NSObject <NSCopying, NSSecureCoding>
{
    int _operatorType;
    id _tokenFieldObjectValue;
}

+ (BOOL)supportsSecureCoding;
@property(nonatomic) int operatorType; // @synthesize operatorType=_operatorType;
@property(retain, nonatomic) id tokenFieldObjectValue; // @synthesize tokenFieldObjectValue=_tokenFieldObjectValue;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)initWithTokenFieldObjectValue:(id)arg1 operatorType:(int)arg2;
- (BOOL)isNotEmpty;

@end

