//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  6 2019 20:12:56).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSSearchField.h>

__attribute__((visibility("hidden")))
@interface _TtC6DVTKit31DVTNavigationPopoverFilterField : NSSearchField
{
    // Error parsing type: , name: filterFieldDelegate
    // Error parsing type: , name: filterButton
    // Error parsing type: , name: backButton
    // Error parsing type: , name: mode
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)resizeSubviewsWithOldSize:(struct CGSize)arg1;
- (void)awakeFromNib;
- (void)clickButtonWithSender:(id)arg1;
- (struct CGRect)rectForSearchTextWhenCentered:(BOOL)arg1;

@end

