//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTKit/_TtC6DVTKit33DVTNavigationPopoverTableCellView.h>

@class NSTextField;

__attribute__((visibility("hidden")))
@interface _TtC6DVTKit36DVTNavNavigationPopoverTableCellView : _TtC6DVTKit33DVTNavigationPopoverTableCellView
{
    // Error parsing type: , name: subtitleTextField
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)awakeFromNib;
@property(nonatomic, retain) NSTextField *subtitleTextField; // @synthesize subtitleTextField;

@end

