//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <DVTKit/DVTGraphLayer-Protocol.h>

@class DVTGraph, DVTGraphLayerSelectionDetails, NSString;

@interface DVTAbstractGraphLayer : NSObject <DVTGraphLayer>
{
    BOOL _wantsClipping;
    DVTGraph *_graph;
    DVTGraphLayerSelectionDetails *_selectionDetails;
}

- (void).cxx_destruct;
@property BOOL wantsClipping; // @synthesize wantsClipping=_wantsClipping;
@property(retain) DVTGraphLayerSelectionDetails *selectionDetails; // @synthesize selectionDetails=_selectionDetails;
@property(readonly) __weak DVTGraph *graph; // @synthesize graph=_graph;
- (void)clearSelection;
- (BOOL)selectNext;
- (BOOL)selectPrevious;
- (void)selectDataAtIndex:(unsigned long long)arg1;
- (BOOL)selectDataAtPoint:(struct CGPoint)arg1;
- (void)drawLayerWithVisibleBounds:(struct _DVTGraphBounds)arg1;
- (id)initWithGraph:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

