//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface DVTAnnotation : NSObject
{
    double _precedence;
    id _representedObject;
    BOOL _visible;
}

- (void).cxx_destruct;
@property(retain) id representedObject; // @synthesize representedObject=_representedObject;
@property(getter=isVisible) BOOL visible; // @synthesize visible=_visible;
@property double precedence; // @synthesize precedence=_precedence;
@property(readonly) BOOL hideCarets;
- (id)annotationDisplayDescription;
- (id)annotationDisplayName;
- (long long)comparePrecedence:(id)arg1;
- (id)init;

@end

