//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSSplitViewController.h>

@class DVTObservingToken;

@interface DVTDevicesWindowSplitViewController : NSSplitViewController
{
    DVTObservingToken *_selectionObserver;
}

@property(retain) DVTObservingToken *selectionObserver; // @synthesize selectionObserver=_selectionObserver;
- (void).cxx_destruct;
- (void)_updateDetailsWithDevice:(id)arg1;
- (BOOL)splitView:(id)arg1 canCollapseSubview:(id)arg2;
@property long long mode;
- (void)viewWillDisappear;
- (void)viewWillAppear;

@end

