//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTFoundation/DVTDiffLineDataSource.h>

@interface DVTDiffTextStorageDataSource : DVTDiffLineDataSource
{
}

+ (void)initialize;
- (void)_textStorageDidProcessEditing:(id)arg1;
- (void)_coalescedTextStorageDidProcessEditing:(id)arg1;
- (id)THREAD_arrangedContent;
- (id)arrangedContent;
- (id)THREAD_content;
- (void)didChangeContent;
- (void)willChangeContent;
- (void)dealloc;
- (id)initWithContent:(id)arg1;

@end

