//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTKit/DVTBorderedView.h>

@class NSButton, NSImage, NSImageView, NSString, NSTextField;
@protocol DVTDisclosureHeaderViewDelegate;

@interface DVTDisclosureHeaderView : DVTBorderedView
{
    NSButton *_disclosureButton;
    NSTextField *_titleField;
    NSButton *_closeButton;
    NSImageView *_iconView;
    double _distanceFromLeftEdgeToDisclosureButton;
    CDUnknownBlockType _closeClickHandler;
    double _rightEdgeInset;
    unsigned long long _disclosureButtonPosition;
    BOOL _disclosed;
    BOOL _disclosable;
    BOOL _draggable;
    BOOL _drawsBottomBorder;
    long long _extendedDisclosureHitArea;
    double _preferredHeight;
    id <DVTDisclosureHeaderViewDelegate> _delegate;
}

@property __weak id <DVTDisclosureHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
@property double preferredHeight; // @synthesize preferredHeight=_preferredHeight;
@property(nonatomic) long long extendedDisclosureHitArea; // @synthesize extendedDisclosureHitArea=_extendedDisclosureHitArea;
@property(readonly) NSButton *closeButton; // @synthesize closeButton=_closeButton;
@property(nonatomic, getter=isDisclosed) BOOL disclosed; // @synthesize disclosed=_disclosed;
@property(getter=isDraggable) BOOL draggable; // @synthesize draggable=_draggable;
@property(nonatomic, getter=isDisclosable) BOOL disclosable; // @synthesize disclosable=_disclosable;
@property double rightEdgeInset; // @synthesize rightEdgeInset=_rightEdgeInset;
@property(nonatomic) unsigned long long disclosureButtonPosition; // @synthesize disclosureButtonPosition=_disclosureButtonPosition;
@property double distanceFromLeftEdgeToDisclosureButton; // @synthesize distanceFromLeftEdgeToDisclosureButton=_distanceFromLeftEdgeToDisclosureButton;
- (void).cxx_destruct;
- (void)_updateBottomBorderColor;
@property BOOL drawsBottomBorder;
- (void)layoutBottomUp;
- (void)layoutTopDown;
@property(copy) NSImage *icon;
@property(readonly) struct CGRect grabRect;
@property(retain) NSTextField *titleField;
@property(copy) NSString *title;
- (void)userToggledDisclosureState:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)insertCloseButtonWithAccessibilityDescription:(id)arg1 withClickHandler:(CDUnknownBlockType)arg2;
- (void)insertCloseButtonWithClickHandler:(CDUnknownBlockType)arg1;
- (void)closeButtonWasClicked:(id)arg1;
- (void)insertCloseButtonWithTarget:(id)arg1 action:(SEL)arg2 withAccessibilityDescription:(id)arg3;
- (void)insertCloseButtonWithTarget:(id)arg1 action:(SEL)arg2;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)commonInit;
- (void)_configureIconView;
- (id)defaultTitleField;
- (id)defaultCloseButton;
@property(retain) NSButton *disclosureButton;
- (id)defaultDisclosureButton;

@end

