//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  6 2019 20:12:56).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class NSImageView, NSTextField;

@interface DVTFileLiteralInfoCellView : NSTableCellView
{
    NSTextField *_subtitle;
    NSImageView *_checkmark;
}

@property(retain, nonatomic) NSImageView *checkmark; // @synthesize checkmark=_checkmark;
@property(retain, nonatomic) NSTextField *subtitle; // @synthesize subtitle=_subtitle;
- (void).cxx_destruct;

@end

