//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTKit/DVTPlistNode.h>

@class NSString;

@interface DVTPlistCommentNode : DVTPlistNode
{
    NSString *_comment;
    BOOL isMultiLine;
}

- (void).cxx_destruct;
@property BOOL isMultiLine; // @synthesize isMultiLine;
- (id)rawPlist;
- (id)xmlStringWithIndent:(id)arg1;
- (id)plistStringWithIndent:(id)arg1;
- (id)value;
- (void)setValueFromPlist:(id)arg1;
- (void)setValue:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (BOOL)isPlistCommentNode;

@end

