//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTKit/DVTLineRangeCharacterRangeConverter-Protocol.h>
#import <DVTKit/NSObject-Protocol.h>

@class DVTSourceCodeLanguage, DVTSourceModelItem, NSString;

@protocol DVTSourceBufferProvider <NSObject, DVTLineRangeCharacterRangeConverter>
- (unsigned long long)leadingWhitespacePositionsForLine:(unsigned long long)arg1;
- (unsigned long long)length;
- (NSString *)string;

@optional
- (void)scheduleLazyInvalidationForRange:(struct _NSRange)arg1;
- (NSString *)stringForItem:(DVTSourceModelItem *)arg1;
- (DVTSourceCodeLanguage *)language;
@end

