//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSAttributedString, NSString;

@interface DVTSharedFindState : NSObject
{
    NSAttributedString *_findAttributedString;
    NSAttributedString *_replaceAttributedString;
}

+ (id)keyPathsForValuesAffectingReplaceString;
+ (id)keyPathsForValuesAffectingFindString;
+ (id)sharedInstance;
+ (id)sharedFindState;
+ (void)initialize;
+ (void)_setFindPasteboardStringValue:(id)arg1;
+ (id)_findPasteboardStringValue;
+ (void)_setFindPasteboardAttributedStringValue:(id)arg1;
+ (id)_findPasteboardAttributedStringValue;
- (void).cxx_destruct;
@property(nonatomic) BOOL wrapText;
@property(nonatomic) BOOL ignoresCase;
@property(nonatomic) unsigned long long matchStyle;
@property(nonatomic) unsigned long long findType;
@property(copy) NSString *replaceString;
@property(copy, nonatomic) NSAttributedString *replaceAttributedString;
@property(copy) NSAttributedString *findAttributedString;
@property(copy) NSString *findString;
- (void)_applicationDidBecomeActive:(id)arg1;
- (void)dealloc;
- (id)initWithFindAttributedString:(id)arg1;

@end

