//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSScrollView.h>

@class DVTComparisonSplitView;
@protocol DVTSourceTextScrollViewDelegate;

@interface DVTSourceTextScrollView : NSScrollView
{
    id <DVTSourceTextScrollViewDelegate> _delegate;
    DVTComparisonSplitView *_comparisonSplitView;
}

+ (BOOL)isCompatibleWithResponsiveScrolling;
@property(retain) DVTComparisonSplitView *comparisonSplitView; // @synthesize comparisonSplitView=_comparisonSplitView;
@property(retain) id <DVTSourceTextScrollViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)_pointInVisibleScroller:(struct CGPoint)arg1;
- (void)reflectScrolledClipView:(id)arg1;
- (void)scrollWheel:(id)arg1;
- (void)setFrameSize:(struct CGSize)arg1;
- (void)viewDidEndLiveResize;
- (void)viewWillStartLiveResize;

@end

