//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSWindow.h>

@protocol DVTTextCompletionListDataSource;

@interface DVTTextCompletionWindow : NSWindow
{
    id <DVTTextCompletionListDataSource> _dataSource;
}

- (void).cxx_destruct;
@property(retain) id <DVTTextCompletionListDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (id)accessibilityParent;
- (id)accessibilityTitle;
- (BOOL)isAccessibilityElement;
- (BOOL)_shouldShowCursorRects;
- (BOOL)canBecomeMainWindow;
- (BOOL)canBecomeKeyWindow;

@end

