//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface DVTThemeUtilities : NSObject
{
}

+ (void)initializeDVTKitFonts;
+ (id)_loadThemeFromURL:(id)arg1 error:(id *)arg2;
+ (id)propertyValuePairsForThemeAtPath:(id)arg1;
+ (id)_parseFontElement:(id)arg1 name:(id *)arg2 error:(id *)arg3;
+ (id)_parseInsetElement:(id)arg1 name:(id *)arg2 error:(id *)arg3;
+ (id)_parseGradientElement:(id)arg1 name:(id *)arg2 error:(id *)arg3;
+ (id)_parseColorElement:(id)arg1 requireName:(BOOL)arg2 name:(id *)arg3 allowLocation:(BOOL)arg4 location:(double *)arg5 error:(id *)arg6;
+ (id)_parseStringElement:(id)arg1 name:(id *)arg2 error:(id *)arg3;
+ (id)_parseNameValueElement:(id)arg1 name:(id *)arg2 error:(id *)arg3;

@end

