//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSColor.h>

@interface NSColor (DVTNSColorAdditions)
+ (id)dvt_colorFromHexRGB:(id)arg1;
+ (id)dvt_colorFromRGBAString:(id)arg1;
- (id)dvt_colorResolvedInAppearance:(id)arg1;
- (BOOL)dvt_isDark;
- (id)dvt_colorWithSaturationComponent:(double)arg1 andBrightnessComponent:(double)arg2;
- (id)dvt_colorWithBrightnessComponent:(double)arg1;
- (id)dvt_colorWithSaturationComponent:(double)arg1;
- (id)dvt_colorByMultiplyingSaturation:(double)arg1 andBrightness:(double)arg2;
- (id)dvt_colorByMultiplyingSaturation:(double)arg1;
- (id)dvt_colorByMultiplyingAlpha:(double)arg1;
- (id)dvt_colorByMultiplyingBrightness:(double)arg1;
- (id)dvt_colorByShiftingHue:(double)arg1;
- (id)dvt_complementaryColor;
- (id)dvt_RGBAStringRepresentation;
- (id)dvt_hexRGBRepresentation;
@end

