//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSFont.h>

@interface NSFont (DVTNSFontAdditions)
+ (id)dvt_boldSystemFontOfSize:(double)arg1;
+ (id)dvt_semiBoldSystemFontOfSize:(double)arg1;
+ (id)dvt_mediumSystemFontOfSize:(double)arg1;
+ (id)dvt_systemFontOfSize:(double)arg1;
+ (id)dvt_systemFontOfSize:(double)arg1 weight:(double)arg2;
- (id)dvt_deriveFontWithSizeDelta:(double)arg1;
@end

