//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTBindingHelper;

@interface NSObject (DVTBindingHelperAccess)
- (void)dvt_clearBindingHelper;
@property(readonly) DVTBindingHelper *dvt_bindingHelper;
@property(readonly) DVTBindingHelper *bindingHelper;
@end

