//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <QuartzCore/CAShapeLayer.h>

@class MISSING_TYPE;

@interface _TtC12SourceEditor24SourceEditorLozengeLayer : CAShapeLayer
{
    MISSING_TYPE *verticalBarThickness;
    MISSING_TYPE *topLineFrame;
    MISSING_TYPE *bottomLineFrame;
    MISSING_TYPE *hotspotFrame;
    MISSING_TYPE *pathCornerRadius;
    MISSING_TYPE *secondaryHotspotFrame;
    MISSING_TYPE *handleFrame;
    MISSING_TYPE *$__lazy_storage_$_hotspotLayer;
    MISSING_TYPE *handleColorOverride;
    MISSING_TYPE *$__lazy_storage_$_handleLayer;
    MISSING_TYPE *closingCurlyBraceHotspotFrame;
    MISSING_TYPE *shapePath;
    MISSING_TYPE *color;
    MISSING_TYPE *enableFill;
    MISSING_TYPE *animated;
    MISSING_TYPE *animationDuration;
}

- (void).cxx_destruct;
- (id)init;
- (id)actionForKey:(id)arg1;
- (void)layoutSublayers;
- (id)initWithCoder:(id)arg1;
- (id)initWithLayer:(id)arg1;

@end

