//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC12SourceEditor22SourceEditorDataSource : _TtCs12_SwiftObject
{
    MISSING_TYPE *lineData;
    MISSING_TYPE *utf8RangeData;
    MISSING_TYPE *contents;
    MISSING_TYPE *transactionNesting;
    MISSING_TYPE *editedRange;
    MISSING_TYPE *invalidatedRange;
    MISSING_TYPE *lockedDocument;
    MISSING_TYPE *name;
    MISSING_TYPE *language;
    MISSING_TYPE *$__lazy_storage_$_languageService;
    MISSING_TYPE *formattingOptions;
    MISSING_TYPE *observerTokens;
    MISSING_TYPE *journalObserverTokens;
    MISSING_TYPE *documentSettings;
    MISSING_TYPE *delegate;
    MISSING_TYPE *$__lazy_storage_$_undoManager;
    MISSING_TYPE *isPermanentlyClosed;
    MISSING_TYPE *newObserverTokens;
    MISSING_TYPE *diagnosticProviderToken;
    MISSING_TYPE *diagnosticManager;
}

@end

