//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SourceEditor/_TtC12SourceEditor25NoImplicitAnimationsLayer.h>

@class MISSING_TYPE;

@interface _TtC12SourceEditor20MinimapAuxViewsLayer : _TtC12SourceEditor25NoImplicitAnimationsLayer
{
    MISSING_TYPE *auxiliaryViewDescriptors;
    MISSING_TYPE *fillColor;
}

- (void).cxx_destruct;
- (void)drawInContext:(struct CGContext *)arg1;
- (id)initWithLayer:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

