//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC12SourceEditorP33_5B634B9DCDB55D6100C0DC388A389C2748SourceEditorLineAnnotationDropdownItemLayoutInfo : _TtCs12_SwiftObject
{
    MISSING_TYPE *message;
    MISSING_TYPE *accessories;
    MISSING_TYPE *layoutSize;
}

@end

