//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC12SourceEditor20SourceEditorLineData : _TtCs12_SwiftObject
{
    MISSING_TYPE *lineContentRange;
    MISSING_TYPE *lineTerminatorLength;
    MISSING_TYPE *placeholders;
    MISSING_TYPE *hidden;
    MISSING_TYPE *layer;
    MISSING_TYPE *auxViews;
    MISSING_TYPE *accessoryView;
    MISSING_TYPE *substitutionView;
    MISSING_TYPE *accessibilityElement;
}

@end

