//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSImageView.h>

__attribute__((visibility("hidden")))
@interface _TtCC12SourceEditor41SourceEditorLineAnnotationCategoryControl15CategoryControl : NSImageView
{
    // Error parsing type: , name: category
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)animationForKey:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

