//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC12SourceEditor11DisplayLink : NSObject
{
    MISSING_TYPE *target;
    MISSING_TYPE *sel;
    MISSING_TYPE *displayLink;
    MISSING_TYPE *isInvalid;
    MISSING_TYPE *isPaused;
}

- (void).cxx_destruct;
- (id)init;

@end

