//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC12SourceEditor25CodeCoverageVisualization : SwiftObject
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: sourceEditorView
    // Error parsing type: , name: coverageLayersByLine
    // Error parsing type: , name: installedCoverageRanges
    // Error parsing type: , name: highlightLayers
    // Error parsing type: , name: highlightedCoverageLayersByLine
    // Error parsing type: , name: reusableCoverageLayers
    // Error parsing type: , name: coverageRangesByLineNumber
    // Error parsing type: , name: ribbonWidth
    // Error parsing type: , name: defaultCountColor
    // Error parsing type: , name: showCoverageCounts
    // Error parsing type: , name: ribbonView
    // Error parsing type: , name: ribbonBackgroundView
    // Error parsing type: , name: ribbonBackgroundColor
    // Error parsing type: , name: ribbonEdgeColor
    // Error parsing type: , name: defaultFont
}

@end

