//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC12SourceEditor25RenameLayoutVisualization : SwiftObject
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: focusedRangeLayer
    // Error parsing type: , name: primaryRangesLayer
    // Error parsing type: , name: secondaryRangesLayer
    // Error parsing type: , name: disabledSecondaryRangesLayer
    // Error parsing type: , name: enableButtonLayer
    // Error parsing type: , name: enableImageButtonLayer
    // Error parsing type: , name: hitTestViews
}

@end

