//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC12SourceEditorP33_8102EB5F02AAC7A963B4E461E023FA4742UnfoldingSourceEditorViewPlaceholderMargin : _TtCs12_SwiftObject
{
    MISSING_TYPE *leftMargin;
}

@end

