//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  6 2019 20:12:56).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC12SourceEditor16RenameController : _TtCs12_SwiftObject
{
    // Error parsing type: , name: $__lazy_storage_$_layoutVisualization
    // Error parsing type: , name: focusedIndex
    // Error parsing type: , name: editAssistant
    // Error parsing type: , name: journal
    // Error parsing type: , name: managedPrimaryEditingRanges
    // Error parsing type: , name: managedSecondaryEditingRanges
    // Error parsing type: , name: originalText
    // Error parsing type: , name: disableAll
    // Error parsing type: , name: delegate
    // Error parsing type: , name: clickDelegate
    // Error parsing type: , name: enableButtonRange
    // Error parsing type: , name: enableButtonIsEnabled
    // Error parsing type: , name: enableButtonIsPressed
    // Error parsing type: , name: enableButtonTrackingRect
    // Error parsing type: , name: updating
}

@end

