//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC12SourceEditor17MinimapAttributes : _TtCs12_SwiftObject
{
    MISSING_TYPE *preferredWidthPercentageOfEditor;
    MISSING_TYPE *minMinimapWidth;
    MISSING_TYPE *maxMinimapWidth;
    MISSING_TYPE *minWidthToShowLandmarks;
    MISSING_TYPE *landmarkMarkFont;
    MISSING_TYPE *landmarkOpacity;
    MISSING_TYPE *expandedLandmarkBackgroundColorLight;
    MISSING_TYPE *expandedLandmarkBackgroundColorDark;
    MISSING_TYPE *expandedLandmarkBorderColorLight;
    MISSING_TYPE *expandedLandmarkBorderColorDark;
    MISSING_TYPE *viewportHighlightColorLight;
    MISSING_TYPE *viewportHighlightColorDark;
    MISSING_TYPE *minimumFontSizeToBaseExpandedLandmarksOn;
    MISSING_TYPE *baseLandmarkFontSize;
    MISSING_TYPE *baseBarHeight;
    MISSING_TYPE *baseBarSpacing;
    MISSING_TYPE *barHeight;
    MISSING_TYPE *barSpacing;
    MISSING_TYPE *landmarkInterval;
    MISSING_TYPE *plainTextBarColor;
    MISSING_TYPE *landmarkTextColor;
    MISSING_TYPE *expandedLandmarkTypeFont;
    MISSING_TYPE *expandedLandmarkMarkFont;
    MISSING_TYPE *expandedLandmarkBackgroundColor;
    MISSING_TYPE *expandedLandmarkBorderColor;
    MISSING_TYPE *expandedLandmarkFontSize;
    MISSING_TYPE *expandedLandmarkPopoverHeight;
    MISSING_TYPE *landmarkSeparatorColor;
    MISSING_TYPE *viewportHighlightColor;
    MISSING_TYPE *backgroundColor;
    MISSING_TYPE *dividerColor;
    MISSING_TYPE *auxViewBackgroundColor;
    MISSING_TYPE *syntaxTokenColorOpacity;
    MISSING_TYPE *landmarkSyntaxTokenColorOpacity;
    MISSING_TYPE *theme;
    MISSING_TYPE *hasLightBackground;
}

@end

