//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC12SourceEditor15DynamicAnimator : NSObject
{
    MISSING_TYPE *behaviors;
    MISSING_TYPE *displayLink;
}

- (void).cxx_destruct;
- (id)init;
- (void)step;

@end

