\\ T _SourceEditorDataSource.lineIndexForLineWithIdentifier(_:) T __T012SourceEditor0ab4DataA0C30lineIndexForLineWithIdentifierSiSgAA0abgI0VF
\\ T _SourceEditorDataSource.positionAtEndOfLine(_:) T __T012SourceEditor0ab4DataA0C19positionAtEndOfLineAA0aB8PositionVSiF
\\ T _SourceEditorDataSource.nextCharacterPositionFromPosition(_:) T __T012SourceEditor0ab4DataA0C025nextCharacterPositionFromF0AA0abF0VSgAFF
\\ T _SourceEditorDataSource.textInRange(_:) T __T012SourceEditor0ab4DataA0C11textInRangeSSAA0abF0VF
\\ T _SourceEditorDataSource.validateRange(_:) T __T012SourceEditor0ab4DataA0C13validateRangeyAA0abE0VF
\\ T _SourceEditorDataSource.languageService.getter T __T012SourceEditor0ab4DataA0C15languageServiceAA0ab8LanguageE0_pfg
\\ T _SourceEditorDataSource.previousCharacterPositionFromPosition(_:) T __T012SourceEditor0ab4DataA0C029previousCharacterPositionFromF0AA0abF0VSgAFF
\\ T _SourceEditorDataSource.lineCount.getter T __T012SourceEditor0ab4DataA0C9lineCountSifg
\\ T _SourceEditorDataSource.positionForEndOfDocument() T __T012SourceEditor0ab4DataA0C24positionForEndOfDocumentAA0aB8PositionVyF
\\ T _SourceEditorDataSource.firstPlaceholderRangeInRange(_:) T __T012SourceEditor0ab4DataA0C023firstPlaceholderRangeInF0AA0abF0VSgAFF
\\ T _SourceEditorDataSource.placeholderInformationForLine(_:) T __T012SourceEditor0ab4DataA0C29placeholderInformationForLineSaySC8_NSRangeV_AA19PlaceholderMetadataOtGSiF
\\ T _SourceEditorDataSource.lineContentLengthForLine(_:) T __T012SourceEditor0ab4DataA0C24lineContentLengthForLineS2iF
\\ T _SourceEditorDataSource.indentLine(_:allowUnindent:allowIndent:) T __T012SourceEditor0ab4DataA0C10indentLineySi_Sb13allowUnindentSb0F6IndenttF
\\ T _SourceEditorDataSource.leadingWhitespaceWidthForLine(_:expandTabs:) T __T012SourceEditor0ab4DataA0C29leadingWhitespaceWidthForLineS2i_Sb10expandTabstF
\\ T _SourceEditorDataSource.lineContentForLine(_:) T __T012SourceEditor0ab4DataA0C18lineContentForLineSSSiF
\\ T _SourceEditorDataSource.beginEditTransaction() T __T012SourceEditor0ab4DataA0C20beginEditTransactionyyF
\\ T _SourceEditorDataSource.insertTextAtPosition(_:position:) T __T012SourceEditor0ab4DataA0C20insertTextAtPositionAA0abG0VSS_AF8positiontF
\\ T _SourceEditorDataSource.endEditTransaction() T __T012SourceEditor0ab4DataA0C18endEditTransactionyyF
\\ T _SourceEditorDataSource.__allocating_init(usingMutableString:language:) T __T012SourceEditor0ab4DataA0CACSo15NSMutableStringC012usingMutableE0_AA0aB8Language_pSg8languagetcfC
\\ T _SourceEditorDataSource.diagnosticManager.setter T __T012SourceEditor0ab4DataA0C17diagnosticManagerAA0ab10DiagnosticE0CSgfs
\\ T _SourceEditorDataSource.identifierForLine(_:) T __T012SourceEditor0ab4DataA0C17identifierForLineAA0abF10IdentifierVSiF
\\ T _SourceEditorDataSource.placeholderRangeAtPosition(_:) T __T012SourceEditor0ab4DataA0C26placeholderRangeAtPositionAA0abE0VSgAA0abG0VF
\\ T _SourceEditorDataSource.isEditing.getter T __T012SourceEditor0ab4DataA0C9isEditingSbfg
\\ T _SourceEditorDataSource.undoManager.getter T __T012SourceEditor0ab4DataA0C11undoManagerAA0ab4UndoE0Cfg
\\ T _SourceEditorDataSource.positionForBeginningOfDocument() T __T012SourceEditor0ab4DataA0C30positionForBeginningOfDocumentAA0aB8PositionVyF
\\ T _SourceEditorDataSource.tokenRangeAtPosition(_:) T __T012SourceEditor0ab4DataA0C20tokenRangeAtPositionAA0aB9TokenTypeOSg_AA0abE0VtSgAA0abG0VF
\\ T _SourceEditorDataSource.characterRangeAtPosition(_:) T __T012SourceEditor0ab4DataA0C24characterRangeAtPositionAA0abE0VAA0abG0VF
\\ T _SourceEditorDataSource.string.getter T __T012SourceEditor0ab4DataA0C6stringSSfg
\\ T _SourceEditorDataSource.internalCharOffsetFromPosition(_:) T __T012SourceEditor0ab4DataA0C30internalCharOffsetFromPositionSiAA0abH0VF
\\ T _SourceEditorDataSource.positionFromInternalCharOffset(_:lineHint:) T __T012SourceEditor0ab4DataA0C30positionFromInternalCharOffsetAA0aB8PositionVSi_Si8lineHinttF
\\ T _SourceEditorDataSource.isCommentOrStringLiteralAtPosition(_:) T __T012SourceEditor0ab4DataA0C34isCommentOrStringLiteralAtPositionSbAA0abJ0VF
\\ T _SourceEditorDataSource.naturalLanguageSyntaxTypeAtPosition(_:) T __T012SourceEditor0ab4DataA0C35naturalLanguageSyntaxTypeAtPositionAA0ab5TokenG0O_AA0aB5RangeVtSgAA0abI0VF
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceWillInsertTextInRange(_:) in conformance SourceEditorView t __T012SourceEditor0aB4ViewCAA0ab4DataA8ObserverA2aDP04dataA21WillInsertTextInRangeyAA0abK0VFTW
\\ T _SourceEditorDataSourceObserver.dataSourceWillInsertTextInRange(_:) T __T012SourceEditor0ab4DataA8ObserverPAAE04dataA21WillInsertTextInRangeyAA0abJ0VF
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceWillDeleteTextInRange(_:) in conformance SourceEditorView t __T012SourceEditor0aB4ViewCAA0ab4DataA8ObserverA2aDP04dataA21WillDeleteTextInRangeyAA0abK0VFTW
\\ T _SourceEditorDataSourceObserver.dataSourceWillDeleteTextInRange(_:) T __T012SourceEditor0ab4DataA8ObserverPAAE04dataA21WillDeleteTextInRangeyAA0abJ0VF
\\ T _SourceEditorDataSource.balancedCountForOpenDelimiter(_:closeDelimiter:) T __T012SourceEditor0ab4DataA0C29balancedCountForOpenDelimiterSis9CharacterV_AF05closeH0tF
\\ T _SourceEditorDataSource.findMatchingDelimiterFromPosition(_:constrainedTo:) T __T012SourceEditor0ab4DataA0C33findMatchingDelimiterFromPositionAA0abH0VSgAF_AA0aB5RangeVSg13constrainedTotF
\\ T _SourceEditorDataSource.deleteTextInRange(_:) T __T012SourceEditor0ab4DataA0C17deleteTextInRangeAA0aB8PositionVAA0abG0VF
\\ T _SourceEditorDataSource.removeObserver(observer:) T __T012SourceEditor0ab4DataA0C14removeObserveryAA0abcaE0_p8observer_tF
\\ T _SourceEditorDataSource.addObserver(observer:) T __T012SourceEditor0ab4DataA0C11addObserveryAA0abcaE0_p8observer_tF
\\ T _SourceEditorDataSource.isEditableRange(_:multiLine:) T __T012SourceEditor0ab4DataA0C15isEditableRangeSbAA0abF0V_Sb9multiLinetF
\\ T _SourceEditorDataSource.editableRangeAtPosition(_:) T __T012SourceEditor0ab4DataA0C23editableRangeAtPositionAA0abE0V_SbtSgAA0abG0VF
\\ T _SourceEditorDataSource.nsRange(from:) T __T012SourceEditor0ab4DataA0C7nsRangeSC8_NSRangeVAA0abE0V4from_tF
\\ T _SourceEditorDataSource.rangeForLine(_:) T __T012SourceEditor0ab4DataA0C12rangeForLineAA0aB5RangeVSiF
\\ T _SourceEditorDataSource.sourceRange(from:lineHint:) T __T012SourceEditor0ab4DataA0C11sourceRangeAA0abE0VSC8_NSRangeV4from_Si8lineHinttF
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceContentsChanged(_:) in conformance FoldingController t __T012SourceEditor17FoldingControllerCAA0ab4DataA8ObserverA2aDP04dataA15ContentsChangedyAA0aB5RangeVSgFTW
\\ T _SourceEditorDataSourceObserver.dataSourceContentsChanged(_:) T __T012SourceEditor0ab4DataA8ObserverPAAE04dataA15ContentsChangedyAA0aB5RangeVSgF
\\ T _SourceEditorDataSourceObserver.dataSourceDidDeleteLines(_:) T __T012SourceEditor0ab4DataA8ObserverPAAE04dataA14DidDeleteLinesy10Foundation8IndexSetVF
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceBeginEditTransaction() in conformance FoldingController t __T012SourceEditor17FoldingControllerCAA0ab4DataA8ObserverA2aDP04dataA20BeginEditTransactionyyFTW
\\ T _SourceEditorDataSourceObserver.dataSourceBeginEditTransaction() T __T012SourceEditor0ab4DataA8ObserverPAAE04dataA20BeginEditTransactionyyF
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceEndEditTransaction() in conformance FoldingController t __T012SourceEditor17FoldingControllerCAA0ab4DataA8ObserverA2aDP04dataA18EndEditTransactionyyFTW
\\ T _SourceEditorDataSourceObserver.dataSourceEndEditTransaction() T __T012SourceEditor0ab4DataA8ObserverPAAE04dataA18EndEditTransactionyyF
\\ T _SourceEditorDataSource.lineWithIdentifierExists(_:) T __T012SourceEditor0ab4DataA0C24lineWithIdentifierExistsSbAA0ab4LineF0VF
\\ T _NSNotification.Name.SourceEditorDataSourceWillChange.unsafeMutableAddressor T __T0So14NSNotificationC4NameV12SourceEditorE0cd4DataC10WillChangeADfau
\\ T _static NSNotification.Name.SourceEditorDataSourceWillChange.getter T __T0So14NSNotificationC4NameV12SourceEditorE0cd4DataC10WillChangeADfgZ
\\ T _NSNotification.Name.SourceEditorDataSourceChanged.unsafeMutableAddressor T __T0So14NSNotificationC4NameV12SourceEditorE0cd4DataC7ChangedADfau
\\ T _static NSNotification.Name.SourceEditorDataSourceChanged.getter T __T0So14NSNotificationC4NameV12SourceEditorE0cd4DataC7ChangedADfgZ
\\ T _NSNotification.Name.SourceEditorDataSourceDidInsertText.unsafeMutableAddressor T __T0So14NSNotificationC4NameV12SourceEditorE0cd4DataC13DidInsertTextADfau
\\ T _static NSNotification.Name.SourceEditorDataSourceDidInsertText.getter T __T0So14NSNotificationC4NameV12SourceEditorE0cd4DataC13DidInsertTextADfgZ
\\ T _NSNotification.Name.SourceEditorDataSourceDidDeleteText.unsafeMutableAddressor T __T0So14NSNotificationC4NameV12SourceEditorE0cd4DataC13DidDeleteTextADfau
\\ T _static NSNotification.Name.SourceEditorDataSourceDidDeleteText.getter T __T0So14NSNotificationC4NameV12SourceEditorE0cd4DataC13DidDeleteTextADfgZ
\\ T _SourceEditorDataSourceChangedNotificationEditedStartLineKey.unsafeMutableAddressor T __T012SourceEditor0ab4DataA37ChangedNotificationEditedStartLineKeySSfau
\\ T _SourceEditorDataSourceChangedNotificationEditedStartColKey.unsafeMutableAddressor T __T012SourceEditor0ab4DataA36ChangedNotificationEditedStartColKeySSfau
\\ T _SourceEditorDataSourceChangedNotificationEditedEndLineKey.unsafeMutableAddressor T __T012SourceEditor0ab4DataA35ChangedNotificationEditedEndLineKeySSfau
\\ T _SourceEditorDataSourceChangedNotificationEditedEndColKey.unsafeMutableAddressor T __T012SourceEditor0ab4DataA34ChangedNotificationEditedEndColKeySSfau
\\ T _SourceEditorDataSourceDidInsertTextNotificationStartLineKey.unsafeMutableAddressor T __T012SourceEditor0ab4DataA37DidInsertTextNotificationStartLineKeySSfau
\\ T _SourceEditorDataSourceDidInsertTextNotificationStartColKey.unsafeMutableAddressor T __T012SourceEditor0ab4DataA36DidInsertTextNotificationStartColKeySSfau
\\ T _SourceEditorDataSourceDidInsertTextNotificationCharOffsetKey.unsafeMutableAddressor T __T012SourceEditor0ab4DataA38DidInsertTextNotificationCharOffsetKeySSfau
\\ T _SourceEditorDataSourceDidInsertTextNotificationTextKey.unsafeMutableAddressor T __T012SourceEditor0ab4Dataa25DidInsertTextNotificationF3KeySSfau
\\ T _SourceEditorDataSourceDidDeleteTextNotificationStartLineKey.unsafeMutableAddressor T __T012SourceEditor0ab4DataA37DidDeleteTextNotificationStartLineKeySSfau
\\ T _SourceEditorDataSourceDidDeleteTextNotificationStartColKey.unsafeMutableAddressor T __T012SourceEditor0ab4DataA36DidDeleteTextNotificationStartColKeySSfau
\\ T _SourceEditorDataSourceDidDeleteTextNotificationEndLineKey.unsafeMutableAddressor T __T012SourceEditor0ab4DataA35DidDeleteTextNotificationEndLineKeySSfau
\\ T _SourceEditorDataSourceDidDeleteTextNotificationEndColKey.unsafeMutableAddressor T __T012SourceEditor0ab4DataA34DidDeleteTextNotificationEndColKeySSfau
\\ T _SourceEditorDataSourceDidDeleteTextNotificationCharOffsetKey.unsafeMutableAddressor T __T012SourceEditor0ab4DataA38DidDeleteTextNotificationCharOffsetKeySSfau
\\ T _SourceEditorDataSourceDidDeleteTextNotificationCharLengthKey.unsafeMutableAddressor T __T012SourceEditor0ab4DataA38DidDeleteTextNotificationCharLengthKeySSfau
\\ T _SourceEditorDataSourceDidDeleteTextNotificationTextKey.unsafeMutableAddressor T __T012SourceEditor0ab4Dataa25DidDeleteTextNotificationF3KeySSfau
\\ T _SourceEditorDataSourceObjectLiteralNameColorLiteral.unsafeMutableAddressor T __T012SourceEditor0ab4Dataa22ObjectLiteralNameColorE0SSfau
\\ T _SourceEditorDataSourceObjectLiteralNameImageLiteral.unsafeMutableAddressor T __T012SourceEditor0ab4Dataa22ObjectLiteralNameImageE0SSfau
\\ T _SourceEditorDataSourceObjectLiteralNameFileLiteral.unsafeMutableAddressor T __T012SourceEditor0ab4Dataa21ObjectLiteralNameFileE0SSfau
\\ T _SourceEditorDataSource.name.getter T __T012SourceEditor0ab4DataA0C4nameSSSgfg
\\ T _SourceEditorDataSource.lockedDocument.getter T __T012SourceEditor0ab4DataA0C14lockedDocumentSbfg
\\ T _SourceEditorDataSource.language.getter T __T012SourceEditor0ab4DataA0C8languageAA0aB8Language_pSgfg
\\ T _SourceEditorDataSource.formattingOptions.getter T __T012SourceEditor0ab4DataA0C17formattingOptionsAA0ab10FormattingE0Vfg
\\ T _SourceEditorDataSource.formattingOptions.setter T __T012SourceEditor0ab4DataA0C17formattingOptionsAA0ab10FormattingE0Vfs
\\ T _SourceEditorDataSource.formattingOptions.materializeForSet T __T012SourceEditor0ab4DataA0C17formattingOptionsAA0ab10FormattingE0Vfm
\\ T _SourceEditorDataSource.string.setter T __T012SourceEditor0ab4DataA0C6stringSSfs
\\ t _SourceEditorDataSource.observers.getter t __T012SourceEditor0ab4DataA0C9observers33_76DCD73D096C2A8A62A7C1A15575EAAALLSayAA0abcA8Observer_pSgGfg
\\ t _closure #1 in SourceEditorDataSource.string.materializeForSet t __T012SourceEditor0ab4DataA0C6stringSSfmytfU_
\\ T _SourceEditorDataSource.string.materializeForSet T __T012SourceEditor0ab4DataA0C6stringSSfm
\\ T _SourceEditorDataSource.documentSettings.didset T __T012SourceEditor0ab4DataA0C16documentSettingsAA0ab8DocumentE0_pSgfW
\\ T _SourceEditorDataSource.documentSettings.getter T __T012SourceEditor0ab4DataA0C16documentSettingsAA0ab8DocumentE0_pSgfg
\\ T _SourceEditorDataSource.documentSettings.setter T __T012SourceEditor0ab4DataA0C16documentSettingsAA0ab8DocumentE0_pSgfs
\\ t _closure #1 in SourceEditorDataSource.documentSettings.materializeForSet t __T012SourceEditor0ab4DataA0C16documentSettingsAA0ab8DocumentE0_pSgfmytfU_
\\ T _SourceEditorDataSource.documentSettings.materializeForSet T __T012SourceEditor0ab4DataA0C16documentSettingsAA0ab8DocumentE0_pSgfm
\\ T _SourceEditorDataSource.delegate.getter T __T012SourceEditor0ab4DataA0C8delegateAA0abcA8Delegate_pSgXwfg
\\ T _SourceEditorDataSource.delegate.setter T __T012SourceEditor0ab4DataA0C8delegateAA0abcA8Delegate_pSgXwfs
\\ t _closure #1 in SourceEditorDataSource.delegate.materializeForSet t __T012SourceEditor0ab4DataA0C8delegateAA0abcA8Delegate_pSgXwfmytfU_
\\ T _SourceEditorDataSource.delegate.materializeForSet T __T012SourceEditor0ab4DataA0C8delegateAA0abcA8Delegate_pSgXwfm
\\ T _SourceEditorDataSource.undoManager.setter T __T012SourceEditor0ab4DataA0C11undoManagerAA0ab4UndoE0Cfs
\\ t _closure #1 in SourceEditorDataSource.undoManager.materializeForSet t __T012SourceEditor0ab4DataA0C11undoManagerAA0ab4UndoE0CfmytfU_
\\ T _SourceEditorDataSource.undoManager.materializeForSet T __T012SourceEditor0ab4DataA0C11undoManagerAA0ab4UndoE0Cfm
\\ T _SourceEditorDataSource.__allocating_init(name:language:usingMutableString:) T __T012SourceEditor0ab4DataA0CACSS4name_AA0aB8Language_p8languageSo15NSMutableStringC012usingMutableH0tcfC
\\ T _SourceEditorDataSource.init(name:language:usingMutableString:) T __T012SourceEditor0ab4DataA0CACSS4name_AA0aB8Language_p8languageSo15NSMutableStringC012usingMutableH0tcfc
\\ T _SourceEditorDataSource.init(usingMutableString:language:) T __T012SourceEditor0ab4DataA0CACSo15NSMutableStringC012usingMutableE0_AA0aB8Language_pSg8languagetcfc
\\ T _SourceEditorDataSource.__allocating_init(languageService:language:usingMutableString:name:) T __T012SourceEditor0ab4DataA0CAcA0aB15LanguageService_p08languageE0_AA0abD0_p0F0So15NSMutableStringC012usingMutableH0SSSg4nametcfC
\\ T _SourceEditorDataSource.init(languageService:language:usingMutableString:name:) T __T012SourceEditor0ab4DataA0CAcA0aB15LanguageService_p08languageE0_AA0abD0_p0F0So15NSMutableStringC012usingMutableH0SSSg4nametcfc
\\ T _static SourceEditorDataSource.dataSourceWithGeneratedContent(for:using:completion:) T __T012SourceEditor0ab4DataA0C04dataA20WithGeneratedContentAA015LanguageServiceG21GenerationCoordinatorCSgAA0aB16DocumentSettings_p3for_AA0abH0_p5usingyAC0gJ6ResultOc10completiontFZ
\\ t _closure #1 in static SourceEditorDataSource.dataSourceWithGeneratedContent(for:using:completion:) t __T012SourceEditor0ab4DataA0C04dataA20WithGeneratedContentAA015LanguageServiceG21GenerationCoordinatorCSgAA0aB16DocumentSettings_p3for_AA0abH0_p5usingyAC0gJ6ResultOc10completiontFZyAaLOcfU_
\\ T _SourceEditorDataSource.clone(with:language:) T __T012SourceEditor0ab4DataA0C5cloneACSSSg4with_AA0aB8Language_pSg8languagetF
\\ T _SourceEditorDataSource.clone() T __T012SourceEditor0ab4DataA0C5cloneACyF
\\ T _SourceEditorDataSource.closePermanently() T __T012SourceEditor0ab4DataA0C16closePermanentlyyyF
\\ T _SourceEditorDataSource.nextEditableRangeFromPosition(_:endPosition:) T __T012SourceEditor0ab4DataA0C29nextEditableRangeFromPositionAA0abF0V_SbtSgAA0abH0V_AISg03endH0tF
\\ T _SourceEditorDataSource.validatePosition(_:) T __T012SourceEditor0ab4DataA0C16validatePositionyAA0abE0VF
\\ t _SourceEditorDataSource.verifyLineDataIntegrity() t __T012SourceEditor0ab4DataA0C010verifyLineC9Integrity33_76DCD73D096C2A8A62A7C1A15575EAAALLyyF
\\ T _SourceEditorDataSource.lineContentChangedForLineRange(_:) T __T012SourceEditor0ab4DataA0C30lineContentChangedForLineRangeys09CountableI0VySiGF
\\ T _SourceEditorDataSource.validateLineIndex(_:) T __T012SourceEditor0ab4DataA0C17validateLineIndexySiF
\\ T _SourceEditorDataSource.replaceContentsWithText(_:) T __T012SourceEditor0ab4DataA0C23replaceContentsWithTextySSF
\\ t _SourceEditorDataSource.notifyContentsChanged() t __T012SourceEditor0ab4DataA0C21notifyContentsChanged33_76DCD73D096C2A8A62A7C1A15575EAAALLyyF
\\ T _SourceEditorDataSource.trimmedLineContentForLine(_:) T __T012SourceEditor0ab4DataA0C021trimmedLineContentForE0SSSiF
\\ T _SourceEditorDataSource.lineContentForLineWithIdentifier(_:) T __T012SourceEditor0ab4DataA0C32lineContentForLineWithIdentifierSSSgAA0abgI0VF
\\ T _SourceEditorDataSource.contentRangeForLineRange(_:) T __T012SourceEditor0ab4DataA0C019contentRangeForLineE0AA0abE0Vs09CountableE0VySiGF
\\ T _SourceEditorDataSource.tokenAtPosition(_:) T __T012SourceEditor0ab4DataA0C15tokenAtPositionSS_AA0aB5RangeVAA13CodeTokenTypeOSgtSgAA0abF0VF
\\ T _SourceEditorDataSource.lineTerminatorLengthForLine(_:) T __T012SourceEditor0ab4DataA0C27lineTerminatorLengthForLineS2iF
\\ T _SourceEditorDataSource.leadingWhitespaceWidthForLineWithIdentifier(_:expandTabs:) T __T012SourceEditor0ab4DataA0C43leadingWhitespaceWidthForLineWithIdentifierSiAA0abhJ0V_Sb10expandTabstF
\\ T _SourceEditorDataSource.isBoundedByWhitespaceInRange(_:) T __T012SourceEditor0ab4DataA0C28isBoundedByWhitespaceInRangeSbAA0abI0VF
\\ T _SourceEditorDataSource.isLineHidden(_:) T __T012SourceEditor0ab4DataA0C12isLineHiddenSbSiF
\\ t _SourceEditorDataSource.precedingNonHiddenLineIndex(_:) t __T012SourceEditor0ab4DataA0C27precedingNonHiddenLineIndexSiSgSiF
\\ T _SourceEditorDataSource.nextNonHiddenLineIndex(_:) T __T012SourceEditor0ab4DataA0C22nextNonHiddenLineIndexSiSgSiF
\\ T _SourceEditorDataSource.injectedPlaceholderTextForPosition(_:) T __T012SourceEditor0ab4DataA0C34injectedPlaceholderTextForPositionSSSgAA0abH0VF
\\ T _SourceEditorDataSource.inlineEditableFieldsForLine(_:) T __T012SourceEditor0ab4DataA0C27inlineEditableFieldsForLineSaySC8_NSRangeV_AFS4StGSiF
\\ T _SourceEditorDataSource.positionFromPosition(_:offset:) T __T012SourceEditor0ab4DataA0C20positionFromPositionAA0abF0VSgAF_Si6offsettF
\\ t _SourceEditorDataSource.queueDataSourceContentsChanged(_:) t __T012SourceEditor0ab4DataA0C05queuecA15ContentsChanged33_76DCD73D096C2A8A62A7C1A15575EAAALLyAA0aB5RangeVSgF
\\ T _SourceEditorDataSource.evictLineLayerCache() T __T012SourceEditor0ab4DataA0C19evictLineLayerCacheyyF
\\ T _SourceEditorDataSource.documentResetContents() T __T012SourceEditor0ab4DataA0C21documentResetContentsyyF
\\ t _SourceEditorDataSource.removeLayoutContextFor(_:) t __T012SourceEditor0ab4DataA0C22removeLayoutContextForyAA0abE17ManagerIdentifierVF
\\ t _SourceEditorDataSource.detachSubstitutionViewForLine(_:layoutManagerIdentifier:relayout:) t __T012SourceEditor0ab4DataA0C29detachSubstitutionViewForLineySi_AA0aB23LayoutManagerIdentifierV06layoutjK0Sb8relayouttF
\\ t _SourceEditorDataSource.detachSubstitutionViewForLineWithIdentifier(_:layoutManagerIdentifier:relayout:) t __T012SourceEditor0ab4DataA0C43detachSubstitutionViewForLineWithIdentifieryAA0abhJ0V_AA0ab13LayoutManagerJ0V06layoutlJ0Sb8relayouttF
\\ t _SourceEditorDataSource.adjacentCodeEdgesForLine(_:layoutManagerIdentifier:) t __T012SourceEditor0ab4DataA0C24adjacentCodeEdgesForLineAA8RectEdgeVSi_AA0aB23LayoutManagerIdentifierV06layoutlM0tF
\\ t _SourceEditorDataSource.setAccessoryViewForLineWithIdentifier(_:layoutManagerIdentifier:view:relayout:) t __T012SourceEditor0ab4DataA0C37setAccessoryViewForLineWithIdentifieryAA0abhJ0V_AA0ab13LayoutManagerJ0V06layoutlJ0So6NSViewCSg4viewSb8relayouttF
\\ T _SourceEditorDataSource.lineContainsPlaceholders(_:) T __T012SourceEditor0ab4DataA0C24lineContainsPlaceholdersSbSiF
\\ T _SourceEditorDataSource.lastPlaceholderRangeInRange(_:) T __T012SourceEditor0ab4DataA0C022lastPlaceholderRangeInF0AA0abF0VSgAFF
\\ T _SourceEditorDataSource.nextPlaceholderRangeRelativeToPosition(_:) T __T012SourceEditor0ab4DataA0C38nextPlaceholderRangeRelativeToPositionAA0abF0VSgAA0abI0VF
\\ T _SourceEditorDataSource.previousPlaceholderRangeRelativeToPosition(_:) T __T012SourceEditor0ab4DataA0C42previousPlaceholderRangeRelativeToPositionAA0abF0VSgAA0abI0VF
\\ T _SourceEditorDataSource.diagnosticManager.didset T __T012SourceEditor0ab4DataA0C17diagnosticManagerAA0ab10DiagnosticE0CSgfW
\\ T _SourceEditorDataSource.diagnosticManager.getter T __T012SourceEditor0ab4DataA0C17diagnosticManagerAA0ab10DiagnosticE0CSgfg
\\ t _closure #1 in SourceEditorDataSource.diagnosticManager.materializeForSet t __T012SourceEditor0ab4DataA0C17diagnosticManagerAA0ab10DiagnosticE0CSgfmytfU_
\\ T _SourceEditorDataSource.diagnosticManager.materializeForSet T __T012SourceEditor0ab4DataA0C17diagnosticManagerAA0ab10DiagnosticE0CSgfm
\\ T _SourceEditorDataSource.placeholderInformationForLineWithIdentifier(_:) T __T012SourceEditor0ab4DataA0C43placeholderInformationForLineWithIdentifierSaySC8_NSRangeV_AA19PlaceholderMetadataOtGAA0abgI0VF
\\ T _SourceEditorDataSource.borderForEditableRange(_:layoutManager:) T __T012SourceEditor0ab4DataA0C22borderForEditableRangeSbAA0abG0V_AA0aB13LayoutManagerC06layoutI0tF
\\ t _closure #1 in variable initialization expression of static SourceEditorDataSource.shouldVerifyLineIntegrity t __T012SourceEditor0ab4DataA0C25shouldVerifyLineIntegrity33_76DCD73D096C2A8A62A7C1A15575EAAALLSbvZfiSbycfU_
\\ T _SourceEditorDataSource.description.getter T __T012SourceEditor0ab4DataA0C11descriptionSSfg
\\ T _SourceEditorDataSource.debugDescription.getter T __T012SourceEditor0ab4DataA0C16debugDescriptionSSfg
\\ T _SourceEditorDataSource.lineDataDescription.getter T __T012SourceEditor0ab4DataA0C04lineC11DescriptionSSfg
\\ T _SourceEditorDataSource.deinit T __T012SourceEditor0ab4DataA0Cfd
\\ T _SourceEditorDataSource.__deallocating_deinit T __T012SourceEditor0ab4DataA0CfD
\\ t _protocol witness for SourceEditorBuffer.string.getter in conformance SourceEditorDataSource t __T012SourceEditor0ab4DataA0CAA0aB6BufferA2aDP6stringSSfgTW
\\ t _protocol witness for SourceEditorBuffer.documentSettings.getter in conformance SourceEditorDataSource t __T012SourceEditor0ab4DataA0CAA0aB6BufferA2aDP16documentSettingsAA0ab8DocumentF0_pSgfgTW
\\ t _protocol witness for SourceEditorBuffer.textInRange(_:) in conformance SourceEditorDataSource t __T012SourceEditor0ab4DataA0CAA0aB6BufferA2aDP11textInRangeSSAA0abG0VFTW
\\ t _protocol witness for SourceEditorBuffer.positionFromInternalCharOffset(_:lineHint:) in conformance SourceEditorDataSource t __T012SourceEditor0ab4DataA0CAA0aB6BufferA2aDP30positionFromInternalCharOffsetAA0aB8PositionVSi_Si8lineHinttFTW
\\ t _protocol witness for SourceEditorBuffer.internalCharOffsetFromPosition(_:) in conformance SourceEditorDataSource t __T012SourceEditor0ab4DataA0CAA0aB6BufferA2aDP30internalCharOffsetFromPositionSiAA0abI0VFTW
\\ t _protocol witness for SourceEditorBuffer.positionForBeginningOfDocument() in conformance SourceEditorDataSource t __T012SourceEditor0ab4DataA0CAA0aB6BufferA2aDP30positionForBeginningOfDocumentAA0aB8PositionVyFTW
\\ t _protocol witness for SourceEditorBuffer.positionForEndOfDocument() in conformance SourceEditorDataSource t __T012SourceEditor0ab4DataA0CAA0aB6BufferA2aDP24positionForEndOfDocumentAA0aB8PositionVyFTW
\\ t _protocol witness for SourceEditorBuffer.nextCharacterPositionFromPosition(_:) in conformance SourceEditorDataSource t __T012SourceEditor0ab4DataA0CAA0aB6BufferA2aDP025nextCharacterPositionFromG0AA0abG0VSgAHFTW
\\ t _protocol witness for SourceEditorBuffer.previousCharacterPositionFromPosition(_:) in conformance SourceEditorDataSource t __T012SourceEditor0ab4DataA0CAA0aB6BufferA2aDP029previousCharacterPositionFromG0AA0abG0VSgAHFTW
\\ t _protocol witness for SourceEditorBuffer.lineContentLengthForLine(_:) in conformance SourceEditorDataSource t __T012SourceEditor0ab4DataA0CAA0aB6BufferA2aDP24lineContentLengthForLineS2iFTW
\\ t _protocol witness for SourceEditorBuffer.lineContentForLine(_:) in conformance SourceEditorDataSource t __T012SourceEditor0ab4DataA0CAA0aB6BufferA2aDP18lineContentForLineSSSiFTW
\\ t _protocol witness for SourceEditorBuffer.formattingOptions.getter in conformance SourceEditorDataSource t __T012SourceEditor0ab4DataA0CAA0aB6BufferA2aDP17formattingOptionsAA0ab10FormattingF0VfgTW
\\ t _protocol witness for SourceEditorBuffer.documentResetContents() in conformance SourceEditorDataSource t __T012SourceEditor0ab4DataA0CAA0aB6BufferA2aDP21documentResetContentsyyFTW
\\ t _protocol witness for SourceEditorBuffer.lineContentChangedForLineRange(_:) in conformance SourceEditorDataSource t __T012SourceEditor0ab4DataA0CAA0aB6BufferA2aDP30lineContentChangedForLineRangeys09CountableJ0VySiGFTW
\\ t _protocol witness for CustomStringConvertible.description.getter in conformance SourceEditorDataSource t __T012SourceEditor0ab4DataA0Cs23CustomStringConvertibleAAsADP11descriptionSSfgTW
\\ t _protocol witness for CustomDebugStringConvertible.debugDescription.getter in conformance SourceEditorDataSource t __T012SourceEditor0ab4DataA0Cs28CustomDebugStringConvertibleAAsADP16debugDescriptionSSfgTW
\\ T _SourceEditorDataSourceObserver.dataSourceDidInsertTextInRange(_:) T __T012SourceEditor0ab4DataA8ObserverPAAE04dataA20DidInsertTextInRangeyAA0abJ0VF
\\ T _SourceEditorDataSourceObserver.dataSourceDidDeleteTextInRange(_:) T __T012SourceEditor0ab4DataA8ObserverPAAE04dataA20DidDeleteTextInRangeyAA0abJ0VF
\\ T _SourceEditorDataSource.associatedLineData<A>() T __T012SourceEditor0ab4DataA0C014associatedLineC0AA013AnyAssociatedeC0VyxGyAA0abeC4TypeRzlF
\\ t _closure #1 in SourceEditorDataSource.associatedLineData<A>() t __T012SourceEditor0ab4DataA0C014associatedLineC0AA013AnyAssociatedeC0VyxGyAA0abeC4TypeRzlF0geC0QzAA0abeC0CcfU_
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceContentsChanged(_:) in conformance RenameController t __T012SourceEditor16RenameControllerCAA0ab4DataA8ObserverA2aDP04dataA15ContentsChangedyAA0aB5RangeVSgFTW
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceWillInsertTextInRange(_:) in conformance RenameController t __T012SourceEditor16RenameControllerCAA0ab4DataA8ObserverA2aDP04dataA21WillInsertTextInRangeyAA0abL0VFTW
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceWillDeleteTextInRange(_:) in conformance RenameController t __T012SourceEditor16RenameControllerCAA0ab4DataA8ObserverA2aDP04dataA21WillDeleteTextInRangeyAA0abL0VFTW
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceBeginEditTransaction() in conformance RenameController t __T012SourceEditor16RenameControllerCAA0ab4DataA8ObserverA2aDP04dataA20BeginEditTransactionyyFTW
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceEndEditTransaction() in conformance RenameController t __T012SourceEditor16RenameControllerCAA0ab4DataA8ObserverA2aDP04dataA18EndEditTransactionyyFTW
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceContentsChanged(_:) in conformance JournalDataSourceObserver t __T012SourceEditor011JournalDataA8Observer33_E53694DE114CF52172E44FB14EB48E6ALLCAA0abdaE0A2aEP04dataA15ContentsChangedyAA0aB5RangeVSgFTW
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceDidDeleteTextInRange(_:) in conformance JournalDataSourceObserver t __T012SourceEditor011JournalDataA8Observer33_E53694DE114CF52172E44FB14EB48E6ALLCAA0abdaE0A2aEP04dataA20DidDeleteTextInRangeyAA0abR0VFTW
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceDidDeleteLines(_:) in conformance JournalDataSourceObserver t __T012SourceEditor011JournalDataA8Observer33_E53694DE114CF52172E44FB14EB48E6ALLCAA0abdaE0A2aEP04dataA14DidDeleteLinesy10Foundation8IndexSetVFTW
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceBeginEditTransaction() in conformance JournalDataSourceObserver t __T012SourceEditor011JournalDataA8Observer33_E53694DE114CF52172E44FB14EB48E6ALLCAA0abdaE0A2aEP04dataA20BeginEditTransactionyyFTW
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceEndEditTransaction() in conformance JournalDataSourceObserver t __T012SourceEditor011JournalDataA8Observer33_E53694DE114CF52172E44FB14EB48E6ALLCAA0abdaE0A2aEP04dataA18EndEditTransactionyyFTW
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceWillInsertTextInRange(_:) in conformance LayoutManagerDataSourceObserver t __T012SourceEditor017LayoutManagerDataA8Observer33_8A34A44A3A81F5AC1210A0E6DECBF3ABLLCAA0abeaF0A2aEP04dataA21WillInsertTextInRangeyAA0abV0VFTW
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceWillDeleteTextInRange(_:) in conformance LayoutManagerDataSourceObserver t __T012SourceEditor017LayoutManagerDataA8Observer33_8A34A44A3A81F5AC1210A0E6DECBF3ABLLCAA0abeaF0A2aEP04dataA21WillDeleteTextInRangeyAA0abV0VFTW
\\ t _specialized SourceEditorDataSource.removeObserver(observer:) t __T012SourceEditor0ab4DataA0C14removeObserveryAA0abcaE0_p8observer_tFTf4gn_n
\\ t _specialized closure #1 in SourceEditorDataSource.removeLayoutContextFor(_:) t __T012SourceEditor0ab4DataA0C22removeLayoutContextForyAA0abE17ManagerIdentifierVFyAA0ab4LineC0CcfU_Tf4gn_n
\\ t _specialized SourceEditorDataSource.internalCharOffsetFromPosition(_:) t __T012SourceEditor0ab4DataA0C30internalCharOffsetFromPositionSiAA0abH0VFTf4xn_n
\\ t _specialized SourceEditorDataSource.nextCharacterPositionFromPosition(_:) t __T012SourceEditor0ab4DataA0C025nextCharacterPositionFromF0AA0abF0VSgAFFTf4xn_n
\\ t _specialized SourceEditorDataSource.nextEditableRangeFromPosition(_:endPosition:) t __T012SourceEditor0ab4DataA0C29nextEditableRangeFromPositionAA0abF0V_SbtSgAA0abH0V_AISg03endH0tFTf4xnn_n
\\ t _specialized SourceEditorDataSource.borderForEditableRange(_:layoutManager:) t __T012SourceEditor0ab4DataA0C22borderForEditableRangeSbAA0abG0V_AA0aB13LayoutManagerC06layoutI0tFTf4ngn_n
\\ t _specialized SourceEditorDataSource.addObserver(observer:) t __T012SourceEditor0ab4DataA0C11addObserveryAA0abcaE0_p8observer_tFTf4gn_n
\\ t _specialized SourceEditorDataSource.lineIsOnEditableRangeEdge(_:layoutManager:) t __T012SourceEditor0ab4DataA0C25lineIsOnEditableRangeEdgeSbSi_AA0aB13LayoutManagerC06layoutK0tFTf4ngn_n
\\ t _specialized SourceEditorDataSource.balancedCountForOpenDelimiter(_:closeDelimiter:) t __T012SourceEditor0ab4DataA0C29balancedCountForOpenDelimiterSis9CharacterV_AF05closeH0tFTf4ggn_n
\\ t _specialized SourceEditorDataSource.findMatchingDelimiterFromInternalCharOffset(_:delimiter:searchRange:) t __T012SourceEditor0ab4DataA0C43findMatchingDelimiterFromInternalCharOffset33_76DCD73D096C2A8A62A7C1A15575EAAALLSiSgSi_So8NSStringC9delimiterSC8_NSRangeV11searchRangetFTf4ngnn_n
\\ t _specialized SourceEditorDataSource.findMatchingDelimiterFromPosition(_:constrainedTo:) t __T012SourceEditor0ab4DataA0C33findMatchingDelimiterFromPositionAA0abH0VSgAF_AA0aB5RangeVSg13constrainedTotFTf4xnn_n
\\ t _specialized SourceEditorDataSource.characterRangeAtPosition(_:) t __T012SourceEditor0ab4DataA0C24characterRangeAtPositionAA0abE0VAA0abG0VFTf4xn_n
\\ t _specialized SourceEditorDataSource.lineRangeForSubstitutionView(_:layoutManagerIdentifier:hint:) t __T012SourceEditor0ab4DataA0C28lineRangeForSubstitutionViews09CountableE0VySiGSgSo6NSViewC_AA0aB23LayoutManagerIdentifierV06layoutlM0SiSg4hinttFTf4gnnn_n
\\ t _specialized SourceEditorDataSource.updateEditedRangeWithDeletedTextInRange(_:) t __T012SourceEditor0ab4DataA0C034updateEditedRangeWithDeletedTextInF033_76DCD73D096C2A8A62A7C1A15575EAAALLys09CountableF0VySiGFTf4xn_n
\\ t _specialized SourceEditorDataSource.auxViewsForLineWithIdentifier(_:layoutManagerIdentifier:withAuxViewIdentifier:) t __T012SourceEditor0ab4DataA0C29auxViewsForLineWithIdentifierSayAA0aB13AuxiliaryViewVGAA0abgI0V_AA0ab13LayoutManagerI0V06layoutmI0SSSg07withAuxkI0tFTf4nnnd_n
\\ t _specialized SourceEditorDataSource.updateEditedRangeWithInsertedTextInRange(_:) t __T012SourceEditor0ab4DataA0C035updateEditedRangeWithInsertedTextInF033_76DCD73D096C2A8A62A7C1A15575EAAALLys09CountableF0VySiGFTf4xn_n
\\ t _specialized SourceEditorDataSource.insertTextAtPosition(_:position:) t __T012SourceEditor0ab4DataA0C20insertTextAtPositionAA0abG0VSS_AF8positiontFTf4gXxn_n
\\ t _specialized SourceEditorDataSource.leadingWhitespaceWidthForInternalRange(range:expandTabs:) t __T012SourceEditor0ab4DataA0C38leadingWhitespaceWidthForInternalRange33_76DCD73D096C2A8A62A7C1A15575EAAALLSiSC8_NSRangeV5range_Sb10expandTabstFTf4xnn_n
\\ T _type metadata accessor for SourceEditorDataSource T __T012SourceEditor0ab4DataA0CMa
\\ t _specialized SourceEditorDataSource.init(usingMutableString:language:) t __T012SourceEditor0ab4DataA0CACSo15NSMutableStringC012usingMutableE0_AA0aB8Language_pSg8languagetcfcTf4gnn_n
\\ t _specialized SourceEditorDataSource.diagnosticManager.setter t __T012SourceEditor0ab4DataA0C17diagnosticManagerAA0ab10DiagnosticE0CSgfsTf4gn_n
\\ t _specialized SourceEditorDataSource.tokenAtPosition(_:) t __T012SourceEditor0ab4DataA0C15tokenAtPositionSS_AA0aB5RangeVAA13CodeTokenTypeOSgtSgAA0abF0VFTf4xn_n
\\ t _specialized SourceEditorDataSource.attachAuxViewForLineWithIdentifier(_:layoutManagerIdentifier:withAuxViewIdentifier:view:position:alignment:padding:fullBleed:relayout:) t __T012SourceEditor0ab4DataA0C34attachAuxViewForLineWithIdentifieryAA0abhJ0V_AA0ab13LayoutManagerJ0V06layoutlJ0SSSg04withefJ0So6NSViewC4viewAA0ab9AuxiliaryF0V8PositionOSg8positionAP9AlignmentOSg9alignmentSC6CGSizeV7paddingSb9fullBleedSb8relayouttFTf4nnggnnnnnn_n
\\ t _specialized SourceEditorDataSource.placeholderRangeAtPosition(_:) t __T012SourceEditor0ab4DataA0C26placeholderRangeAtPositionAA0abE0VSgAA0abG0VFTf4xn_n
\\ t _partial apply for closure #2 in SourceEditorDataSource.deleteTextInRange(_:) t __T012SourceEditor0ab4DataA0C17deleteTextInRangeAA0aB8PositionVAA0abG0VFySSSg_SC8_NSRangeVAKSpy10ObjectiveC8ObjCBoolVGtcfU0_TA
\\ t _specialized SourceEditorDataSource.attachSubstitutionViewForLines(_:layoutManagerIdentifier:view:fullBleed:requiresSeparatorsForEdges:relayout:) t __T012SourceEditor0ab4DataA0C30attachSubstitutionViewForLinesys14CountableRangeVySiG_AA0aB23LayoutManagerIdentifierV06layoutlM0So6NSViewC4viewSb9fullBleedAA8RectEdgeV018requiresSeparatorsG5EdgesSb8relayouttFTf4xngnnnn_n
\\ t _specialized SourceEditorDataSource.updateSubstitutionViewRangeForLine(_:newRange:layoutManagerIdentifier:relayout:) t __T012SourceEditor0ab4DataA0C34updateSubstitutionViewRangeForLineySi_s09CountableG0VySiG03newG0AA0aB23LayoutManagerIdentifierV06layoutmN0Sb8relayouttFTf4nxnnn_n
\\ t _specialized SourceEditorDataSource.string.setter t __T012SourceEditor0ab4DataA0C6stringSSfsTf4gXn_n
\\ t _specialized SourceEditorDataSource.init(name:language:usingMutableString:) t __T012SourceEditor0ab4DataA0CACSS4name_AA0aB8Language_p8languageSo15NSMutableStringC012usingMutableH0tcfcTf4gXngn_n
\\ t _specialized SourceEditorDataSource.init(languageService:language:usingMutableString:name:) t __T012SourceEditor0ab4DataA0CAcA0aB15LanguageService_p08languageE0_AA0abD0_p0F0So15NSMutableStringC012usingMutableH0SSSg4nametcfcTf4gnggn_n
\\ t _partial apply for closure #1 in static SourceEditorDataSource.dataSourceWithGeneratedContent(for:using:completion:) t __T012SourceEditor0ab4DataA0C04dataA20WithGeneratedContentAA015LanguageServiceG21GenerationCoordinatorCSgAA0aB16DocumentSettings_p3for_AA0abH0_p5usingyAC0gJ6ResultOc10completiontFZyAaLOcfU_TA
\\ t _specialized closure #1 in static SourceEditorDataSource.dataSourceWithGeneratedContent(for:using:completion:) t __T012SourceEditor0ab4DataA0C04dataA20WithGeneratedContentAA015LanguageServiceG21GenerationCoordinatorCSgAA0aB16DocumentSettings_p3for_AA0abH0_p5usingyAC0gJ6ResultOc10completiontFZyAaLOcfU_Tf4ggggg_n
\\ t _specialized closure #2 in SourceEditorDataSource.insertTextAtPosition(_:position:) t __T012SourceEditor0ab4DataA0C20insertTextAtPositionAA0abG0VSS_AF8positiontFySSSg_SC8_NSRangeVAJSpy10ObjectiveC8ObjCBoolVGtcfU0_Tf4gxxdggg_n
\\ t _specialized SourceEditorDataSource.lineContentChangedForLineRange(_:) t __T012SourceEditor0ab4DataA0C30lineContentChangedForLineRangeys09CountableI0VySiGFTf4xn_n
\\ t _partial apply for closure #1 in SourceEditorDataSource.associatedLineData<A>() t __T012SourceEditor0ab4DataA0C014associatedLineC0AA013AnyAssociatedeC0VyxGyAA0abeC4TypeRzlF0geC0QzAA0abeC0CcfU_TA
\\ T _protocol witness table accessor for SourceEditorDataSource T __T012SourceEditor0ab4DataA0CAA0aB6BufferAAWa
\\ T _protocol witness table accessor for SourceEditorDataSource T __T012SourceEditor0ab4DataA0Cs23CustomStringConvertibleAAWa
\\ T _protocol witness table accessor for SourceEditorDataSource T __T012SourceEditor0ab4DataA0Cs28CustomDebugStringConvertibleAAWa
\\ t _destroyBuffer for SourceEditorDataSource.ContentGenerationResult t __T012SourceEditor0ab4DataA0C23ContentGenerationResultOwXX
\\ t _initializeBufferWithCopyOfBuffer for SourceEditorDataSource.ContentGenerationResult t __T012SourceEditor0ab4DataA0C23ContentGenerationResultOwCP
\\ t _destroy for SourceEditorDataSource.ContentGenerationResult t __T012SourceEditor0ab4DataA0C23ContentGenerationResultOwxx
\\ t _initializeBufferWithCopy for SourceEditorDataSource.ContentGenerationResult t __T012SourceEditor0ab4DataA0C23ContentGenerationResultOwCp
\\ t _initializeWithCopy for SourceEditorDataSource.ContentGenerationResult t __T012SourceEditor0ab4DataA0C23ContentGenerationResultOwcp
\\ t _assignWithCopy for SourceEditorDataSource.ContentGenerationResult t __T012SourceEditor0ab4DataA0C23ContentGenerationResultOwca
\\ t _assignWithTake for SourceEditorDataSource.ContentGenerationResult t __T012SourceEditor0ab4DataA0C23ContentGenerationResultOwta
\\ t _destroyArray for SourceEditorDataSource.ContentGenerationResult t __T012SourceEditor0ab4DataA0C23ContentGenerationResultOwXx
\\ t _initializeArrayWithCopy for SourceEditorDataSource.ContentGenerationResult t __T012SourceEditor0ab4DataA0C23ContentGenerationResultOwCc
\\ t _getEnumTag for SourceEditorDataSource.ContentGenerationResult t __T012SourceEditor0ab4DataA0C23ContentGenerationResultOwug
\\ t _destructiveProjectEnumData for SourceEditorDataSource.ContentGenerationResult t __T012SourceEditor0ab4DataA0C23ContentGenerationResultOwup
\\ t _destructiveInjectEnumTag for SourceEditorDataSource.ContentGenerationResult t __T012SourceEditor0ab4DataA0C23ContentGenerationResultOwui
\\ T _type metadata accessor for SourceEditorDataSource.ContentGenerationResult T __T012SourceEditor0ab4DataA0C23ContentGenerationResultOMa
\\ t _specialized closure #2 in SourceEditorDataSource.deleteTextInRange(_:) t __T012SourceEditor0ab4DataA0C17deleteTextInRangeAA0aB8PositionVAA0abG0VFySSSg_SC8_NSRangeVAKSpy10ObjectiveC8ObjCBoolVGtcfU0_Tf4dxxdgng_n
\\ t _specialized SourceEditorDataSource.detachAuxViewsForLineWithIdentifier(_:layoutManagerIdentifier:withAuxViewIdentifier:relayout:) t __T012SourceEditor0ab4DataA0C35detachAuxViewsForLineWithIdentifieryAA0abhJ0V_AA0ab13LayoutManagerJ0V06layoutlJ0SSSg04withe4ViewJ0Sb8relayouttFTf4nngnn_n
\\ t _partial apply for closure #2 in SourceEditorDataSource.insertTextAtPosition(_:position:) t __T012SourceEditor0ab4DataA0C20insertTextAtPositionAA0abG0VSS_AF8positiontFySSSg_SC8_NSRangeVAJSpy10ObjectiveC8ObjCBoolVGtcfU0_TA
\\ t _destroyBuffer for SourceEditorDataSourceObserverToken t __T012SourceEditor0ab4DataA13ObserverToken33_76DCD73D096C2A8A62A7C1A15575EAAALLVwXX
\\ t _initializeBufferWithCopyOfBuffer for SourceEditorDataSourceObserverToken t __T012SourceEditor0ab4DataA13ObserverToken33_76DCD73D096C2A8A62A7C1A15575EAAALLVwCP
\\ t _projectBuffer for SourceEditorDataSourceObserverToken t __T012SourceEditor0ab4DataA13ObserverToken33_76DCD73D096C2A8A62A7C1A15575EAAALLVwpr
\\ t _deallocateBuffer for SourceEditorDataSourceObserverToken t __T012SourceEditor0ab4DataA13ObserverToken33_76DCD73D096C2A8A62A7C1A15575EAAALLVwde
\\ t _destroy for SourceEditorDataSourceObserverToken t __T012SourceEditor0ab4DataA13ObserverToken33_76DCD73D096C2A8A62A7C1A15575EAAALLVwxx
\\ t _initializeBufferWithCopy for SourceEditorDataSourceObserverToken t __T012SourceEditor0ab4DataA13ObserverToken33_76DCD73D096C2A8A62A7C1A15575EAAALLVwCp
\\ t _initializeWithCopy for SourceEditorDataSourceObserverToken t __T012SourceEditor0ab4DataA13ObserverToken33_76DCD73D096C2A8A62A7C1A15575EAAALLVwcp
\\ t _assignWithCopy for SourceEditorDataSourceObserverToken t __T012SourceEditor0ab4DataA13ObserverToken33_76DCD73D096C2A8A62A7C1A15575EAAALLVwca
\\ t _initializeBufferWithTake for SourceEditorDataSourceObserverToken t __T012SourceEditor0ab4DataA13ObserverToken33_76DCD73D096C2A8A62A7C1A15575EAAALLVwTk
\\ t _initializeBufferWithCopy for SourceEditorDataSourceObserverToken t __T012SourceEditor0ab4DataA13ObserverToken33_76DCD73D096C2A8A62A7C1A15575EAAALLVwCpTm
\\ t _initializeWithTake for SourceEditorDataSourceObserverToken t __T012SourceEditor0ab4DataA13ObserverToken33_76DCD73D096C2A8A62A7C1A15575EAAALLVwtk
\\ t _assignWithTake for SourceEditorDataSourceObserverToken t __T012SourceEditor0ab4DataA13ObserverToken33_76DCD73D096C2A8A62A7C1A15575EAAALLVwta
\\ t _allocateBuffer for SourceEditorDataSourceObserverToken t __T012SourceEditor0ab4DataA13ObserverToken33_76DCD73D096C2A8A62A7C1A15575EAAALLVwal
\\ t _destroyArray for SourceEditorDataSourceObserverToken t __T012SourceEditor0ab4DataA13ObserverToken33_76DCD73D096C2A8A62A7C1A15575EAAALLVwXx
\\ t _initializeArrayWithCopy for SourceEditorDataSourceObserverToken t __T012SourceEditor0ab4DataA13ObserverToken33_76DCD73D096C2A8A62A7C1A15575EAAALLVwCc
\\ t _initializeArrayWithTakeFrontToBack for SourceEditorDataSourceObserverToken t __T012SourceEditor0ab4DataA13ObserverToken33_76DCD73D096C2A8A62A7C1A15575EAAALLVwTt
\\ t _initializeArrayWithCopy for SourceEditorDataSourceObserverToken t __T012SourceEditor0ab4DataA13ObserverToken33_76DCD73D096C2A8A62A7C1A15575EAAALLVwCcTm
\\ t _initializeArrayWithTakeBackToFront for SourceEditorDataSourceObserverToken t __T012SourceEditor0ab4DataA13ObserverToken33_76DCD73D096C2A8A62A7C1A15575EAAALLVwtT
\\ t _storeExtraInhabitant for SourceEditorDataSourceObserverToken t __T012SourceEditor0ab4DataA13ObserverToken33_76DCD73D096C2A8A62A7C1A15575EAAALLVwxs
\\ t _getExtraInhabitantIndex for SourceEditorDataSourceObserverToken t __T012SourceEditor0ab4DataA13ObserverToken33_76DCD73D096C2A8A62A7C1A15575EAAALLVwxg
\\ t _type metadata accessor for SourceEditorDataSourceObserverToken t __T012SourceEditor0ab4DataA13ObserverToken33_76DCD73D096C2A8A62A7C1A15575EAAALLVMa
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceDidInsertLines(_:) in conformance FoldingController t __T012SourceEditor17FoldingControllerCAA0ab4DataA8ObserverA2aDP04dataA14DidInsertLinesy10Foundation8IndexSetVFTW
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceDidDeleteLines(_:) in conformance FoldingController t __T012SourceEditor17FoldingControllerCAA0ab4DataA8ObserverA2aDP04dataA14DidDeleteLinesy10Foundation8IndexSetVFTW
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceDidInsertLines(_:) in conformance RenameController t __T012SourceEditor16RenameControllerCAA0ab4DataA8ObserverA2aDP04dataA14DidInsertLinesy10Foundation8IndexSetVFTW
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceDidDeleteLines(_:) in conformance RenameController t __T012SourceEditor16RenameControllerCAA0ab4DataA8ObserverA2aDP04dataA14DidDeleteLinesy10Foundation8IndexSetVFTW
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceDidInsertLines(_:) in conformance JournalDataSourceObserver t __T012SourceEditor011JournalDataA8Observer33_E53694DE114CF52172E44FB14EB48E6ALLCAA0abdaE0A2aEP04dataA14DidInsertLinesy10Foundation8IndexSetVFTW
\\ T _SourceEditorDataSourceObserver.dataSourceDidInsertLines(_:) T __T012SourceEditor0ab4DataA8ObserverPAAE04dataA14DidInsertLinesy10Foundation8IndexSetVF
\\ T _SourceEditorDataSource.findResultFor(query:) T __T012SourceEditor0ab4DataA0C13findResultForAA08TextFindE0_pSgAA0gH5QueryV5query_tF
\\ T _SourceEditorDataSource.rangesMatching(regularExpression:) T __T012SourceEditor0ab4DataA0C14rangesMatchingSayAA0aB5RangeV_So20NSTextCheckingResultCtGSo19NSRegularExpressionC07regularK0_tF
\\ T _SourceEditorDataSource.rangesMatching(string:options:) T __T012SourceEditor0ab4DataA0C14rangesMatchingSayAA0aB5RangeVGSS6string_So8NSStringC14CompareOptionsV7optionstF
\\ t _protocol witness for TextFindableDataSource.findResultFor(query:) in conformance SourceEditorDataSource t __T012SourceEditor0ab4DataA0CAA012TextFindablecA0A2aDP13findResultForAA0d4FindG0_pSgAA0dI5QueryV5query_tFTW
\\ t _protocol witness for TextFindableDataSource.rangesMatching(string:options:) in conformance SourceEditorDataSource t __T012SourceEditor0ab4DataA0CAA012TextFindablecA0A2aDP14rangesMatchingSayAA0aB5RangeVGSS6string_So8NSStringC14CompareOptionsV7optionstFTW
\\ t _protocol witness for TextFindableDataSource.rangesMatching(regularExpression:) in conformance SourceEditorDataSource t __T012SourceEditor0ab4DataA0CAA012TextFindablecA0A2aDP14rangesMatchingSayAA0aB5RangeV_So20NSTextCheckingResultCtGSo19NSRegularExpressionC07regularM0_tFTW
\\ t _specialized SourceEditorDataSource.rangesMatching(regularExpression:) t __T012SourceEditor0ab4DataA0C14rangesMatchingSayAA0aB5RangeV_So20NSTextCheckingResultCtGSo19NSRegularExpressionC07regularK0_tFTf4gn_n
\\ t _specialized SourceEditorDataSource.rangesMatching(string:options:) t __T012SourceEditor0ab4DataA0C14rangesMatchingSayAA0aB5RangeVGSS6string_So8NSStringC14CompareOptionsV7optionstFTf4gXnn_n
\\ T _protocol witness table accessor for SourceEditorDataSource T __T012SourceEditor0ab4DataA0CAA012TextFindablecA0AAWa
\\ t _partial apply for SourceEditorDataSource.lineIndexForLineWithIdentifier(_:) t __T012SourceEditor0ab4DataA0C30lineIndexForLineWithIdentifierSiSgAA0abgI0VFTA
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceDidInsertTextInRange(_:) in conformance RenameController t __T012SourceEditor16RenameControllerCAA0ab4DataA8ObserverA2aDP04dataA20DidInsertTextInRangeyAA0abL0VFTW
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceDidDeleteTextInRange(_:) in conformance RenameController t __T012SourceEditor16RenameControllerCAA0ab4DataA8ObserverA2aDP04dataA20DidDeleteTextInRangeyAA0abL0VFTW
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceWillInsertTextInRange(_:) in conformance JournalDataSourceObserver t __T012SourceEditor011JournalDataA8Observer33_E53694DE114CF52172E44FB14EB48E6ALLCAA0abdaE0A2aEP04dataA21WillInsertTextInRangeyAA0abR0VFTW
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceDidInsertTextInRange(_:) in conformance JournalDataSourceObserver t __T012SourceEditor011JournalDataA8Observer33_E53694DE114CF52172E44FB14EB48E6ALLCAA0abdaE0A2aEP04dataA20DidInsertTextInRangeyAA0abR0VFTW
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceWillDeleteTextInRange(_:) in conformance JournalDataSourceObserver t __T012SourceEditor011JournalDataA8Observer33_E53694DE114CF52172E44FB14EB48E6ALLCAA0abdaE0A2aEP04dataA21WillDeleteTextInRangeyAA0abR0VFTW
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceContentsChanged(_:) in conformance LayoutManagerDataSourceObserver t __T012SourceEditor017LayoutManagerDataA8Observer33_8A34A44A3A81F5AC1210A0E6DECBF3ABLLCAA0abeaF0A2aEP04dataA15ContentsChangedyAA0aB5RangeVSgFTW
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceDidInsertTextInRange(_:) in conformance LayoutManagerDataSourceObserver t __T012SourceEditor017LayoutManagerDataA8Observer33_8A34A44A3A81F5AC1210A0E6DECBF3ABLLCAA0abeaF0A2aEP04dataA20DidInsertTextInRangeyAA0abV0VFTW
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceDidDeleteTextInRange(_:) in conformance LayoutManagerDataSourceObserver t __T012SourceEditor017LayoutManagerDataA8Observer33_8A34A44A3A81F5AC1210A0E6DECBF3ABLLCAA0abeaF0A2aEP04dataA20DidDeleteTextInRangeyAA0abV0VFTW
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceDidInsertLines(_:) in conformance LayoutManagerDataSourceObserver t __T012SourceEditor017LayoutManagerDataA8Observer33_8A34A44A3A81F5AC1210A0E6DECBF3ABLLCAA0abeaF0A2aEP04dataA14DidInsertLinesy10Foundation8IndexSetVFTW
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceDidDeleteLines(_:) in conformance LayoutManagerDataSourceObserver t __T012SourceEditor017LayoutManagerDataA8Observer33_8A34A44A3A81F5AC1210A0E6DECBF3ABLLCAA0abeaF0A2aEP04dataA14DidDeleteLinesy10Foundation8IndexSetVFTW
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceBeginEditTransaction() in conformance LayoutManagerDataSourceObserver t __T012SourceEditor017LayoutManagerDataA8Observer33_8A34A44A3A81F5AC1210A0E6DECBF3ABLLCAA0abeaF0A2aEP04dataA20BeginEditTransactionyyFTW
\\ t _protocol witness for SourceEditorDataSourceObserver.dataSourceEndEditTransaction() in conformance LayoutManagerDataSourceObserver t __T012SourceEditor017LayoutManagerDataA8Observer33_8A34A44A3A81F5AC1210A0E6DECBF3ABLLCAA0abeaF0A2aEP04dataA18EndEditTransactionyyFTW
\\ s _direct field offset for SourceEditorDataSource.lineData s __T012SourceEditor0ab4DataA0C04lineC033_76DCD73D096C2A8A62A7C1A15575EAAALLSayAA0ab4LineC0CGvWvd
\\ s _direct field offset for SourceEditorDataSource.contents s __T012SourceEditor0ab4DataA0C8contents33_76DCD73D096C2A8A62A7C1A15575EAAALLSo15NSMutableStringCvWvd
\\ s _direct field offset for SourceEditorDataSource.transactionNesting s __T012SourceEditor0ab4DataA0C18transactionNesting33_76DCD73D096C2A8A62A7C1A15575EAAALLSivWvd
\\ s _direct field offset for SourceEditorDataSource.editedRange s __T012SourceEditor0ab4DataA0C11editedRange33_76DCD73D096C2A8A62A7C1A15575EAAALLs09CountableE0VySiGSgvWvd
\\ S _direct field offset for SourceEditorDataSource.name S __T012SourceEditor0ab4DataA0C4nameSSSgvWvd
\\ S _direct field offset for SourceEditorDataSource.lockedDocument S __T012SourceEditor0ab4DataA0C14lockedDocumentSbvWvd
\\ S _direct field offset for SourceEditorDataSource.language S __T012SourceEditor0ab4DataA0C8languageAA0aB8Language_pSgvWvd
\\ s _direct field offset for SourceEditorDataSource.languageService.storage s __T012SourceEditor0ab4DataA0C0028languageServicestorage_GxAFh33_76DCD73D096C2A8A62A7C1A15575EAAALLAA0aB15LanguageService_pSgvWvd
\\ S _direct field offset for SourceEditorDataSource.formattingOptions S __T012SourceEditor0ab4DataA0C17formattingOptionsAA0ab10FormattingE0VvWvd
\\ s _direct field offset for SourceEditorDataSource.observerTokens s __T012SourceEditor0ab4DataA0C14observerTokens33_76DCD73D096C2A8A62A7C1A15575EAAALLSayAA0abcA13ObserverTokenAELLVGvWvd
\\ S _direct field offset for SourceEditorDataSource.documentSettings S __T012SourceEditor0ab4DataA0C16documentSettingsAA0ab8DocumentE0_pSgvWvd
\\ S _direct field offset for SourceEditorDataSource.delegate S __T012SourceEditor0ab4DataA0C8delegateAA0abcA8Delegate_pSgXwvWvd
\\ s _direct field offset for SourceEditorDataSource.undoManager.storage s __T012SourceEditor0ab4DataA0C0024undoManagerstorage_wnAHf33_76DCD73D096C2A8A62A7C1A15575EAAALLAA0aB11UndoManagerCSgvWvd
\\ s _direct field offset for SourceEditorDataSource.diagnosticProviderToken s __T012SourceEditor0ab4DataA0C23diagnosticProviderToken33_76DCD73D096C2A8A62A7C1A15575EAAALLAA0ab10DiagnosticeF0VSgvWvd
\\ S _direct field offset for SourceEditorDataSource.diagnosticManager S __T012SourceEditor0ab4DataA0C17diagnosticManagerAA0ab10DiagnosticE0CSgvWvd
\\ S _nominal type descriptor for SourceEditorDataSource S __T012SourceEditor0ab4DataA0CMn
\\ S _nominal type descriptor for SourceEditorDataSource.ContentGenerationResult S __T012SourceEditor0ab4DataA0C23ContentGenerationResultOMn
\\ s _nominal type descriptor for SourceEditorDataSourceObserverToken s __T012SourceEditor0ab4DataA13ObserverToken33_76DCD73D096C2A8A62A7C1A15575EAAALLVMn
\\ s _reflection metadata field descriptor SourceEditorDataSourceDelegate s __T012SourceEditor0ab4DataA8Delegate_pMF
\\ s _reflection metadata field descriptor SourceEditorDataSource.ContentGenerationResult s __T012SourceEditor0ab4DataA0C23ContentGenerationResultOMF
\\ s _reflection metadata field descriptor SourceEditorDataSource s __T012SourceEditor0ab4DataA0CMF
\\ s _reflection metadata field descriptor SourceEditorDataSourceObserver s __T012SourceEditor0ab4DataA8Observer_pMF
\\ s _reflection metadata field descriptor SourceEditorDataSourceObserverToken s __T012SourceEditor0ab4DataA13ObserverToken33_76DCD73D096C2A8A62A7C1A15575EAAALLVMF
\\ s _reflection metadata builtin descriptor SourceEditorDataSource.ContentGenerationResult s __T012SourceEditor0ab4DataA0C23ContentGenerationResultOMB
\\ S _protocol witness table for SourceEditorDataSource S __T012SourceEditor0ab4DataA0CAA29CodeCompletionOptionsProviderAAWP
\\ S _protocol witness table for SourceEditorDataSource S __T012SourceEditor0ab4DataA0CAA0aB6BufferAAWP
\\ S _protocol witness table for SourceEditorDataSource S __T012SourceEditor0ab4DataA0Cs23CustomStringConvertibleAAWP
\\ S _protocol witness table for SourceEditorDataSource S __T012SourceEditor0ab4DataA0Cs28CustomDebugStringConvertibleAAWP
\\ S _protocol descriptor for SourceEditorDataSourceDelegate S __T012SourceEditor0ab4DataA8DelegateMp
\\ S _protocol descriptor for SourceEditorDataSourceObserver S __T012SourceEditor0ab4DataA8ObserverMp
\\ S _protocol witness table for SourceEditorDataSource S __T012SourceEditor0ab4DataA0CAA012TextFindablecA0AAWP
\\ d _lazy cache variable for type metadata for SourceEditorDataSourceObserver.Type d __T012SourceEditor0ab4DataA8Observer_pXpML
\\ d _lazy cache variable for type metadata for SourceEditorDataSourceObserver d __T012SourceEditor0ab4DataA8Observer_pML
\\ d _lazy cache variable for type metadata for SourceEditorDataSource? d __T012SourceEditor0ab4DataA0CSgML
\\ d _lazy cache variable for type metadata for _ContiguousArrayStorage<SourceEditorDataSourceObserverToken> d __T0s23_ContiguousArrayStorageCy12SourceEditor0de4DataD13ObserverToken33_76DCD73D096C2A8A62A7C1A15575EAAALLVGML
\\ D _metaclass for SourceEditorDataSource D __T012SourceEditor0ab4DataA0CMm
\\ d _lazy cache variable for type metadata for SourceEditorDataSource d __T012SourceEditor0ab4DataA0CML
\\ d _full type metadata for SourceEditorDataSource d __T012SourceEditor0ab4DataA0CMf
\\ D _type metadata for SourceEditorDataSource D __T012SourceEditor0ab4DataA0CN
\\ d _value witness table for SourceEditorDataSource.ContentGenerationResult d __T012SourceEditor0ab4DataA0C23ContentGenerationResultOWV
\\ d _lazy cache variable for type metadata for SourceEditorDataSource.ContentGenerationResult d __T012SourceEditor0ab4DataA0C23ContentGenerationResultOML
\\ d _full type metadata for SourceEditorDataSource.ContentGenerationResult d __T012SourceEditor0ab4DataA0C23ContentGenerationResultOMf
\\ D _type metadata for SourceEditorDataSource.ContentGenerationResult D __T012SourceEditor0ab4DataA0C23ContentGenerationResultON
\\ d _lazy cache variable for type metadata for [SourceEditorDataSourceObserverToken] d __T0Say12SourceEditor0ab4DataA13ObserverToken33_76DCD73D096C2A8A62A7C1A15575EAAALLVGML
\\ d _lazy cache variable for type metadata for SourceEditorDataSourceDelegate? d __T012SourceEditor0ab4DataA8Delegate_pSgML
\\ d _lazy cache variable for type metadata for SourceEditorDataSourceDelegate d __T012SourceEditor0ab4DataA8Delegate_pML
\\ d _lazy cache variable for type metadata for SourceEditorDataSourceObserver? d __T012SourceEditor0ab4DataA8Observer_pSgML
\\ d _lazy cache variable for type metadata for _ContiguousArrayStorage<SourceEditorDataSourceObserver?> d __T0s23_ContiguousArrayStorageCy12SourceEditor0de4DataD8Observer_pSgGML
\\ d _value witness table for SourceEditorDataSourceObserverToken d __T012SourceEditor0ab4DataA13ObserverToken33_76DCD73D096C2A8A62A7C1A15575EAAALLVWV
\\ d _full type metadata for SourceEditorDataSourceObserverToken d __T012SourceEditor0ab4DataA13ObserverToken33_76DCD73D096C2A8A62A7C1A15575EAAALLVMf
\\ d _type metadata for SourceEditorDataSourceObserverToken d __T012SourceEditor0ab4DataA13ObserverToken33_76DCD73D096C2A8A62A7C1A15575EAAALLVN
\\ s _SourceEditorDataSourceDebugIntegrity s __T012SourceEditor0ab4DataA14DebugIntegrity33_76DCD73D096C2A8A62A7C1A15575EAAALLSSv
\\ S _static NSNotification.Name.SourceEditorDataSourceWillChange S __T0So14NSNotificationC4NameV12SourceEditorE0cd4DataC10WillChangeADvZ
\\ S _static NSNotification.Name.SourceEditorDataSourceChanged S __T0So14NSNotificationC4NameV12SourceEditorE0cd4DataC7ChangedADvZ
\\ S _static NSNotification.Name.SourceEditorDataSourceDidInsertText S __T0So14NSNotificationC4NameV12SourceEditorE0cd4DataC13DidInsertTextADvZ
\\ S _static NSNotification.Name.SourceEditorDataSourceDidDeleteText S __T0So14NSNotificationC4NameV12SourceEditorE0cd4DataC13DidDeleteTextADvZ
\\ S _SourceEditorDataSourceChangedNotificationEditedStartLineKey S __T012SourceEditor0ab4DataA37ChangedNotificationEditedStartLineKeySSv
\\ S _SourceEditorDataSourceChangedNotificationEditedStartColKey S __T012SourceEditor0ab4DataA36ChangedNotificationEditedStartColKeySSv
\\ S _SourceEditorDataSourceChangedNotificationEditedEndLineKey S __T012SourceEditor0ab4DataA35ChangedNotificationEditedEndLineKeySSv
\\ S _SourceEditorDataSourceChangedNotificationEditedEndColKey S __T012SourceEditor0ab4DataA34ChangedNotificationEditedEndColKeySSv
\\ S _SourceEditorDataSourceDidInsertTextNotificationStartLineKey S __T012SourceEditor0ab4DataA37DidInsertTextNotificationStartLineKeySSv
\\ S _SourceEditorDataSourceDidInsertTextNotificationStartColKey S __T012SourceEditor0ab4DataA36DidInsertTextNotificationStartColKeySSv
\\ S _SourceEditorDataSourceDidInsertTextNotificationCharOffsetKey S __T012SourceEditor0ab4DataA38DidInsertTextNotificationCharOffsetKeySSv
\\ S _SourceEditorDataSourceDidInsertTextNotificationTextKey S __T012SourceEditor0ab4Dataa25DidInsertTextNotificationF3KeySSv
\\ S _SourceEditorDataSourceDidDeleteTextNotificationStartLineKey S __T012SourceEditor0ab4DataA37DidDeleteTextNotificationStartLineKeySSv
\\ S _SourceEditorDataSourceDidDeleteTextNotificationStartColKey S __T012SourceEditor0ab4DataA36DidDeleteTextNotificationStartColKeySSv
\\ S _SourceEditorDataSourceDidDeleteTextNotificationEndLineKey S __T012SourceEditor0ab4DataA35DidDeleteTextNotificationEndLineKeySSv
\\ S _SourceEditorDataSourceDidDeleteTextNotificationEndColKey S __T012SourceEditor0ab4DataA34DidDeleteTextNotificationEndColKeySSv
\\ S _SourceEditorDataSourceDidDeleteTextNotificationCharOffsetKey S __T012SourceEditor0ab4DataA38DidDeleteTextNotificationCharOffsetKeySSv
\\ S _SourceEditorDataSourceDidDeleteTextNotificationCharLengthKey S __T012SourceEditor0ab4DataA38DidDeleteTextNotificationCharLengthKeySSv
\\ S _SourceEditorDataSourceDidDeleteTextNotificationTextKey S __T012SourceEditor0ab4Dataa25DidDeleteTextNotificationF3KeySSv
\\ S _SourceEditorDataSourceObjectLiteralNameColorLiteral S __T012SourceEditor0ab4Dataa22ObjectLiteralNameColorE0SSv
\\ S _SourceEditorDataSourceObjectLiteralNameImageLiteral S __T012SourceEditor0ab4Dataa22ObjectLiteralNameImageE0SSv
\\ S _SourceEditorDataSourceObjectLiteralNameFileLiteral S __T012SourceEditor0ab4Dataa21ObjectLiteralNameFileE0SSv
\\ s _static SourceEditorDataSource.comparisonOperators s __T012SourceEditor0ab4DataA0C19comparisonOperators33_76DCD73D096C2A8A62A7C1A15575EAAALLSo19NSRegularExpressionCvZ
\\ s _static SourceEditorDataSource.assignmentOperators s __T012SourceEditor0ab4DataA0C19assignmentOperators33_76DCD73D096C2A8A62A7C1A15575EAAALLSo19NSRegularExpressionCvZ
\\ s _static SourceEditorDataSource.binaryOperators s __T012SourceEditor0ab4DataA0C15binaryOperators33_76DCD73D096C2A8A62A7C1A15575EAAALLSo19NSRegularExpressionCvZ
\\ s _static SourceEditorDataSource.shouldVerifyLineIntegrity s __T012SourceEditor0ab4DataA0C25shouldVerifyLineIntegrity33_76DCD73D096C2A8A62A7C1A15575EAAALLSbvZ
