//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEUtilitySlice.h>

@class DVTExtension;

@interface _IDEUtilitySliceExtension : IDEUtilitySlice
{
    DVTExtension *_extension;
}

- (void).cxx_destruct;
@property(retain, nonatomic) DVTExtension *extension; // @synthesize extension=_extension;
- (id)description;
- (BOOL)wantsBottomPadding;
- (BOOL)wantsHeaderBottomBorder;
- (id)maximumAllowedRuntimeOSVersion;
- (id)minimumRequiredRuntimeOSVersion;
- (id)positionAnchor;
- (id)positionPriority;
- (BOOL)supportsDocumentInspection;
- (BOOL)supportsDocumentUndo;
- (id)inspectorTitleKeyPath;
- (id)sliceFile;
- (id)inspectorTitle;
- (id)categoryIdentifier;
- (id)contentType;
- (Class)controllerClass;
- (id)version;
- (id)name;
- (id)sliceDictionary;
- (id)bundle;
- (id)identifier;
- (id)valueForKey:(id)arg1;
- (id)initWithExtension:(id)arg1;

@end

