//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  6 2019 20:12:56).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/_IDEDistributionManualConfigurationDataSource.h>

#import <IDEKit/IDESigningEditorTeamDataSource-Protocol.h>

@class NSOrderedSet, _TtC13IDEFoundation26SigningEditorConfiguration;
@protocol IDEProvisioningBasicTeam, IDESigningEditorConfigurationDataSourceDelegate;

@interface _IDEDistributionManualSigningTeamDataSource : _IDEDistributionManualConfigurationDataSource <IDESigningEditorTeamDataSource>
{
    id <IDEProvisioningBasicTeam> _team;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) BOOL isTeamSelectionRequired;
@property(readonly) NSOrderedSet *teams;
@property(retain, nonatomic) id <IDEProvisioningBasicTeam> team;
- (id)initWithTeam:(id)arg1;

// Remaining properties
@property(readonly) _TtC13IDEFoundation26SigningEditorConfiguration *configuration;
@property __weak id <IDESigningEditorConfigurationDataSourceDelegate> configurationDataSourceDelegate;

@end

