//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSURL;

@interface _IDEIssueDocumentURL : NSObject
{
    NSURL *_url;
    unsigned long long _type;
}

- (void).cxx_destruct;
@property(readonly) unsigned long long issueType; // @synthesize issueType=_type;
@property(readonly) NSURL *url; // @synthesize url=_url;
- (id)initWithURL:(id)arg1 type:(unsigned long long)arg2;

@end

