//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/_IDENavigableItemExtraInfo.h>

@class NSMapTable;

@interface _IDEContainerItemNavigableItemExtraInfo : _IDENavigableItemExtraInfo
{
    NSMapTable *_observersByModelObjectGraph;
}

@property(readonly) NSMapTable *_observersByModelObjectGraph; // @synthesize _observersByModelObjectGraph;
- (void).cxx_destruct;
- (void)configureObservingForModelObjectGraph:(id)arg1;
- (void)processModelObjectGraphNotification:(id)arg1;
- (id)init;

@end

