//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTFoundation/DVTInvalidation_NSObject.h>

@class MISSING_TYPE;

@interface _TtC6IDEKit37IDEFilteringWorkspaceExplorableSource : DVTInvalidation_NSObject
{
    MISSING_TYPE *synchronizationQueue;
    MISSING_TYPE *baseWorkspaceSource;
    MISSING_TYPE *$__lazy_storage_$_predicateProducer;
    MISSING_TYPE *currentFilterSession;
    MISSING_TYPE *canonicalTreeToken;
    MISSING_TYPE *recentFilesToken;
    MISSING_TYPE *filterMatches;
    MISSING_TYPE *currentFilterSpec;
}

- (void).cxx_destruct;
- (id)init;
- (void)primitiveInvalidate;

@end

