//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEInspectorProperty.h>

#import <IDEKit/IDEJumpToFieldCellDelegate-Protocol.h>

@class IDEJumpToField, MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC6IDEKit28IDEInspectorURLFieldProperty : IDEInspectorProperty <IDEJumpToFieldCellDelegate>
{
    MISSING_TYPE *jumpToField;
    MISSING_TYPE *valueKeyPath;
    MISSING_TYPE *placeholderKeyPath;
    MISSING_TYPE *placeholder;
    MISSING_TYPE *linkPathKeyPath;
    MISSING_TYPE *url;
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)primitiveInvalidate;
- (void)setupRefreshTriggersAndConfigure;
- (void)IDEJumpToFieldCell:(id)arg1 clickedPathArrow:(id)arg2;
- (void)refresh;
- (double)baseline;
@property(nonatomic) __weak IDEJumpToField *jumpToField; // @synthesize jumpToField;
- (id)initWithCoder:(id)arg1;
- (id)initWithPropertyDefinition:(id)arg1 andController:(id)arg2;

@end

