//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTFoundation/DVTInvalidation_NSObject.h>

#import <IDEKit/DVTStatefulObject-Protocol.h>

@class IDEEditorContext, MISSING_TYPE, NSArray, _TtC19DVTUserInterfaceKit17DVTDocumentTabBar, _TtC6IDEKit12IDEEditorTab;
@protocol _TtP6IDEKit28IDEEditorTabViewHostProtocol_, _TtP6IDEKit34IDEEditorTabViewControllerDelegate_;

@interface _TtC6IDEKit26IDEEditorTabViewController : DVTInvalidation_NSObject <DVTStatefulObject>
{
    MISSING_TYPE *_editorContext;
    MISSING_TYPE *tabViewHost;
    MISSING_TYPE *tabBarView;
    MISSING_TYPE *delegate;
    MISSING_TYPE *_showStaticEditorTabBacktrace;
    MISSING_TYPE *_willChangeDocumentBacktrace;
    MISSING_TYPE *_isNavigatingToStaticEditorTab;
    MISSING_TYPE *_isRespondingToTabSelectionChange;
    MISSING_TYPE *_logAspect;
    MISSING_TYPE *__didEndDocumentTransactionToken;
    MISSING_TYPE *__editorDocumentWillCloseNotificationToken;
    MISSING_TYPE *__documentControllerEditorDocumentsToken;
    MISSING_TYPE *_editorTabs;
    MISSING_TYPE *_selectedEditorTabIndex;
    MISSING_TYPE *canCloseLastTab;
    MISSING_TYPE *isDraggingSource;
    MISSING_TYPE *_stateToken;
}

+ (long long)tabCountFromDictionary:(id)arg1;
+ (id)dynamicTabIndexFromDictionary:(id)arg1;
+ (void)configureStateSavingObjectPersistenceByName:(id)arg1;
+ (BOOL)navigateUsingTabViewController:(id)arg1 staticEditorTab:(BOOL)arg2 block:(CDUnknownBlockType)arg3;
- (void).cxx_destruct;
- (void)commitStateToDictionary:(id)arg1;
- (void)revertStateWithDictionary:(id)arg1;
- (void)setStateToken:(id)arg1;
- (id)stateToken;
- (void)_menu_convertToStaticTab:(id)arg1;
- (void)_menu_closeAllOtherTabs:(id)arg1;
- (void)_menu_closeTab:(id)arg1;
@property(nonatomic) BOOL isDraggingSource; // @synthesize isDraggingSource;
- (void)_updateDocumentTabBarViewFromEditorTabs;
@property(nonatomic) BOOL canCloseLastTab; // @synthesize canCloseLastTab;
- (id)updateIconForDocumentURL:(id)arg1 historyItem:(id)arg2 updateImageBlock:(CDUnknownBlockType)arg3;
- (id)iconFor:(id)arg1;
- (void)convertSelectedTabToStaticEditorTab;
- (BOOL)canConvertSelectedTabToStaticEditorTab;
- (void)convertSelectedTabToDynamicEditorTab;
- (BOOL)canConvertSelectedTabToDynamicEditorTab;
- (void)updateCurrentHistoryItem:(id)arg1;
- (void)editorContextDidChangeEditorMode;
- (void)editorContextDidChangeSelectedDocument:(id)arg1 useStaticTab:(BOOL)arg2;
- (id)editorContextWillChangeSelectedDocument:(id)arg1;
- (void)documentPropertyDidChangeFor:(id)arg1 document:(id)arg2 block:(CDUnknownBlockType)arg3;
- (void)_openTabInEditorContext:(id)arg1 scrollToVisible:(BOOL)arg2;
- (void)primitiveInvalidate;
- (void)documentIsClosingWithEditorTab:(id)arg1 isClosingToRevert:(BOOL)arg2 replacementURL:(id)arg3;
- (void)_closeAllEditorTabs;
- (void)_setWithEditorTabs:(id)arg1 select:(id)arg2;
@property(nonatomic, readonly) _TtC6IDEKit12IDEEditorTab *_selectedEditorTab;
@property(nonatomic) long long _selectedEditorTabIndex; // @synthesize _selectedEditorTabIndex;
@property(nonatomic, copy) NSArray *_editorTabs;
- (long long)editorTabsCount;
- (BOOL)hasDynamicTab;
- (BOOL)hasStaticTabs;
- (void)closeOtherTabsWithClient:(unsigned long long)arg1;
- (BOOL)canCloseOtherTabs;
- (void)closeActiveTabWithClient:(unsigned long long)arg1;
- (BOOL)canCloseActiveTab;
- (void)showNextTab;
- (void)showPreviousTab;
- (BOOL)hasNextTab;
- (BOOL)hasPreviousTab;
- (void)updateWithEditorContext:(id)arg1 tabViewHost:(id)arg2;
- (id)init;
@property(nonatomic, retain) id <_TtP6IDEKit34IDEEditorTabViewControllerDelegate_> delegate; // @synthesize delegate;
@property(nonatomic, retain) _TtC19DVTUserInterfaceKit17DVTDocumentTabBar *tabBarView; // @synthesize tabBarView;
@property(nonatomic, retain) id <_TtP6IDEKit28IDEEditorTabViewHostProtocol_> tabViewHost; // @synthesize tabViewHost;
@property(nonatomic, retain) IDEEditorContext *editorContext;

@end

