//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTFoundation/DVTInvalidation_NSObject.h>

#import <IDEKit/_TtP6IDEKit20IDEEditorTabProtocol_-Protocol.h>

@class MISSING_TYPE, NSImage, NSString, NSURL, _TtC6IDEKit26IDEEditorTabViewController;
@protocol IDEEditorHistoryControllerItem, _TtP6IDEKit29IDEEditorTab_DocumentProtocol_;

@interface _TtC6IDEKit12IDEEditorTab : DVTInvalidation_NSObject <_TtP6IDEKit20IDEEditorTabProtocol_>
{
    MISSING_TYPE *isDynamic;
    MISSING_TYPE *documentDisplayName;
    MISSING_TYPE *documentURL;
    MISSING_TYPE *documentIcon;
    MISSING_TYPE *historyItem;
    MISSING_TYPE *_tabViewController;
    MISSING_TYPE *__fileURLObservingToken;
    MISSING_TYPE *__displayNameObservingToken;
    MISSING_TYPE *__updateIconToken;
    MISSING_TYPE *document;
}

- (void).cxx_destruct;
- (id)init;
- (void)primitiveInvalidate;
@property(nonatomic, retain) id <_TtP6IDEKit29IDEEditorTab_DocumentProtocol_> document; // @synthesize document;
- (id)initWithDocument:(id)arg1 historyItem:(id)arg2 isDynamic:(BOOL)arg3 tabViewController:(id)arg4;
- (id)initWithDocument:(id)arg1 historyItem:(id)arg2 documentURL:(id)arg3 isDynamic:(BOOL)arg4 tabViewController:(id)arg5;
@property(nonatomic, retain) _TtC6IDEKit26IDEEditorTabViewController *tabViewController;
@property(nonatomic, retain) id <IDEEditorHistoryControllerItem> historyItem; // @synthesize historyItem;
@property(nonatomic, retain) NSImage *documentIcon; // @synthesize documentIcon;
@property(nonatomic, copy) NSURL *documentURL;
@property(nonatomic, copy) NSString *documentDisplayName;
@property(nonatomic) BOOL isDynamic; // @synthesize isDynamic;

@end

