//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTStructuredLayoutKit/DVTLayoutView_ML.h>

@class MISSING_TYPE, NSButton, NSLayoutConstraint, NSStackView, NSTextField, _TtC6IDEKit30IDEInspectorPathEditorProperty;

__attribute__((visibility("hidden")))
@interface _TtC6IDEKit27_IDEInspectorPathEditorView : DVTLayoutView_ML
{
    MISSING_TYPE *_parentController;
    MISSING_TYPE *_chooserButton;
    MISSING_TYPE *_clearButton;
    MISSING_TYPE *_buttonGroup;
    MISSING_TYPE *_pathTextField;
    MISSING_TYPE *_pathTextFieldBottom;
    MISSING_TYPE *_pathTextFieldTop;
    MISSING_TYPE *_pathTextFieldLeading;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (BOOL)performDragOperation:(id)arg1;
- (unsigned long long)draggingEntered:(id)arg1;
- (void)awakeFromNib;
- (void)layoutBottomUp;
@property(nonatomic, retain) NSLayoutConstraint *_pathTextFieldLeading; // @synthesize _pathTextFieldLeading;
@property(nonatomic, retain) NSLayoutConstraint *_pathTextFieldTop; // @synthesize _pathTextFieldTop;
@property(nonatomic, retain) NSLayoutConstraint *_pathTextFieldBottom; // @synthesize _pathTextFieldBottom;
@property(nonatomic, retain) NSTextField *_pathTextField; // @synthesize _pathTextField;
@property(nonatomic, retain) NSStackView *_buttonGroup; // @synthesize _buttonGroup;
@property(nonatomic, retain) NSButton *_clearButton; // @synthesize _clearButton;
@property(nonatomic, retain) NSButton *_chooserButton; // @synthesize _chooserButton;
@property(nonatomic) __weak _TtC6IDEKit30IDEInspectorPathEditorProperty *_parentController; // @synthesize _parentController;

@end

