//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextFieldCell.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC6IDEKit23TrainyardLabelFieldCell : NSTextFieldCell
{
    MISSING_TYPE *icon;
    MISSING_TYPE *expandIcon;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initTextCell:(id)arg1;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (struct CGSize)cellSizeForBounds:(struct CGRect)arg1;

@end

