//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  6 2019 20:12:56).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC6IDEKit30IDEResultBundleSpotlightFinder : _TtCs12_SwiftObject
{
    // Error parsing type: , name: _queue_isRunning
    // Error parsing type: , name: _queue_isCanceled
    // Error parsing type: , name: syncQueue
    // Error parsing type: , name: notificationToken
    // Error parsing type: , name: workspaceName
}

@end

