//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCOC6IDEKit13IDEEditorCore15InstalledEditor7Bridged : _TtCs12_SwiftObject
{
    MISSING_TYPE *editor;
    MISSING_TYPE *options;
    MISSING_TYPE *documentSpecifier;
    MISSING_TYPE *jumpBarController;
    MISSING_TYPE *selectionDidChange;
    MISSING_TYPE *documentRep;
    MISSING_TYPE *interiorContent;
    MISSING_TYPE *controlVisibility;
    MISSING_TYPE *observationTokens;
    MISSING_TYPE *selection;
}

@end

