//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSButton.h>

__attribute__((visibility("hidden")))
@interface _TtC6IDEKit30IDESourceControlFavoriteButton : NSButton
{
    // Error parsing type: , name: trackingArea
    // Error parsing type: , name: isMouseOver
    // Error parsing type: , name: REMOVE_STAR_IMAGE
    // Error parsing type: , name: ADD_STAR_IMAGE
    // Error parsing type: , name: STAR_IMAGE
    // Error parsing type: , name: EMPTY_STAR_IMAGE
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)dealloc;
- (void)updateTrackingAreas;
- (void)drawRect:(struct CGRect)arg1;
@property(nonatomic) long long state;

@end

