//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/NSObject-Protocol.h>

@class NSImage, NSString, NSURL;
@protocol IDEEditorHistoryControllerItem;

@protocol _TtP6IDEKit20IDEEditorTabProtocol_ <NSObject>
@property(nonatomic, retain) id <IDEEditorHistoryControllerItem> historyItem;
@property(nonatomic, retain) NSImage *documentIcon;
@property(nonatomic, copy) NSURL *documentURL;
@property(nonatomic, copy) NSString *documentDisplayName;
@property(nonatomic) BOOL isDynamic;
@end

