//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class IDENavigatorChoice, IDENavigatorChooserView;

@protocol _TtP6IDEKit31IDENavigatorChooserViewDelegate_
- (void)navigatorChooserView:(IDENavigatorChooserView *)arg1 selected:(IDENavigatorChoice *)arg2;
@end

