//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol DVTInvalidation;

@protocol _TtP6IDEKit39IDETestReportCallStackCodeRoll_Document_
- (id <DVTInvalidation>)observeCloseWithHandler:(BOOL (^)(id <_TtP6IDEKit39IDETestReportCallStackCodeRoll_Document_>))arg1;
@property(nonatomic, readonly) BOOL isClosed;
@end

