//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  6 2019 20:12:56).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/NSObject-Protocol.h>

@class IDESchemeBuildableReference, IDETest, NSSet, _TtC13IDEFoundation25IDEDeviceAppDataReference, _TtC13IDEFoundation28IDELocationScenarioReference;
@protocol IDETestable;

@protocol _TtP13IDEFoundation36IDETestPlanTestableReferenceProtocol_ <NSObject>
- (BOOL)isTestEnabledInHierarchy:(IDETest *)arg1;
@property(nonatomic, readonly) long long testExecutionOrdering;
@property(nonatomic, readonly) _TtC13IDEFoundation28IDELocationScenarioReference *locationScenarioReference;
@property(nonatomic, readonly) _TtC13IDEFoundation25IDEDeviceAppDataReference *deviceAppDataReference;
@property(nonatomic, readonly) BOOL isAssociatedWithSchemeAction;
@property(nonatomic, readonly) NSSet *selectedTests;
@property(nonatomic, readonly) NSSet *skippedTests;
@property(nonatomic, readonly) long long testSelectionMode;
@property(nonatomic, readonly) BOOL parallelizable;
@property(nonatomic, readonly) BOOL isEnabled;
@property(nonatomic, readonly) IDESchemeBuildableReference *buildableReference;
@property(nonatomic, readonly) id <IDETestable> testable;
@end

