//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/NSObject-Protocol.h>

@class NSMenuItem, NSString;

@protocol DVTMenuBuilder <NSObject>
+ (NSMenuItem *)contextHelpMenuItemForHelpID:(NSString *)arg1 andTitle:(NSString *)arg2;

@optional
+ (NSMenuItem *)contextHelpMenuItemForHelpID:(NSString *)arg1;
@end

