//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <QuartzCore/CALayer.h>

#import <IDEKit/DVTInvalidation-Protocol.h>
#import <IDEKit/IDEActivityThemeableLayer-Protocol.h>

@class DVTObservingToken, DVTStackBacktrace, IDEActivityActionButtonLayer, IDEActivityProgressIndicatorLayer, IDEActivityReport, IDEActivityScrollingTextLayer, IDEActivityView, NSMutableArray, NSString;

@interface IDEActivityReportLayer : CALayer <DVTInvalidation, IDEActivityThemeableLayer>
{
    IDEActivityProgressIndicatorLayer *_progressIndicatorLayer;
    IDEActivityScrollingTextLayer *_scrollingTextLayer;
    IDEActivityActionButtonLayer *_cancelButtonLayer;
    long long _displayStyle;
    IDEActivityReport *_activityReport;
    CALayer *_imageLayer;
    NSMutableArray *_stringSegments;
    BOOL _paused;
    DVTObservingToken *_kvoActivityReportTitleSegmentsToken;
    DVTObservingToken *_kvoActivityReportProgressToken;
    DVTObservingToken *_kvoActivityReportTitleToken;
    DVTObservingToken *_kvoActivityReportThrottleFactorToken;
    BOOL _isActiveWindowStyle;
    IDEActivityReport *_displayedReportValidCopy;
    double _spaceNeededForMultiActionIndicator;
    double _spaceNeededForStatusLayers;
    IDEActivityView *_activityView;
    DVTObservingToken *_validReportObserver;
}

+ (id)keyPathsForValuesAffectingIndeterminateReportInProgress;
+ (id)activityReportLayerForDisplayStyle:(long long)arg1;
+ (struct CGSize)defaultSizeForPopUpStyle;
+ (void)initialize;
- (void).cxx_destruct;
@property(retain) DVTObservingToken *validReportObserver; // @synthesize validReportObserver=_validReportObserver;
@property(retain) IDEActivityView *activityView; // @synthesize activityView=_activityView;
@property(nonatomic) double spaceNeededForStatusLayers; // @synthesize spaceNeededForStatusLayers=_spaceNeededForStatusLayers;
@property(nonatomic) double spaceNeededForMultiActionIndicator; // @synthesize spaceNeededForMultiActionIndicator=_spaceNeededForMultiActionIndicator;
@property(nonatomic) BOOL isActiveWindowStyle; // @synthesize isActiveWindowStyle=_isActiveWindowStyle;
@property(retain) IDEActivityReport *displayedReportValidCopy; // @synthesize displayedReportValidCopy=_displayedReportValidCopy;
@property(nonatomic) long long displayStyle; // @synthesize displayStyle=_displayStyle;
@property(retain, nonatomic) IDEActivityReport *activityReport; // @synthesize activityReport=_activityReport;
- (void)updateTheme;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)dvt_view;
- (void)layoutSublayers;
- (double)spaceNeededForCancelButtonLayer;
- (BOOL)shouldShowCancelButtonLayer;
@property(readonly) BOOL indeterminateReportInProgress;
- (void)updateVisibilityForCancelButtonAndAdjustLayoutIfNeeded;
- (void)updateVisibilityForTextFieldAndAdjustLayoutIfNeeded;
- (BOOL)shouldHideProgress;
- (void)_startObservingActivityReport;
- (void)_stopObservingActivityReport;
- (void)updateScrollingTextFieldStringValue;
- (id)_workspace;
- (void)_updatePaused:(BOOL)arg1;
- (void)_updateStringSegments:(id)arg1;
- (void)_removePausedSegment;
- (void)_addPausedSegment;
- (id)_pausedAttributes;
- (id)defaultIdleActionString;
- (id)nonFailedBuildTextAttributes;
- (id)defaultIdleTitle;
- (id)defaultReportTitle;
- (id)defaultCompletionSummary;
- (void)updateConstraints;
@property(readonly, copy) NSString *description;
- (id)init;
- (void)primitiveInvalidate;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

