//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSCache, NSSet;

@interface IDEClassIconProvider : NSObject
{
    NSSet *_extensions;
    NSCache *_cache;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)_iconEntryForClassName:(id)arg1;
- (void)cachedImageForClassNameOrAnySuperclassName:(id)arg1 index:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)cachedImageForAnyClassName:(id)arg1;
- (id)_cachedIconEntryForAnyClassName:(id)arg1;
- (id)cachedImageForClassName:(id)arg1;
- (id)_cachedIconEntryForClassName:(id)arg1;
- (id)init;

@end

