//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  6 2019 20:12:56).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IDEGroup, IDENavigableItem, IDENavigableItemCoordinator, IDEWorkspace, NSPopUpButton, NSSavePanel, NSURL;
@protocol IDECompletionDestinationDelegate;

@interface IDECompletionDestinationManager : NSObject
{
    NSURL *_lastSetDirectoryURL;
    IDENavigableItem *_workspaceNavigableItem;
    id <IDECompletionDestinationDelegate> _delegate;
    NSPopUpButton *_destinationGroupPopUp;
    NSPopUpButton *_destinationWorkspacePopUp;
    NSSavePanel *_savePanel;
    IDEWorkspace *_workspace;
    IDEGroup *_destinationGroup;
    IDENavigableItemCoordinator *_navigableItemCoordinator;
}

@property(retain, nonatomic) IDENavigableItemCoordinator *navigableItemCoordinator; // @synthesize navigableItemCoordinator=_navigableItemCoordinator;
@property(retain) IDEGroup *destinationGroup; // @synthesize destinationGroup=_destinationGroup;
@property(retain) IDEWorkspace *workspace; // @synthesize workspace=_workspace;
@property(retain) NSSavePanel *savePanel; // @synthesize savePanel=_savePanel;
@property(retain, nonatomic) NSPopUpButton *destinationWorkspacePopUp; // @synthesize destinationWorkspacePopUp=_destinationWorkspacePopUp;
@property(retain, nonatomic) NSPopUpButton *destinationGroupPopUp; // @synthesize destinationGroupPopUp=_destinationGroupPopUp;
@property(retain) id <IDECompletionDestinationDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)workspaceNavigableItem;
- (void)deactivate;
- (void)activate;
- (void)clearDestinationWorkspace;
- (void)selectedWorkspaceDidChange:(id)arg1;
- (void)populateDestinationWorkspacePopUp;
- (void)clearDestinationGroup;
- (void)selectedGroupDidChange:(id)arg1;
- (void)populateDestinationGroupPopUp;
- (void)addMenuItemsToPopUpButton:(id)arg1 menu:(id)arg2 forItem:(id)arg3 indentationLevel:(unsigned long long)arg4 items:(id)arg5;
- (BOOL)shouldAddItemToDestinationMenu:(id)arg1;
- (id)menuItemForDestinationGroup:(id)arg1;
- (id)destinationGroupForMenuItem:(id)arg1;

@end

