//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTStructuredLayoutKit/DVTLayoutView_ML.h>

@class NSMutableArray, NSString, NSTextField;

@interface IDECapsuleFooterView : DVTLayoutView_ML
{
    NSMutableArray *_buttons;
    NSTextField *_labelField;
}

- (void).cxx_destruct;
- (void)layoutBottomUp;
- (void)layoutTopDown;
@property(copy) NSString *label;
- (id)addButtonWithImage:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

