//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/NSObject-Protocol.h>

@class DVTFilePath, IDEDistributionMethod, NSArray, NSDictionary, NSString;
@protocol IDEDistributable;

@protocol IDEDistributionArchiveReformatter <NSObject>
- (NSArray *)reformatterWarnings:(IDEDistributionMethod *)arg1 archive:(id <IDEDistributable>)arg2 error:(id *)arg3;
- (id <IDEDistributable>)reformattedArchive:(id <IDEDistributable>)arg1 distributionMethod:(IDEDistributionMethod *)arg2 temporaryDirectory:(DVTFilePath *)arg3 error:(id *)arg4;
- (NSString *)targetName:(id <IDEDistributable>)arg1 distributionMethod:(IDEDistributionMethod *)arg2 error:(id *)arg3;
- (NSString *)targetBundleIdentifier:(id <IDEDistributable>)arg1 distributionMethod:(IDEDistributionMethod *)arg2 error:(id *)arg3;
- (BOOL)wantsReformattingForArchive:(id <IDEDistributable>)arg1 distributionMethod:(IDEDistributionMethod *)arg2;
- (BOOL)isAppStoreContainerAppInfoDictionary:(NSDictionary *)arg1;
- (long long)sortOrder;
- (NSString *)appTypeDescription;
- (BOOL)supportsManifestDistribution;
- (NSString *)inspectablePropertyValueForArchive:(id <IDEDistributable>)arg1;
- (NSString *)inspectablePropertyName;
@end

