//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEDistributionStepViewController.h>

@interface IDEDistributionAppStoreConfigurationStepViewController : IDEDistributionStepViewController
{
}

+ (BOOL)skipStepForContext:(id)arg1 assistantDirection:(long long)arg2;
- (BOOL)canGoPrevious;
- (BOOL)canGoNext;
- (id)title;
- (id)providedOutputContextPropertyNames;
- (id)requiredInputContextPropertyNames;
- (BOOL)shouldUseDefaultConfiguration;
- (void)viewDidLoad;

@end

