//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDESplitViewDebugArea.h>

#import <IDEKit/DVTReplacementViewDelegate-Protocol.h>
#import <IDEKit/DVTSplitViewDelegate-Protocol.h>
#import <IDEKit/DVTStatefulObject-Protocol.h>

@class DVTExtension, DVTObservingToken, IDEConsoleArea, NSString;

@interface IDEDefaultDebugArea : IDESplitViewDebugArea <DVTReplacementViewDelegate, DVTSplitViewDelegate, DVTStatefulObject>
{
    DVTExtension *_currentConsoleExtension;
    DVTExtension *_currentVariablesViewExtension;
    DVTObservingToken *_launchSessionObserver;
    BOOL _shouldOnlyAllowConsole;
}

//- (void).cxx_destruct;
@property(nonatomic) BOOL shouldOnlyAllowConsole; // @synthesize shouldOnlyAllowConsole=_shouldOnlyAllowConsole;
- (void)replacementView:(id)arg1 didInstallViewController:(id)arg2;
@property(readonly) IDEConsoleArea *consoleArea;
- (void)_launchSessionChanged:(id)arg1;
@property(retain) DVTExtension *currentConsoleExtension; // @dynamic currentConsoleExtension;
- (void)_cancelAndNilOutObservers;
- (void)primitiveInvalidate;
- (void)viewWillUninstall;
- (void)viewDidInstall;
- (void)activateConsole;
- (BOOL)canActivateConsole;
- (void)reloadConsole;
- (BOOL)canReloadConsole;
- (void)clearConsole;
- (BOOL)canClearConsole;
- (id)stateSavingIdentifier;
- (id)toolTipForHideRightViewButton;
- (id)toolTipForShowRightViewButton;
- (id)toolTipForHideLeftViewButton;
- (id)toolTipForShowLeftViewButton;
- (void)loadView;

// Remaining properties
@property(readonly) BOOL canRevertWithEmptyStateDictionary;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

