//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTFoundation/DVTInvalidation_NSObject.h>

@class _TtC6IDEKit47IDEExplorableJumpBarControllerBindingsInterface;
@protocol _TtP6IDEKit38IDEExplorableJumpBarControllerDelegate_;

@interface IDEExplorableJumpBarController : DVTInvalidation_NSObject
{
    // Error parsing type: , name: content
    // Error parsing type: , name: delegate
    // Error parsing type: , name: identifierToHandle
    // Error parsing type: , name: bindingsInterface
    // Error parsing type: , name: pendingSelectionToPushToBindingsInterface
}

- (void).cxx_destruct;
- (id)init;
- (void)pathCell:(id)arg1 willDismissMenuDisplayingItems:(id)arg2;
- (void)pathCell:(id)arg1 willDisplayChildren:(id)arg2 mostProximateChildItem:(id)arg3;
- (id)takeoverPathControl:(id)arg1;
- (void)userDidSelectIdentifier:(id)arg1;
- (void)primitiveInvalidate;
@property(nonatomic, readonly) BOOL hasSelection;
@property(nonatomic, retain) _TtC6IDEKit47IDEExplorableJumpBarControllerBindingsInterface *bindingsInterface; // @synthesize bindingsInterface;
@property(nonatomic, retain) id <_TtP6IDEKit38IDEExplorableJumpBarControllerDelegate_> delegate; // @synthesize delegate;

@end

