//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTStructuredLayoutKit/DVTLayoutView_ML.h>

#import <IDEKit/DVTInvalidation-Protocol.h>

@class DVTGradientImageButton, DVTObservingToken, DVTStackBacktrace, NSArrayController, NSString, NSView;

@interface IDEEditorStepperView : DVTLayoutView_ML <DVTInvalidation>
{
    DVTGradientImageButton *_leftArrowButton;
    DVTGradientImageButton *_rightArrowButton;
    NSView *_centerView;
    NSArrayController *_arrayController;
    DVTObservingToken *_countObservingToken;
}

+ (void)initialize;
+ (id)keyPathsForValuesAffectingCanMove;
+ (id)_arrowButtonWithDirection:(BOOL)arg1;
- (void).cxx_destruct;
@property(retain) NSArrayController *arrayController; // @synthesize arrayController=_arrayController;
- (void)primitiveInvalidate;
- (void)selectPrevious:(id)arg1;
- (void)selectNext:(id)arg1;
- (BOOL)canMove;
- (id)_toolTipForRightArrow;
- (id)_toolTipForLeftArrow;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)rightArrowButton;
- (id)leftArrowButton;
- (id)newCenterView;
- (void)layoutBottomUp;
- (double)centerViewOverlap;
- (struct CGSize)centerViewSizeInHeight:(double)arg1;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

