//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEAbstractEditorBar.h>

#import <IDEKit/DVTActiveStateAware-Protocol.h>

@class DVTActiveStateAwareToken, _TtC19DVTUserInterfaceKit17DVTDocumentTabBar;

@interface IDEEditorTabBar : IDEAbstractEditorBar <DVTActiveStateAware>
{
    _TtC19DVTUserInterfaceKit17DVTDocumentTabBar *_tabBarView;
    DVTActiveStateAwareToken *_activeStateAwareToken;
    BOOL _inActiveContext;
}

- (void).cxx_destruct;
@property(nonatomic, getter=isInActiveContext) BOOL inActiveContext; // @synthesize inActiveContext=_inActiveContext;
- (void)primitiveInvalidate;
- (void)editorModeDidChange;
@property(retain) _TtC19DVTUserInterfaceKit17DVTDocumentTabBar *tabBarView;
- (void)viewDidMoveToWindow;
- (unsigned long long)leftControlGroupVisibility;
- (unsigned long long)rightControlGroupVisibility;
- (void)_IDEAbstractEditorBarSharedInit;

@end

