//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  6 2019 20:12:56).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IDEEditorContextExtract : NSObject
{
}

- (void)openRecentItemWithArchivableRep:(id)arg1 editor:(id)arg2;
- (id)defaultFileDataTypeForURL:(id)arg1;
- (id)defaultDocumentExtensionForURL:(id)arg1 contentsURL:(id)arg2 error:(id *)arg3;
- (id)makeEditorWithDocument:(id)arg1 documentExtension:(id)arg2 editorClass:(Class)arg3 error:(id *)arg4;
- (id)_newDocumentWithURL:(id)arg1 contentsURL:(id)arg2 fileDataType:(id)arg3 documentClass:(Class)arg4 documentExtension:(id)arg5 error:(id *)arg6;
- (BOOL)_isSeeminglyValidURL:(id)arg1;
- (id)_replaceDocument:(id)arg1 withDocumentURL:(id)arg2 contentsURL:(id)arg3 documentExtension:(id)arg4 error:(id *)arg5;
- (id)documentWithURL:(id)arg1 contentsURL:(id)arg2 fileDataType:(id)arg3 documentExtension:(id)arg4 error:(id *)arg5;
- (void)setEditorCore:(id)arg1 onEditor:(id)arg2;

@end

