//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/NSObject-Protocol.h>

@class IDEFunctionBarSimulatorWorkspaceExecutionReporter, IDEWorkspace;

@protocol IDEFunctionBarSimulatorWorkspaceExecutionReporterDelegate <NSObject>
- (void)touchBarSimulatorWorkspaceExecutionReporter:(IDEFunctionBarSimulatorWorkspaceExecutionReporter *)arg1 workspace:(IDEWorkspace *)arg2 didChangeActiveExecutionsCount:(long long)arg3;
@end

