//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  6 2019 20:12:56).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEKit/IDECommandHandler-Protocol.h>
#import <IDEKit/IDECommandHandlerVendor-Protocol.h>

@class NSString;
@protocol IDESelectionSource;

@interface IDEFindNavigatorCommands : NSObject <IDECommandHandlerVendor, IDECommandHandler>
{
    id <IDESelectionSource> _selectionSource;
}

+ (id)symbolForSourceExpression:(id)arg1 inWorkspaceTableController:(id)arg2;
+ (id)handlerForAction:(SEL)arg1 withSelectionSource:(id)arg2;
- (void).cxx_destruct;
- (void)focusOnCallHiearchySymbol:(id)arg1;
- (void)revealCallHierarchySymbolInSymbolNavigator:(id)arg1;
- (id)contextMenuFocusedCallHierarchySymbol;
- (void)showCallHierarchy:(id)arg1;
- (void)invokeWithSelectedSymbolForFindAction:(CDUnknownBlockType)arg1;
- (void)initiateCallHierarchyQueryWithSymbol:(id)arg1 inWorkspaceTabController:(id)arg2;
- (void)searchInSelectedFolders:(id)arg1;
- (void)searchInSelectedGroups:(id)arg1;
- (void)navigateToPreviousFindResult:(id)arg1;
- (void)navigateToNextFindResult:(id)arg1;
- (void)navigateToAdjascentFindResultInDirection:(long long)arg1;
- (id)adjascentResultFindResultInDirection:(long long)arg1;
- (void)findAndReplaceInWorkspace:(id)arg1;
- (void)findSelectedSymbolInWorkspace:(id)arg1;
- (void)findSelectedTextInWorkspace:(id)arg1;
- (void)findText:(id)arg1 inWorkspaceWithQueryClass:(Class)arg2;
- (void)findTerm:(id)arg1 inWorkspaceWithQueryClass:(Class)arg2;
- (void)findInWorkspace:(id)arg1;
- (id)workspaceTabControllerAfterRunningAlertWithTitle:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (BOOL)validateAction:(SEL)arg1;
- (BOOL)anySelectedNavigableItemsAllowScoping;
- (void)enumerateSelectedNavigableItemsForScoping:(CDUnknownBlockType)arg1;
- (id)workspaceBeforeRetargeting;
- (id)workspaceTabControllerBeforeRetargeting;
- (id)selectedSelectionItems;
- (id)initWithSelectionSource:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

