//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEAbstractFindNavigatorOutlineViewDelegate-Protocol.h>

@class IDEFindNavigatorOutlineView;

@protocol IDEFindNavigatorOutlineViewDelegate <IDEAbstractFindNavigatorOutlineViewDelegate>
- (void)findNavigatorOutlineViewEmptyContentPlaceholderButtonWasClicked:(IDEFindNavigatorOutlineView *)arg1;
@end

