//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEFileNavigableItem.h>

@class NSColor, NSString, NSURL;

@interface IDEFileReferenceNavigableItem : IDEFileNavigableItem
{
    NSURL *_fileURL;
    NSString *_scmLocalStatus;
    NSString *_scmServerStatus;
    struct {
        unsigned int _needUpdateForFileURL:1;
        unsigned int _reserved:31;
    } _ideFileRefNavItemflags;
    BOOL _associatedFileExists;
}

+ (id)keyPathsForValuesAffectingFileReference;
+ (id)_createExtraInfoObject;
+ (void)_editorDocumentDirtyStatusDidChange:(id)arg1;
+ (void)_anyEditorDocumentDirtyStatusWillClose:(id)arg1;
+ (void)_anyEditorDocumentDirtyStatusDidChange:(id)arg1;
+ (void)initialize;
- (void).cxx_destruct;
@property(readonly) BOOL associatedFileExists; // @synthesize associatedFileExists=_associatedFileExists;
@property(readonly) BOOL displaysStatus;
@property(readonly) BOOL displaysProgress;
- (unsigned long long)conflictStateForUpdateOrMerge;
- (id)sourceControlServerStatus;
- (unsigned long long)sourceControlServerStatusFlag;
- (id)sourceControlLocalStatus;
- (unsigned long long)sourceControlLocalStatusFlag;
- (BOOL)isDocumentNavigableItem;
@property(readonly) NSColor *textColor;
- (id)newImage;
- (id)fileURL;
- (void)updateChildRepresentedObjects;
- (void)updateAttributes;
- (id)fileReference;
- (id)initWithRepresentedObject:(id)arg1;

@end

