//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextField.h>

@class NSAttributedString;

@interface IDEFindNavigatorResultTextField : NSTextField
{
    CDStruct_bf6d4a14 _layoutInset;
}

+ (Class)cellClass;
@property CDStruct_bf6d4a14 layoutInset; // @synthesize layoutInset=_layoutInset;
- (BOOL)allowsVibrancy;
@property(copy) NSAttributedString *expansionText;

@end

