//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEKit/IDEKeyDrivenNavigableItemRepresentedObject-Protocol.h>

@class DVTDocumentLocation, DVTFileDataType, IDEBatchFindFilePathPredicate, IDEFileReference, NSArray, NSImage, NSMutableArray, NSNull, NSString, NSURL, _TtC13DVTFoundation9DVTSymbol;

@interface IDEFindNavigatorAbstractScopeOutlineItem : NSObject <IDEKeyDrivenNavigableItemRepresentedObject>
{
    NSMutableArray *_children;
    BOOL _passedFilterLocally;
    BOOL _descendantPassedFilter;
    NSString *_title;
    NSImage *_icon;
    IDEBatchFindFilePathPredicate *_predicate;
}

@property(retain, nonatomic) NSArray *children; // @synthesize children=_children;
@property(readonly) BOOL descendantPassedFilter; // @synthesize descendantPassedFilter=_descendantPassedFilter;
@property(readonly) BOOL passedFilterLocally; // @synthesize passedFilterLocally=_passedFilterLocally;
@property(readonly) IDEBatchFindFilePathPredicate *predicate; // @synthesize predicate=_predicate;
@property(readonly) NSImage *icon; // @synthesize icon=_icon;
@property(readonly) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
@property(readonly) BOOL initiallyExpandsSecondLevelChildren;
- (void)addChild:(id)arg1;
- (BOOL)isFilterable;
@property(readonly, nonatomic) NSString *navigableItem_name;
@property(readonly, copy) NSString *description;
- (id)filteredCloneWithChildren:(id)arg1 passedFilterLocally:(BOOL)arg2 descendantPassedFilter:(BOOL)arg3;
- (id)initWithTitle:(id)arg1 icon:(id)arg2 children:(id)arg3 passedFilterLocally:(BOOL)arg4 descendantPassedFilter:(BOOL)arg5;
- (id)initWithTitle:(id)arg1 icon:(id)arg2 predicate:(id)arg3 children:(id)arg4 passedFilterLocally:(BOOL)arg5 descendantPassedFilter:(BOOL)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSString *navigableItem_accessibilityIdentifier;
@property(readonly, nonatomic) NSString *navigableItem_accessibleImageDescription;
@property(readonly, nonatomic) NSArray *navigableItem_additionalFilterMatchingText;
@property(readonly, nonatomic) NSArray *navigableItem_childRepresentedObjects;
@property(readonly, nonatomic) DVTDocumentLocation *navigableItem_contentDocumentLocation;
@property(readonly, nonatomic) DVTFileDataType *navigableItem_documentType;
@property(readonly, nonatomic) IDEFileReference *navigableItem_fileReference;
@property(readonly, nonatomic) NSNull *navigableItem_filtered;
@property(readonly, nonatomic) NSString *navigableItem_groupIdentifier;
@property(readonly, nonatomic) NSImage *navigableItem_image;
@property(readonly, nonatomic) BOOL navigableItem_isEnabled;
@property(readonly, nonatomic) BOOL navigableItem_isLeaf;
@property(readonly, nonatomic) BOOL navigableItem_isMajorGroup;
@property(readonly, nonatomic) BOOL navigableItem_isVisible;
@property(readonly, nonatomic) BOOL navigableItem_missingReferencedContentIsImportant;
@property(readonly, nonatomic) id navigableItem_parentRepresentedObject;
@property(readonly, nonatomic) BOOL navigableItem_referencedContentExists;
@property(readonly, nonatomic) _TtC13DVTFoundation9DVTSymbol *navigableItem_representedSymbol;
@property(readonly, nonatomic) NSURL *navigableItem_representedURL;
@property(readonly, nonatomic) NSString *navigableItem_subtitle;
@property(readonly, nonatomic) NSString *navigableItem_toolTip;
@property(readonly) Class superclass;

@end

