//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IDEKeyBinding, NSArray, NSMutableArray, NSString;

@interface IDEKeyBindingItem : NSObject
{
    NSString *_title;
    IDEKeyBinding *_keyBinding;
    NSMutableArray *_childItems;
}

- (void).cxx_destruct;
@property(readonly) IDEKeyBinding *keyBinding; // @synthesize keyBinding=_keyBinding;
@property(copy) NSString *title; // @synthesize title=_title;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (void)removeObjectFromChildItemsAtIndex:(unsigned long long)arg1;
- (void)insertObject:(id)arg1 inChildItemsAtIndex:(unsigned long long)arg2;
- (id)_childItems;
@property(readonly, copy) NSMutableArray *mutableChildItems;
@property(readonly, copy) NSArray *childItems; // @synthesize childItems=_childItems;
- (void)setChildItems:(id)arg1;
@property(readonly) NSString *toolTip;
@property(readonly) BOOL isGroupedAlternate;
@property(readonly) BOOL isAlternate;
- (id)initWithTitle:(id)arg1 keyBinding:(id)arg2 childItems:(id)arg3;

@end

