//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDESearchWindowController.h>

#import <IDEKit/DVTLibraryControllerDelegate-Protocol.h>
#import <IDEKit/IDELibraryControllerContainerViewDelegate-Protocol.h>
#import <IDEKit/NSWindowDelegate-Protocol.h>

@class DVTDelayedInvocation, DVTLibraryController, IDELibraryControllerContainerView, IDESearchWindowContentPlaceholder, IDEWorkspaceTabController, NSButton, NSCountedSet, NSDate, NSMutableDictionary, NSMutableSet, NSString, _TtC13DVTLibraryKit27LibraryBannerViewController;
@protocol DVTCancellable, DVTInvalidation;

@interface IDELibraryWindowController : IDESearchWindowController <NSWindowDelegate, DVTLibraryControllerDelegate, IDELibraryControllerContainerViewDelegate>
{
    NSString *_selectedExtensionID;
    id <DVTInvalidation> _windowOrderChangingNotifications;
    DVTDelayedInvocation *_libraryAreaContentProvidingTabControllerValidator;
    NSMutableSet *_workspaceTabControllers;
    NSCountedSet *_workspaceDocumentRegistrations;
    IDEWorkspaceTabController *_contentProvidingTabController;
    BOOL _wasPinnedAtBeginingOfDrag;
    id <DVTCancellable> _displayedLibraryControllerOverridingAppearanceDidChangeToken;
    IDELibraryControllerContainerView *_libraryControllerContainerView;
    _TtC13DVTLibraryKit27LibraryBannerViewController *_bannerView;
    IDESearchWindowContentPlaceholder *_placeholderDetailView;
    NSButton *_assetViewStyleButton;
    NSButton *_detailDisplayButton;
    BOOL _showingDetails;
    BOOL _transitioningDetails;
    NSString *_filterString;
    NSDate *_filterExpiration;
    NSMutableDictionary *_assetViewStyles;
    DVTLibraryController *_displayedLibraryController;
}

+ (id)libraryExtensionWithID:(id)arg1;
+ (id)libraryIDsForWorkspaceTabController:(id)arg1 selectedExtensionID:(id *)arg2;
+ (void)setLastSelectedLibraryExtensionIDByEditorID:(id)arg1;
+ (id)lastSelectedLibraryExtensionIDByEditorID;
+ (id)sharedInstance;
+ (void)initialize;
- (void).cxx_destruct;
@property(readonly) DVTLibraryController *displayedLibraryController; // @synthesize displayedLibraryController=_displayedLibraryController;
- (BOOL)performKeyEquivalent:(id)arg1;
- (void)selectNextTab:(id)arg1;
- (void)selectPreviousTab:(id)arg1;
- (void)selectNextLibraryInDirection:(long long)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (BOOL)control:(id)arg1 textView:(id)arg2 doCommandBySelector:(SEL)arg3;
- (BOOL)validateUserInterfaceItem:(id)arg1 forWorkspaceTabController:(id)arg2;
- (void)libraryController:(id)arg1 didUpdateProgress:(long long)arg2;
- (void)libraryController:(id)arg1 didFinishDraggingAssets:(id)arg2;
- (void)libraryController:(id)arg1 didContinueDraggingAssets:(id)arg2;
- (void)libraryController:(id)arg1 didBeginDraggingAssets:(id)arg2 withMouseDown:(id)arg3;
- (void)libraryController:(id)arg1 didDepositAssets:(id)arg2 withEvent:(id)arg3;
- (void)libraryController:(id)arg1 didSelectAssets:(id)arg2;
- (void)libraryController:(id)arg1 didUpdateIsShowingPlaceholder:(BOOL)arg2;
- (void)libraryController:(id)arg1 didChangeError:(id)arg2;
- (void)updateBannerView;
- (void)updateBannerLayout;
- (void)libraryControllerDidCancel:(id)arg1;
- (BOOL)libraryControllerShouldSlideBackFailedDrags:(id)arg1;
- (id)searchFieldIcon;
- (void)toggleAssetDisplayStyle:(id)arg1;
- (void)setShowingDetails:(BOOL)arg1 animate:(BOOL)arg2;
- (void)toggleDetailVisibility:(id)arg1;
- (void)libraryController:(id)arg1 didChangeAssetViewStyle:(long long)arg2;
- (void)updateAccessoryButtonTooltip;
- (void)updateDetailAreaTooltip;
- (void)libraryControllerContainerView:(id)arg1 userDidSelectChoice:(id)arg2;
- (void)openSelectedContent;
- (long long)minimumInstantQueryLength;
- (double)minimumContentHeight;
- (double)minimumWidth;
- (double)defaultContentHeight;
- (BOOL)isVerticallyResizable;
- (void)makeWindowVisible:(BOOL)arg1;
- (void)windowDidLoad;
- (void)showLibrary:(id)arg1 pin:(BOOL)arg2 showDetails:(id)arg3;
- (void)showLibrary:(id)arg1 pin:(BOOL)arg2;
- (void)refreshSourceWorkspaceTabController:(id)arg1;
- (void)refreshAndConditionallyOpen:(BOOL)arg1;
- (void)refreshDetailView;
- (id)iconForLibraryWithID:(id)arg1 suffix:(id)arg2;
- (id)titleForLibraryWithID:(id)arg1;
- (id)inferSourceWorkspaceTabController;
- (struct CGRect)windowWillUseStandardFrame:(id)arg1 defaultFrame:(struct CGRect)arg2;
- (id)userDefaultsBaseName;
- (void)updateSearchWithText:(id)arg1;
- (BOOL)supportsVibrantContent;
- (void)windowWillClose:(id)arg1;
- (void)detachWindowContent;
- (id)libraryControllerForWorkspaceDocument:(id)arg1 extensionID:(id)arg2;
- (id)registerWorkspaceTabController:(id)arg1;
- (void)toggleLibraryFromButton:(id)arg1 preferingLibrary:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

