//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTKit/DVTToolbarViewController.h>

#import <IDEKit/DVTDelayedMenuButtonDelegate-Protocol.h>

@class IDELibraryToolbarButton, IDEWorkspaceWindowController, NSMenuItem, NSString;
@protocol DVTCancellable;

@interface IDELibraryToolbarViewController : DVTToolbarViewController <DVTDelayedMenuButtonDelegate>
{
    IDEWorkspaceWindowController *_windowController;
    IDELibraryToolbarButton *_button;
    id <DVTCancellable> _activeEditorObservation;
    NSMenuItem *_showPrimaryMenuItem;
    NSMenuItem *_openPrimaryMenuItem;
}

- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (void)synchronizeButton;
- (id)workspaceTabController;
- (void)delayedMenuButton:(id)arg1 sendClickAction:(SEL)arg2 to:(id)arg3 from:(id)arg4;
- (id)delayedMenuButton:(id)arg1 willSetCurrentMenuItem:(id)arg2;
- (id)initWithToolbarItemIdentifier:(id)arg1 window:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

