//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/NSObject-Protocol.h>

@class DVTDocumentLocation, IDELogViewController, NSArray;

@protocol IDELogViewControllerDelegate <NSObject>
- (void)logViewController:(IDELogViewController *)arg1 selectedIndexPathsDidChange:(NSArray *)arg2;
- (DVTDocumentLocation *)logViewController:(IDELogViewController *)arg1 replacementDocumentLocationForOriginalDocumentLocation:(DVTDocumentLocation *)arg2;
@end

