//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class DVTLicenseAgreementHelper, NSAttributedString, NSTextField, NSTextView, NSView;

@interface IDELicenseAgreementViewController : NSViewController
{
    DVTLicenseAgreementHelper *_licenseAgreementHelper;
    int _agreementStatus;
    NSAttributedString *_licenseAgreement;
    NSTextView *_licenseAgreementTextView;
    NSView *_foregroundContentView;
    BOOL _licenseOnly;
    NSTextField *_licenseSubtitle;
}

+ (void)initialize;
- (void).cxx_destruct;
@property __weak NSTextField *licenseSubtitle; // @synthesize licenseSubtitle=_licenseSubtitle;
@property(retain) NSView *foregroundContentView; // @synthesize foregroundContentView=_foregroundContentView;
@property int agreementStatus; // @synthesize agreementStatus=_agreementStatus;
- (BOOL)_agreeToLicense;
- (void)agreeToLicense:(id)arg1;
- (void)disagreeWithLicense:(id)arg1;
- (void)_writeLicenseTextToURL:(id)arg1;
- (id)_licenseSavePanel;
- (void)save:(id)arg1;
- (BOOL)isGMLicense;
- (BOOL)shouldShowLicenseAgreement;
- (void)loadView;
- (id)initWithDefaultNib:(BOOL)arg1;

@end

