//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEKit/DVTTextCompletionItem-Protocol.h>

@class DVTRangeArray, DVTSourceCodeLanguage, NSArray, NSAttributedString, NSImage, NSString;

@interface IDEMediaResourceCompletionItem : NSObject <DVTTextCompletionItem>
{
    NSImage *_cachedIcon;
    NSString *name;
    NSString *displayText;
    NSString *displayType;
    NSString *briefDisplayText;
    NSString *displaySignature;
    NSString *completionText;
    NSAttributedString *descriptionText;
    CDUnknownBlockType iconProvidingMainThreadBlock;
    double priority;
    double fuzzyMatchingScore;
    DVTRangeArray *fuzzyMatchingRanges;
}

- (void).cxx_destruct;
@property(retain) DVTRangeArray *fuzzyMatchingRanges; // @synthesize fuzzyMatchingRanges;
@property double fuzzyMatchingScore; // @synthesize fuzzyMatchingScore;
@property double priority; // @synthesize priority;
@property(copy) CDUnknownBlockType iconProvidingMainThreadBlock; // @synthesize iconProvidingMainThreadBlock;
@property(copy) NSAttributedString *descriptionText; // @synthesize descriptionText;
@property(copy) NSString *completionText; // @synthesize completionText;
@property(copy) NSString *displaySignature; // @synthesize displaySignature;
@property(copy) NSString *briefDisplayText; // @synthesize briefDisplayText;
@property(copy) NSString *displayType; // @synthesize displayType;
@property(copy) NSString *displayText; // @synthesize displayText;
@property(copy, nonatomic) NSString *name; // @synthesize name;
@property(readonly, copy) NSString *accessibilityLabel;
@property(readonly) BOOL notRecommended;
@property(readonly) unsigned long long priorityComparatorKind;
@property(readonly) long long priorityBucket;
@property(retain) NSImage *icon; // @synthesize icon=_cachedIcon;
@property(readonly, copy) NSString *parentText;

// Remaining properties
@property(readonly, copy) NSString *action;
@property(readonly, copy) NSArray *additionalCompletions;
@property(readonly, copy) NSAttributedString *attributedDisplaySignature;
@property(readonly, copy) NSAttributedString *attributedDisplayType;
@property(readonly, copy) DVTRangeArray *briefDisplayTextRanges;
@property(readonly) int completionItemStyle;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, copy) DVTRangeArray *displayTextRanges;
@property(readonly) unsigned long long hash;
@property(readonly) NSImage *highlightedStatusIcon;
@property(readonly) DVTSourceCodeLanguage *language;
@property(readonly, copy) DVTRangeArray *nameRanges;
@property(readonly) NSImage *statusIcon;
@property(readonly) Class superclass;
@property(readonly) NSString *usr;

@end

