//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  6 2019 20:12:56).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTKit/DVTLayerHostingView.h>

#import <IDEKit/CALayoutManager-Protocol.h>
#import <IDEKit/DVTInvalidation-Protocol.h>

@class CALayer, CAScrollLayer, DVTDelayedInvocation, DVTImageAndTextLayer, DVTStackBacktrace, NSArray, NSMapTable, NSString;
@protocol IDENavigationHUDSelectionViewDelegate;

@interface IDENavigationHUDSelectionView : DVTLayerHostingView <CALayoutManager, DVTInvalidation>
{
    id <IDENavigationHUDSelectionViewDelegate> _delegate;
    DVTDelayedInvocation *_fileProxyInvocation;
    DVTDelayedInvocation *_coverFlowInvocation;
    DVTDelayedInvocation *_textAreaInvocation;
    BOOL _setUp;
    DVTImageAndTextLayer *_fileProxyLayer;
    DVTImageAndTextLayer *_textLayer;
    CALayer *_contentLayer;
    NSMapTable *_wrappingLayerToRealLayerMap;
    NSMapTable *_realLayerToWrappingLayerMap;
    unsigned long long _selectedCoverFlowLayerIndex;
    CAScrollLayer *_coverFlowScrollLayer;
    NSArray *_coverFlowLayers;
}

+ (id)keyPathsForValuesAffectingSelectedCoverFlowLayer;
+ (void)initialize;
@property(nonatomic) unsigned long long selectedCoverFlowLayerIndex; // @synthesize selectedCoverFlowLayerIndex=_selectedCoverFlowLayerIndex;
@property(retain, nonatomic) id <IDENavigationHUDSelectionViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)accessibilityChildren;
- (id)accessibilityTitle;
- (id)accessibilityRole;
- (BOOL)isAccessibilityElement;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)layoutSublayersOfLayer:(id)arg1;
- (void)removeCoverFlowLayer:(id)arg1;
- (void)addCoverFlowLayer:(id)arg1;
- (id)wrappingLayerForLayerCreatingIfNecessary:(id)arg1;
- (id)realLayerForWrappingLayer:(id)arg1;
- (id)existingWrappingLayerForLayer:(id)arg1;
- (void)setCoverFlowNeedsLayout;
- (void)refreshTextArea;
- (void)refreshCoverFlow;
- (void)refreshFileProxy;
- (void)invalidateTextArea;
- (void)invalidateCoverFlow;
- (void)invalidateFileProxy;
- (BOOL)requireOptimumPerformance;
@property(retain) CALayer *selectedCoverFlowLayer;
@property(readonly) struct CGSize fileProxyImageSize;
- (void)primitiveInvalidate;
- (void)viewDidMoveToWindow;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (void)selectionViewCommonInit;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

