//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDETokenFilterControlBar.h>

@class IDENavigator;

@interface IDENavigatorTokenFilterControlBar : IDETokenFilterControlBar
{
}

@property(retain) IDENavigator *navigator;
- (void)setFilterTarget:(id)arg1;
- (void)_didSetFilterTarget;
- (void)_willSetFilterTarget;

@end

