//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@class IDENavigationHUDController;

@interface IDENavigationHUDWindowController : NSWindowController
{
    CDUnknownBlockType _originalCompletionBlock;
    IDENavigationHUDController *_navigationHUDController;
    id _notificationTokenWillResignActive;
    id _notificationTokenWillHide;
}

@property(readonly) IDENavigationHUDController *navigationHUDController; // @synthesize navigationHUDController=_navigationHUDController;
- (void).cxx_destruct;
- (void)close;
- (void)showWithEvent:(id)arg1;
- (BOOL)shouldShowAtLocationOfEvent:(id)arg1;
- (void)stopListeningForClosure;
- (void)startListeningForClosure;
- (void)closeWithHUDController:(id)arg1 selection:(id)arg2 animate:(BOOL)arg3;
- (void)loadWindow;
- (id)windowNibName;
- (id)initWithInitialSelection:(id)arg1 options:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)initWithURL:(id)arg1 initialSelection:(id)arg2 options:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (id)initWithNavigationHUDController:(id)arg1;

@end

