//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTExtension, MISSING_TYPE, NSArray, NSImage, NSString;

@interface IDENavigatorGroup : NSObject
{
    MISSING_TYPE *identifier;
    MISSING_TYPE *enabledInPlaygrounds;
    MISSING_TYPE *preferredPosition;
    MISSING_TYPE *menuCommandIdentifier;
    MISSING_TYPE *imageName;
    MISSING_TYPE *selectedImageName;
    MISSING_TYPE *title;
    MISSING_TYPE *toolTip;
    MISSING_TYPE *bundle;
    MISSING_TYPE *displayOrderedEntries;
}

+ (id)displayOrderedPlaygroundGroups;
+ (id)displayOrderedWorkspaceGroups;
+ (BOOL)allowNavigatorVariants;
- (void).cxx_destruct;
- (id)init;
- (id)navigatorWithIdentifier:(id)arg1;
@property(nonatomic, readonly) DVTExtension *initialNavigator;
@property(nonatomic, readonly) NSImage *selectedImage;
@property(nonatomic, readonly) NSImage *image;
@property(nonatomic, readonly) BOOL hasSingleTopLevelAlternate;
@property(nonatomic, readonly) NSArray *allNavigators;
@property(nonatomic, readonly) NSArray *primaryNavigators;
@property(nonatomic, readonly) DVTExtension *singleTopLevelAlternatePairAlternative;
@property(nonatomic, readonly) DVTExtension *singleTopLevelAlternatePairPrimary;
- (id)initWithExtension:(id)arg1;
@property(nonatomic, readonly) NSString *toolTip;
@property(nonatomic, readonly) NSString *title;
@property(nonatomic, readonly) NSString *selectedImageName;
@property(nonatomic, readonly) NSString *imageName;
@property(nonatomic, readonly) NSString *menuCommandIdentifier;
@property(nonatomic, readonly) double preferredPosition; // @synthesize preferredPosition;
@property(nonatomic, readonly) BOOL enabledInPlaygrounds; // @synthesize enabledInPlaygrounds;
@property(nonatomic, readonly) NSString *identifier;

@end

