//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEAssistant.h>

@class DVTBorderedView, NSTextView;

@interface IDEObjCModernizationOverviewAssistant : IDEAssistant
{
    NSTextView *_textView;
    DVTBorderedView *_borderedView;
}

+ (id)keyPathsForValuesAffectingCanGoForward;
- (void).cxx_destruct;
- (void)loadView;
- (id)_messageContentsURL;
- (BOOL)canGoForward;
- (id)nextAssistantIdentifier;

@end

