//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@interface IDEOpenQuicklyRowViewIndentIndicatorView : NSView
{
    long long _backgroundStyle;
}

@property(nonatomic) long long backgroundStyle; // @synthesize backgroundStyle=_backgroundStyle;
- (void)drawRect:(struct CGRect)arg1;
- (id)effectiveIndentBackgroundColor;
- (id)effectiveIndentSeparatorColor;

@end

