//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEMigrationAssistantContext.h>

@class NSArray, NSMapTable, NSMutableArray;

@interface IDEObjCModernizationAssistantContext : IDEMigrationAssistantContext
{
    NSMutableArray *_targets;
    NSMutableArray *_selectedTargets;
    unsigned long long _currentConversionStage;
    NSMapTable *_convertedFilePathForOriginalFilePathMapTable;
    NSMutableArray *_modernizerBuildOptions;
}

+ (Class)migrationContextClass;
+ (void)initialize;
- (void).cxx_destruct;
@property(copy) NSArray *targets; // @synthesize targets=_targets;
@property unsigned long long currentConversionStage; // @synthesize currentConversionStage=_currentConversionStage;
- (id)convertedFilePathForOriginalFilePath:(id)arg1;
- (unsigned long long)numberOfConvertedFilePaths;
- (id)_convertedFilePathForOriginalFilePathMapTable;
- (void)setWorkspaceTabController:(id)arg1;
- (id)buildActionEntries;
- (id)runPhase;
- (id)runContext;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

// Remaining properties
@property(copy) NSArray *modernizerBuildOptions; // @dynamic modernizerBuildOptions;
@property(readonly, copy) NSMutableArray *mutableModernizerBuildOptions; // @dynamic mutableModernizerBuildOptions;
@property(readonly, copy) NSMutableArray *mutableSelectedTargets; // @dynamic mutableSelectedTargets;
@property(copy) NSArray *selectedTargets; // @dynamic selectedTargets;

@end

