//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  6 2019 20:12:56).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDEViewController.h>

#import <IDEKit/DVTReplacementViewDelegate-Protocol.h>
#import <IDEKit/IDEProvisioningProfileDownloaderSourceListViewControllerDelegate-Protocol.h>

@class DVTObservingToken, DVTReplacementView, IDEProvisioningCompoundProfile, IDEProvisioningProfileDownloader, NSString;
@protocol IDEProvisioningProfileDownloaderDetailContainerViewControllerDelegate;

@interface IDEProvisioningProfileDownloaderDetailContainerViewController : IDEViewController <IDEProvisioningProfileDownloaderSourceListViewControllerDelegate, DVTReplacementViewDelegate>
{
    IDEProvisioningProfileDownloader *_downloader;
    DVTReplacementView *_replacementView;
    IDEProvisioningCompoundProfile *_compoundProfile;
    DVTObservingToken *_compoundProfileStateObserver;
    DVTObservingToken *_compoundProfileIsLocalProfileOutdatedObserver;
    id <IDEProvisioningProfileDownloaderDetailContainerViewControllerDelegate> _delegate;
    CDUnknownBlockType _updateReplacementViewBlock;
}

@property(copy, nonatomic) CDUnknownBlockType updateReplacementViewBlock; // @synthesize updateReplacementViewBlock=_updateReplacementViewBlock;
@property(retain, nonatomic) id <IDEProvisioningProfileDownloaderDetailContainerViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) DVTObservingToken *compoundProfileIsLocalProfileOutdatedObserver; // @synthesize compoundProfileIsLocalProfileOutdatedObserver=_compoundProfileIsLocalProfileOutdatedObserver;
@property(retain, nonatomic) DVTObservingToken *compoundProfileStateObserver; // @synthesize compoundProfileStateObserver=_compoundProfileStateObserver;
@property(retain, nonatomic) IDEProvisioningCompoundProfile *compoundProfile; // @synthesize compoundProfile=_compoundProfile;
@property __weak DVTReplacementView *replacementView; // @synthesize replacementView=_replacementView;
@property(retain, nonatomic) IDEProvisioningProfileDownloader *downloader; // @synthesize downloader=_downloader;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (void)replacementView:(id)arg1 willInstallViewController:(id)arg2;
- (void)didSelectProfile:(id)arg1;
- (void)updateEmptyContentViewWithTitle:(id)arg1 subtitle:(id)arg2 buttonTitle:(id)arg3 resolutionBlock:(CDUnknownBlockType)arg4;
- (void)updateEmptyContentViewWithDownloadPreviewError;
- (void)updateEmptyContentViewWithBusyState;
- (void)updateDetailViewWithSelectedProfile;
- (void)updateReplacementViewForStateChange;
- (void)setupObservations;
- (void)viewDidLoad;
- (id)initWithDownloader:(id)arg1 delegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

