//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSPathControl.h>

#import <IDEKit/DVTInvalidation-Protocol.h>

@class DVTStackBacktrace, NSString;

@interface IDEPathControl : NSPathControl <DVTInvalidation>
{
    NSString *_menuDefinitionIdentifier;
}

+ (double)iconTitleSpacing;
+ (struct CGSize)iconSize;
+ (Class)cellClass;
+ (unsigned long long)defaultFocusRingType;
+ (void)initialize;
- (void).cxx_destruct;
@property(copy) NSString *menuDefinitionIdentifier; // @synthesize menuDefinitionIdentifier=_menuDefinitionIdentifier;
- (id)accessibilityPopUpMenuParent:(id)arg1;
@property(readonly) struct CGSize sizeWanted;
- (void)viewWillMoveToWindow:(id)arg1;
- (void)popUpMenuForComponentCell:(id)arg1;
- (void)_popUpMenuForComponentCell:(id)arg1;
- (void)rightMouseDown:(id)arg1;
- (id)menuForEvent:(id)arg1;
@property(readonly) struct CGRect grabRect;
- (void)setFont:(id)arg1;
@property BOOL lastComponentFillsWidth;
@property int gradientStyle;
- (void)primitiveInvalidate;
- (id)outputSelection;
- (void)updateBoundContent;
- (void)updateBoundSelectedItem;
- (void)setDelegate:(id)arg1;
- (id)dvt_extraBindings;
- (void)setCell:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

