//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTUserInterfaceKit/DVTPopoverContentViewController.h>

@class IDEProfileQualification, IDEProvisioningProfileInfoViewController;

@interface IDEProvisioningProfileInfoPopoverViewController : DVTPopoverContentViewController
{
    IDEProfileQualification *_qualification;
    IDEProvisioningProfileInfoViewController *_infoViewController;
}

- (void).cxx_destruct;
@property(retain, nonatomic) IDEProvisioningProfileInfoViewController *infoViewController; // @synthesize infoViewController=_infoViewController;
@property(retain, nonatomic) IDEProfileQualification *qualification; // @synthesize qualification=_qualification;
- (void)primitiveInvalidate;
- (void)viewDidLoad;
- (id)initWithQualification:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

