//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/NSObject-Protocol.h>

@class DVTDocumentLocation, IDEComparisonEditor, IDEReviewFilesViewController;

@protocol IDEReviewFilesViewControllerDelegate <NSObject>

@optional
- (BOOL)shouldUpdateEditorHistory;
- (void)reviewFilesViewController:(IDEReviewFilesViewController *)arg1 didInstallComparisonEditor:(IDEComparisonEditor *)arg2;
- (void)willOpenDocumentLocation:(DVTDocumentLocation *)arg1 completionBlock:(void (^)(IDEEditorOpenSpecifier *, NSError *))arg2;
- (BOOL)enableDiffToggles;
@end

