//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@class IDEWorkspaceWindowController, NSTextField;

@interface IDERenameCurrentTabController : NSWindowController
{
    IDEWorkspaceWindowController *_workspaceWindowController;
    NSTextField *_nameTextField;
}

+ (void)renameWorkspaceWindowController:(id)arg1;
- (void).cxx_destruct;
@property(retain) NSTextField *nameTextField; // @synthesize nameTextField=_nameTextField;
@property(retain) IDEWorkspaceWindowController *workspaceWindowController; // @synthesize workspaceWindowController=_workspaceWindowController;
- (void)rename:(id)arg1;
- (void)cancel:(id)arg1;
- (void)loadWindow;

@end

