//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEKit/DVTInvalidation-Protocol.h>

@class DVTStackBacktrace, NSArray, NSMutableArray, NSString;

@interface IDERecentsHelper : NSObject <DVTInvalidation>
{
    NSArray *_recentDocumentInfos;
    NSMutableArray *_watchedFiledPaths;
    CDUnknownBlockType _preUpdateCallback;
    CDUnknownBlockType _postUpdateCallback;
}

+ (BOOL)isProjectFileDataType:(id)arg1;
+ (void)initialize;
@property(copy) CDUnknownBlockType postUpdateCallback; // @synthesize postUpdateCallback=_postUpdateCallback;
@property(copy) CDUnknownBlockType preUpdateCallback; // @synthesize preUpdateCallback=_preUpdateCallback;
@property(retain) NSMutableArray *watchedFiledPaths; // @synthesize watchedFiledPaths=_watchedFiledPaths;
@property(retain) NSArray *recentDocumentInfos; // @synthesize recentDocumentInfos=_recentDocumentInfos;
- (void).cxx_destruct;
- (void)_updateRecentProjectsDoAsync:(BOOL)arg1;
- (id)_processURLsFromRecentInfoArray:(id)arg1;
- (void)_updateRecentProjects;
- (id)initWithPreUpdateCallback:(CDUnknownBlockType)arg1 postUpdateCallback:(CDUnknownBlockType)arg2;
- (void)primitiveInvalidate;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

