//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  6 2019 20:12:56).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDEKeyDrivenNavigableItem.h>

@class IDESourceControlTreeItem, NSError, NSMutableArray;

@interface IDESourceControlBranchNavigableItem : IDEKeyDrivenNavigableItem
{
    NSMutableArray *_computedChildItems;
    NSError *_error;
    IDESourceControlTreeItem *_treeItem;
}

@property(retain) IDESourceControlTreeItem *treeItem; // @synthesize treeItem=_treeItem;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (void)_childRepresentedObjects:(CDUnknownBlockType)arg1;
- (id)childRepresentedObjects;
- (void)idesc_setChildRepresentedObjects:(id)arg1;
- (BOOL)isLeaf;

@end

