//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/DVTInvalidation-Protocol.h>
#import <IDEKit/IDETemplateSupportingNavigator-Protocol.h>

@class IDEContainerItem, IDEStructureNavigatorMenuActionHandler, IDEViewController, NSArray;
@protocol IDEStructureEditingItem;

@protocol IDEStructureNavigatorMenuActionHandlerDelegate <IDETemplateSupportingNavigator, DVTInvalidation>
- (id <IDEStructureEditingItem>)firstTopLevelContainerItem;
- (NSArray *)menuActionHandler:(IDEStructureNavigatorMenuActionHandler *)arg1 sortableSelectedItemsUsingContextualMenuSelection:(BOOL)arg2;
- (NSArray *)menuActionHandler:(IDEStructureNavigatorMenuActionHandler *)arg1 groupableSelectedItemsUsingContextualMenuSelection:(BOOL)arg2;
- (NSArray *)menuActionHandler:(IDEStructureNavigatorMenuActionHandler *)arg1 removableSelectedItemsUsingContextualMenuSelection:(BOOL)arg2;
- (BOOL)menuActionHandler:(IDEStructureNavigatorMenuActionHandler *)arg1 performUsingContextualMenuSelection:(BOOL)arg2 block:(BOOL (^)(id <IDEStructureEditingItem>, BOOL))arg3;
- (IDEContainerItem *)menuActionHandler:(IDEStructureNavigatorMenuActionHandler *)arg1 selectedContainerItemUsingContextualSelection:(BOOL)arg2 useFirstIndex:(BOOL)arg3 selectionWasExplicitlyRejected:(char *)arg4;
@property(nonatomic, readonly) IDEViewController *viewController;
@end

