//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEFoundation/IDEAlert.h>

@class NSString;

@interface IDEShowDebuggerAlert : IDEAlert
{
    BOOL _finalOutputDelayed;
    int _action;
    int _visibility;
    NSString *_destination;
}

- (void).cxx_destruct;
@property(nonatomic) int visibility; // @synthesize visibility=_visibility;
@property(nonatomic) int action; // @synthesize action=_action;
@property(retain, nonatomic) NSString *destination; // @synthesize destination=_destination;
- (BOOL)finalOutputDelayed;
- (void)setFinalOutputDelayed:(BOOL)arg1;
- (int)alertPropertyListVersion;
- (void)runForEvent:(id)arg1 inWorkspace:(id)arg2 context:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (void)_runForRunGeneratesOutputEventInWorkspace:(id)arg1 context:(id)arg2 showIfOutput:(long long)arg3 hideIfNoOutput:(long long)arg4;
- (void)_configureDebugAreaInWorkspaceTabController:(id)arg1;
- (void)_resetActionToExternal;
- (id)initWithPropertyList:(id)arg1;
- (id)propertyList;
- (id)valuesForProperty:(id)arg1;
- (id)visibilities;
- (id)actions;
- (id)destinations;
- (id)init;

@end

