//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface IDESpecialPasteboardHandler : NSObject
{
    NSString *_outputPasteboardType;
    NSDictionary *_context;
}

- (void).cxx_destruct;
@property(readonly) NSDictionary *context; // @synthesize context=_context;
@property(readonly) NSString *outputPasteboardType; // @synthesize outputPasteboardType=_outputPasteboardType;
- (id)specialPasteMenuItemTitleFromPasteboard:(id)arg1;
- (id)specialPasteboardDataFromPasteboard:(id)arg1 error:(id *)arg2;
- (id)initWithOutputPasteboardType:(id)arg1 context:(id)arg2;
- (id)init;

@end

