//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class DVTFilePath, NSArray, NSString;

@protocol IDESourcePackage
@property(readonly) NSArray *packageProducts;
@property(readonly) BOOL isRemotePackage;
@property(readonly) BOOL isRootPackage;
@property(readonly) NSString *packageVersion;
@property(readonly) NSString *packageName;
@property(readonly) DVTFilePath *packagePath;
@property(readonly) NSString *packageURL;
@end

