//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSSegmentedControl.h>

#import <IDEKit/IDESchemeToolbarUpdateConstraintsCallbackProvider-Protocol.h>

@class NSString;

@interface IDESchemeToolbarSegmentedControlView : NSSegmentedControl <IDESchemeToolbarUpdateConstraintsCallbackProvider>
{
    CDUnknownBlockType _updateConstraintsBlock;
}

+ (BOOL)accessibilityIsSingleCelled;
- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType updateConstraintsBlock; // @synthesize updateConstraintsBlock=_updateConstraintsBlock;
- (void)updateConstraints;
- (BOOL)accessibilityIsIgnored;
- (id)accessibilityRoleAttribute;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

