//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  6 2019 20:12:56).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/NSObject-Protocol.h>

@class NSDate, NSString;

@protocol IDETest_ActivityAttachment_Base <NSObject>
@property(readonly, copy, nonatomic) NSString *ide_test_activity_attachment_base_title;
@property(readonly, copy, nonatomic) NSDate *sortingTimestamp;
@end

