//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  6 2019 20:12:56).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/NSObject-Protocol.h>

@class NSString, NSURL;

@protocol IDETestReport_RemoteAsset <NSObject>
@property(readonly, nonatomic) unsigned long long ide_testReport_remoteAsset_size;
@property(readonly, copy, nonatomic) NSURL *ide_testReport_remoteAsset_downloadURL;
@property(readonly, copy, nonatomic) NSString *ide_testReport_remoteAsset_fileName;
@end

