//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSColor;

@protocol IDEToyHostingView
@property(nonatomic) BOOL hasRoundedCorners;
@property(retain, nonatomic) NSColor *selectedBorderColor;
@property(retain, nonatomic) NSColor *backgroundColor;
@property(copy) CDUnknownBlockType rightMouseDownHandler;
@property(copy) CDUnknownBlockType mouseDownHandler;
@property(copy) CDUnknownBlockType mouseTrackingHandler;
@property(nonatomic) BOOL toyIsHighlighted;
@property(nonatomic) BOOL toyIsSelected;
@end

