//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDEAssistantContext.h>

@class IDETemplateInstantiationContext, IDEWorkspaceDocument, NSArray;

@interface IDETemplateAssistantContext : IDEAssistantContext
{
    BOOL _alwaysShowProjectNavigator;
    BOOL _skipFileChooser;
    IDETemplateInstantiationContext *_instantiationContext;
    IDEWorkspaceDocument *_createdDocument;
}

@property BOOL skipFileChooser; // @synthesize skipFileChooser=_skipFileChooser;
@property(readonly) BOOL alwaysShowProjectNavigator; // @synthesize alwaysShowProjectNavigator=_alwaysShowProjectNavigator;
@property(retain) IDEWorkspaceDocument *createdDocument; // @synthesize createdDocument=_createdDocument;
@property(retain, nonatomic) IDETemplateInstantiationContext *instantiationContext; // @synthesize instantiationContext=_instantiationContext;
- (void).cxx_destruct;
- (void)_asyncFinishTemplateInstantiationAfterCreatingWorkspaceDocumentWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)asyncFinishTemplateInstantiationWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)setWorkspaceTabController:(id)arg1;
@property(readonly, copy) NSArray *targetWorkspaces;
- (struct CGSize)windowSize;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

