//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSCollectionView.h>

@protocol IDETemplateChooserCollectionViewDelegate;

@interface IDETemplateChooserCollectionView : NSCollectionView
{
    BOOL _dontSendSelectionIndexesChanges;
}

- (void)moveRight:(id)arg1;
- (void)moveLeft:(id)arg1;
- (void)moveDown:(id)arg1;
- (void)moveUp:(id)arg1;
- (BOOL)_ensureSelectionPreferringLastItem:(BOOL)arg1;
- (void)insertNewline:(id)arg1;
- (void)mouseDown:(id)arg1;
@property id <IDETemplateChooserCollectionViewDelegate> delegate;

@end

