//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  6 2019 20:12:56).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTStructuredLayoutKit/DVTLayoutView_ML.h>

@class NSView;

@interface IDEVerticalResizeToContentLayoutView : DVTLayoutView_ML
{
    double _topSpace;
    double _bottomSpace;
    NSView *_resizingContentView;
}

@property(retain, nonatomic) NSView *resizingContentView; // @synthesize resizingContentView=_resizingContentView;
@property(nonatomic) double bottomSpace; // @synthesize bottomSpace=_bottomSpace;
@property(nonatomic) double topSpace; // @synthesize topSpace=_topSpace;
- (void).cxx_destruct;
- (void)layoutBottomUp;

@end

