//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@interface IDEWelcomeWindowView : NSView
{
}

- (void)keyDown:(id)arg1;
- (void)_updateTransientControlVisibility;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)updateLayer;
- (BOOL)wantsUpdateLayer;

@end

