//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSDocument.h>

@interface NSDocument (IDENSDocumentAdditions)
- (void)ide_canCloseAsynchronouslyUsingBlock:(CDUnknownBlockType)arg1;
- (void)ideNSDocument:(id)arg1 shouldClose:(BOOL)arg2 contextInfo:(void *)arg3;
@end

