//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  6 2019 20:12:56).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import <IDEKit/_TtP6IDEKit26IDENavigationOverlayTarget_-Protocol.h>

@class NSString;

@interface NSViewController (IDEKit) <_TtP6IDEKit26IDENavigationOverlayTarget_>
@property(nonatomic, readonly) NSString *navigationOverlayTargetAccessibilityTitle;
@property(nonatomic, readonly) BOOL wantsHighlightEdgeAdornments;
@property(nonatomic, readonly) double highlightFrameBorderWidth;
@property(nonatomic, readonly) double highlightFrameCornerRadius;
- (struct CGRect)hitTestFrameInWindow:(id)arg1;
- (struct CGRect)highlightFrameInWindow:(id)arg1;
@end

