//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/AppKit.h>
#if 0
#import <IDEKit/IDETabbedWindow.h>

#import <IDEKit/NSKeyedArchiverDelegate-Protocol.h>
#endif

@class DVTObservingToken, NSString;

@interface IDEWorkspaceWindow : NSWindow // IDETabbedWindow <NSKeyedArchiverDelegate>
{
    DVTObservingToken* _workspaceFinishedLoadingObservingToken; // 256 = 0x100
    BOOL __isOverridingEscapeInsteadOfExitingFullscreen; // 264 = 0x108
}

+ (id)lastActiveWorkspaceWindowController;
//- (void).cxx_destruct;
- (BOOL)_addCursorRect:(struct CGRect)arg1 cursor:(id)arg2 forView:(id)arg3;
- (BOOL)_attemptToCloseAllTabs:(id)arg1;
- (void)_invalidateCursorRectsForView:(id)arg1 force:(BOOL)arg2;
- (void)_invalidateCursorRectsForViewsWithNoTrackingAreas;
@property BOOL
            _isOverridingEscapeInsteadOfExitingFullscreen; // @synthesize
                                                           // _isOverridingEscapeInsteadOfExitingFullscreen=__isOverridingEscapeInsteadOfExitingFullscreen;
- (BOOL)_keyViewRedirectionDisabled;
- (void)_setCursorForMouseLocation:(struct CGPoint)arg1;
- (void)becomeMainWindow;
- (BOOL)canBecomeKeyWindow;
- (BOOL)canBecomeMainWindow;
- (void)cancelOperation:(id)arg1;
- (void)close;
- (void)dvt_shouldDeallocate;
- (void)endSheet:(id)arg1 returnCode:(long long)arg2;
- (void)exitFullScreenMode:(id)arg1;
- (id)firstResponder;
- (void)recalculateKeyViewLoop;
- (void)renameCurrentTab:(id)arg1;
- (void)sendEvent:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setWindowController:(id)arg1;
- (void)toggleTabBar:(id)arg1;
- (void)toggleToolbarShown:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;

// Remaining properties
@property (readonly, copy) NSString* debugDescription;
@property (readonly, copy) NSString* description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

@end
