//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  6 2019 20:42:15).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTStackBacktrace, NSString;

@interface DVTNSImageDeallocTattleTale : NSObject
{
    DVTStackBacktrace *_creationBacktrace;
    NSString *_imageDescription;
}

@property(retain) NSString *imageDescription; // @synthesize imageDescription=_imageDescription;
@property(retain) DVTStackBacktrace *creationBacktrace; // @synthesize creationBacktrace=_creationBacktrace;
- (void).cxx_destruct;
- (void)dealloc;

@end

