//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@interface DVTPDFBlockCapturingView : NSView
{
    CDUnknownBlockType _drawingBlock;
}

- (void).cxx_destruct;
@property(copy) CDUnknownBlockType drawingBlock; // @synthesize drawingBlock=_drawingBlock;
- (void)drawRect:(struct CGRect)arg1;

@end

