//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  6 2019 20:42:15).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableView.h>

@class NSIndexSet;

@interface NSTableView (DVTNSTableViewAdditions)
@property(readonly) NSIndexSet *dvt_contextMenuSelectedRowIndexes;
@property(readonly) NSIndexSet *dvt_clickedRowIndexes;
- (void)dvt_scrollRowToVisibleCentered:(long long)arg1;
- (void)dvt_scrollRowToVisibleTop:(long long)arg1;
- (BOOL)dvt_autoscrollWithExternalDragEvent:(id)arg1 animate:(BOOL)arg2;
- (id)dvt_makeOrAllocateViewOfClass:(Class)arg1 withIdentifier:(id)arg2;
- (void)dvt_batchUpdatesDuring:(CDUnknownBlockType)arg1;
- (id)dvt_allIndexes;
@end

