//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  6 2019 20:42:15).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextField.h>

@interface NSTextField (DVTNSTextFieldAdditions)
- (id)dvt_linkAtPoint:(struct CGPoint)arg1;
- (void)dvt_selectAllText;
@end

