//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

__attribute__((visibility("hidden")))
@interface _TtCC12SourceEditorP33_5B634B9DCDB55D6100C0DC388A389C2738SourceEditorLineAnnotationDropdownItem42SourceEditorLineAnnotationDropdownItemView : NSView
{
}

- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (BOOL)isFlipped;

// Remaining properties
@property(nonatomic, readonly) BOOL flipped;

@end

