//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

__attribute__((visibility("hidden")))
@interface _TtC12SourceEditor28SourceEditorGutterMarginView : NSView
{
    // Error parsing type: , name: dividerLineLayer
    // Error parsing type: , name: dividerLineWidth
    // Error parsing type: , name: drawDividerLine
}

- (CDUnknownBlockType).cxx_destruct;
- (BOOL)isFlipped;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(nonatomic, readonly) BOOL flipped;

@end

