//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  6 2019 20:12:56).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <DVTFoundation/NSURLSessionDelegate-Protocol.h>

@class NSString, NSURLCredential;

@interface _DVTDeveloperPortalServiceConnectionSessionDelegate : NSObject <NSURLSessionDelegate>
{
    NSURLCredential *_credential;
}

@property(readonly, nonatomic) NSURLCredential *credential; // @synthesize credential=_credential;
- (void).cxx_destruct;
- (void)URLSession:(id)arg1 didReceiveChallenge:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)initWithCredential:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

