//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  6 2019 20:12:56).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTFoundation/DVTCodeSigningInformation.h>

@class DVTCodeSignatureValidity, NSNumber;

@interface _DVTCodeSigningInformation_PID : DVTCodeSigningInformation
{
    NSNumber *_appleSigned;
    DVTCodeSignatureValidity *_validity;
    int _processID;
}

+ (id)codeSigningDictionaryForProcessID:(int)arg1 additionalCSFlags:(unsigned int)arg2 error:(id *)arg3;
@property(readonly) int processID; // @synthesize processID=_processID;
- (void).cxx_destruct;
- (id)architecturesWithError:(id *)arg1;
- (id)validity;
- (id)codeSigningDictionaryWithAdditionalCSFlags:(unsigned int)arg1 architecture:(id)arg2 error:(id *)arg3;
- (BOOL)isAppleSigned;
- (id)initWithProcessID:(int)arg1 error:(id *)arg2;

@end

