//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol NSCopying;

@interface _TtC13DVTFoundation16DVTIconReference : NSObject
{
    // Error parsing type: , name: reference
}

- (void).cxx_destruct;
- (id)init;
- (BOOL)isEqual:(id)arg1;
@property(nonatomic, readonly) long long hash;
@property(nonatomic, readonly) id <NSCopying> resourceKey;
- (id)copyWithZone:(void *)arg1;

@end

