//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  6 2019 20:12:56).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC13DVTFoundation16DVTDeviceControl : NSObject
{
    // Error parsing type: , name: client
}

- (void).cxx_destruct;
- (id)init;
- (void)deviceShouldBeVisibleWithDevice:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (id)initWithServerPath:(id)arg1;

@end

