//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTFoundation/ACSURLSessionTaskDelegate-Protocol.h>

@class ACSURLSession, ACSURLSessionDataTask, ACSURLSessionDownloadTask, NSCachedURLResponse, NSData, NSURLResponse;

@protocol ACSURLSessionDataDelegate <ACSURLSessionTaskDelegate>

@optional
- (void)URLSession:(ACSURLSession *)arg1 dataTask:(ACSURLSessionDataTask *)arg2 willCacheResponse:(NSCachedURLResponse *)arg3 completionHandler:(void (^)(NSCachedURLResponse *))arg4;
- (void)URLSession:(ACSURLSession *)arg1 dataTask:(ACSURLSessionDataTask *)arg2 didReceiveData:(NSData *)arg3;
- (void)URLSession:(ACSURLSession *)arg1 dataTask:(ACSURLSessionDataTask *)arg2 didBecomeDownloadTask:(ACSURLSessionDownloadTask *)arg3;
- (void)URLSession:(ACSURLSession *)arg1 dataTask:(ACSURLSessionDataTask *)arg2 didReceiveResponse:(NSURLResponse *)arg3 completionHandler:(void (^)(long long))arg4;
@end

