//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTFoundation/ACSURLSessionDelegate-Protocol.h>

@class ACSURLSession, ACSURLSessionTask, NSError, NSHTTPURLResponse, NSURLAuthenticationChallenge, NSURLRequest, NSURLSessionTaskMetrics;

@protocol ACSURLSessionTaskDelegate <ACSURLSessionDelegate>

@optional
- (void)URLSession:(ACSURLSession *)arg1 task:(ACSURLSessionTask *)arg2 willUseCachingServer:(BOOL)arg3 newRequest:(NSURLRequest *)arg4 completionHandler:(void (^)(NSURLRequest *))arg5;
- (void)URLSession:(ACSURLSession *)arg1 task:(ACSURLSessionTask *)arg2 didCompleteWithError:(NSError *)arg3;
- (void)URLSession:(ACSURLSession *)arg1 task:(ACSURLSessionTask *)arg2 didFinishCollectingMetrics:(NSURLSessionTaskMetrics *)arg3;
- (void)URLSession:(ACSURLSession *)arg1 task:(ACSURLSessionTask *)arg2 didSendBodyData:(long long)arg3 totalBytesSent:(long long)arg4 totalBytesExpectedToSend:(long long)arg5;
- (void)URLSession:(ACSURLSession *)arg1 task:(ACSURLSessionTask *)arg2 needNewBodyStream:(void (^)(NSInputStream *))arg3;
- (void)URLSession:(ACSURLSession *)arg1 task:(ACSURLSessionTask *)arg2 didReceiveChallenge:(NSURLAuthenticationChallenge *)arg3 completionHandler:(void (^)(long long, NSURLCredential *))arg4;
- (void)URLSession:(ACSURLSession *)arg1 task:(ACSURLSessionTask *)arg2 willPerformHTTPRedirection:(NSHTTPURLResponse *)arg3 newRequest:(NSURLRequest *)arg4 completionHandler:(void (^)(NSURLRequest *))arg5;
- (void)URLSession:(ACSURLSession *)arg1 taskIsWaitingForConnectivity:(ACSURLSessionTask *)arg2;
@end

