//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSMutableSet;

@interface DVTAbstractMethodChecker : NSObject
{
    NSMutableDictionary *_abstractMethodRecordsByClassName;
    BOOL _scheduledCheck;
    BOOL _checkAllClassesOnNextCheck;
    NSMutableSet *_classNamesToCheckOnNextCheck;
}

+ (void)eumerateAbstractMethodsForClassName:(id)arg1 inDictionary:(id)arg2 usingBlock:(CDUnknownBlockType)arg3;
+ (void)incorporateMethodRecords:(id)arg1 intoDictionary:(id)arg2;
+ (id)abstractMethodRecordsInLibraryWithMachHeader:(const struct mach_header_64 *)arg1;
+ (const struct mach_header_64 *)machHeaderAddressForLibraryContainingClass:(Class)arg1;
+ (id)abstractMethodRecordsInBundle:(id)arg1;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)checkForAbstractMethodsWithoutOverridesInClassName:(id)arg1;
- (BOOL)isClassNameAbstract:(id)arg1;
- (BOOL)scanAndIncorporateAbstractMethodsFromLibraryWithMachHeader:(const struct mach_header_64 *)arg1;
- (void)performPendingChecks;
- (void)incorporateAbstractMethodsAndCheckClasses:(id)arg1 fromLibraryWithMachHeader:(const struct mach_header_64 *)arg2;
- (void)incorporateAbstractMethodsAndCheckClasses:(id)arg1 fromBundle:(id)arg2;
- (void)bundleDidLoad:(id)arg1;
- (id)initObservingBundleLoad:(BOOL)arg1;

@end

