//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  6 2019 20:12:56).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSString;

@protocol DVTDeveloperPortalDefaultsProtocol
@property(readonly, copy, nonatomic) NSString *portalServiceEndpoint;
@property(readonly, copy, nonatomic) NSString *portalServiceHostDescription;
@property(readonly, copy, nonatomic) NSString *portalServiceCertificateHostname;
@property(readonly, copy, nonatomic) NSString *portalServiceHostname;
@property(readonly, copy, nonatomic) NSString *portalServiceProtocolVersion;
@property(readonly, copy, nonatomic) NSString *portalServiceXcodeServerClientID;
@property(readonly, copy, nonatomic) NSString *portalServiceXcodeClientID;
@end

