//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface DVTDataDigester : NSObject
{
}

+ (id)digestForData:(id)arg1;
- (id)digest;
- (void)updateWithArrayOfStrings:(id)arg1;
- (void)updateWithString:(id)arg1;
- (void)updateWithData:(id)arg1;
- (void)updateWithBytes:(const void *)arg1 length:(unsigned long long)arg2;

@end

