//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTFoundation/DVTDeviceApplicationItem-Protocol.h>

@class NSSet, NSString;

@protocol DVTDeviceApplication <DVTDeviceApplicationItem>
@property(readonly) BOOL isHidden;
@property(readonly, copy) NSSet *rootContainerApplicationItems;
@property(readonly) BOOL isFairPlayEncrypted;
@property(readonly) NSString *bundleIdentifier;
@property(readonly) NSString *version;
@end

