//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <DVTFoundation/NSCopying-Protocol.h>

@class NSString;

@interface DVTFuzzyMatchPattern : NSObject <NSCopying>
{
    char *_patternCharacters;
    char *_lowercasePatternCharacters;
    long long _patternLength;
    unsigned int _mask;
    unsigned int *_patternSuccessiveMasks;
    struct DVTFuzzyMatchCandidate *_patternAsCandidate;
    BOOL _containsPathSeparator;
    NSString *_patternText;
}

+ (id)annotatedCandidate:(id)arg1 ranges:(id)arg2;
+ (void)invokeWithTokenizedCandidateUTF8Bytes:(const char *)arg1 length:(long long)arg2 style:(long long)arg3 isFileName:(BOOL)arg4 block:(CDUnknownBlockType)arg5;
- (void).cxx_destruct;
@property(readonly) BOOL containsPathSeparator; // @synthesize containsPathSeparator=_containsPathSeparator;
@property(readonly) NSString *patternText; // @synthesize patternText=_patternText;
- (BOOL)rejectsEverything;
- (BOOL)matchesASubsetOfMatchesFromPattern:(id)arg1;
- (BOOL)matchesEverythingMatchedBy:(id)arg1;
- (id)matchedRangesForCandidate:(struct DVTFuzzyMatchCandidate *)arg1;
- (double)scoreCandidate:(struct DVTFuzzyMatchCandidate *)arg1 precision:(long long)arg2 style:(long long)arg3 isFileName:(BOOL)arg4 ranges:(id *)arg5;
- (double)scoreCandidate:(struct DVTFuzzyMatchCandidate *)arg1 precision:(long long)arg2 isFileName:(BOOL)arg3 matchingRanges:(const struct _NSRange *)arg4 count:(long long)arg5 tokenCount:(long long)arg6 tokenLengths:(const long long *)arg7 charactersToTokens:(const long long *)arg8 charactersToPositionsInToken:(const long long *)arg9 tokenCountsTowardsCoverageBonusing:(const char *)arg10 startOfFileExtension:(long long)arg11;
- (id)allPossibleMatchesForCandidate:(struct DVTFuzzyMatchCandidate *)arg1;
- (void)enumerateAllPossibleMatchingsForCandidate:(struct DVTFuzzyMatchCandidate *)arg1 budget:(long long)arg2 visitor:(CDUnknownBlockType)arg3;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isEqualToPattern:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)invokeWithRangesMatchingCandidate:(struct DVTFuzzyMatchCandidate *)arg1 withBlock:(CDUnknownBlockType)arg2;
- (BOOL)matchesCandidate:(struct DVTFuzzyMatchCandidate *)arg1;
- (BOOL)mightMatchCandidate:(struct DVTFuzzyMatchCandidate *)arg1;
- (id)description;
- (void)dealloc;
- (id)initWithPatternText:(id)arg1;
- (BOOL)matchesText:(id)arg1;
- (id)matchedRangesForText:(id)arg1;

@end

