//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <DVTFoundation/NSSecureCoding-Protocol.h>

@class NSString;

@interface DVTITunesConnectDeviceDescription : NSObject <NSSecureCoding>
{
    NSString *_deviceFamilyIdentifier;
    NSString *_internalName;
}

+ (BOOL)supportsSecureCoding;
@property(readonly) NSString *internalName; // @synthesize internalName=_internalName;
@property(readonly) NSString *deviceFamilyIdentifier; // @synthesize deviceFamilyIdentifier=_deviceFamilyIdentifier;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithITunesSoftwareDeviceDescription:(id)arg1;
- (id)initWithDeviceFamilyIdentifier:(id)arg1 internalName:(id)arg2;

@end

