//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTFoundation/DVTITunesConnectBundleDescription.h>

@class NSString;

@interface DVTITunesConnectApplicationDescription : DVTITunesConnectBundleDescription
{
    NSString *_adamID;
}

+ (BOOL)supportsSecureCoding;
@property(readonly) NSString *adamID; // @synthesize adamID=_adamID;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithITunesSoftwareApplicationDescription:(id)arg1;
- (id)initWithAdamID:(id)arg1 name:(id)arg2 displayableDescription:(id)arg3 platformIdentifier:(id)arg4 bundleIdentifier:(id)arg5;

@end

