//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTFoundation/DVTMacroExpansionString_Substitution.h>

@interface DVTMacroExpansionString_StringSubstitution : DVTMacroExpansionString_Substitution
{
}

- (id)dvt_debugDescription;
- (id)dvt_evaluateAsStringListInScope:(id)arg1 withState:(const struct DVTNestedMacroExpansionState *)arg2;

@end

