//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTFoundation/DVTSigningCertificate.h>

@class NSDate, NSString;

@interface DVTMockSigningCertificate : DVTSigningCertificate
{
    struct OpaqueSecCertificateRef *_certificateRef;
    BOOL _isIdentityMock;
    BOOL _isTrustedMock;
    BOOL _isValidForCodesigningMock;
    BOOL _isForServerMock;
    NSString *_certificateKindMock;
    NSString *_commonNameMock;
    NSString *_portalTeamIDMock;
    NSString *_portalTeamNameMock;
    NSString *_portalMemberIDMock;
    NSDate *_issueDateMock;
    NSDate *_expirationDateMock;
    NSString *_sha1HashMock;
    NSString *_serialNumberMock;
}

+ (id)underlyingObject;
@property BOOL isForServerMock; // @synthesize isForServerMock=_isForServerMock;
@property BOOL isValidForCodesigningMock; // @synthesize isValidForCodesigningMock=_isValidForCodesigningMock;
@property(copy) NSString *serialNumberMock; // @synthesize serialNumberMock=_serialNumberMock;
@property(copy) NSString *sha1HashMock; // @synthesize sha1HashMock=_sha1HashMock;
@property BOOL isTrustedMock; // @synthesize isTrustedMock=_isTrustedMock;
@property(copy) NSDate *expirationDateMock; // @synthesize expirationDateMock=_expirationDateMock;
@property(copy) NSDate *issueDateMock; // @synthesize issueDateMock=_issueDateMock;
@property BOOL isIdentityMock; // @synthesize isIdentityMock=_isIdentityMock;
@property(copy) NSString *portalMemberIDMock; // @synthesize portalMemberIDMock=_portalMemberIDMock;
@property(copy) NSString *portalTeamNameMock; // @synthesize portalTeamNameMock=_portalTeamNameMock;
@property(copy) NSString *portalTeamIDMock; // @synthesize portalTeamIDMock=_portalTeamIDMock;
@property(copy) NSString *commonNameMock; // @synthesize commonNameMock=_commonNameMock;
@property(copy) NSString *certificateKindMock; // @synthesize certificateKindMock=_certificateKindMock;
- (void).cxx_destruct;
- (id)defaultDesignatedRequirementsForIdentifier:(id)arg1;
- (struct OpaqueSecCertificateRef *)certificateRef;
- (BOOL)isForServer;
- (BOOL)isValidForCodeSigning;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (BOOL)isExpired;
- (id)serialNumber;
- (id)sha1Hash;
- (BOOL)isTrusted;
- (id)expirationDate;
- (id)issueDate;
- (BOOL)isIdentity;
- (id)portalMemberID;
- (id)portalTeamName;
- (id)portalTeamID;
- (id)commonName;
- (id)certificateKind;
- (void)validate;
- (id)initWithDictionary:(id)arg1;
- (id)initWithPlist:(id)arg1;
- (id)init;
- (id)initWithUnderlyingType:(id)arg1 logAspect:(id)arg2;

@end

