//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMapTable;
@protocol OS_dispatch_queue;

@interface DVTNotificationCenterTracker : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    NSMapTable *_registrations;
}

+ (void)install;
- (void).cxx_destruct;
- (void)removeObserver:(id)arg1 name:(id)arg2 object:(id)arg3;
- (void)removeObserver:(id)arg1;
- (void)addedObserverToken:(id)arg1 forName:(id)arg2 object:(id)arg3 queue:(id)arg4 usingBlock:(CDUnknownBlockType)arg5;
- (void)addObserver:(id)arg1 selector:(SEL)arg2 name:(id)arg3 object:(id)arg4;
- (void)printStats;
- (id)init;

@end

