//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  6 2019 20:12:56).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <DVTFoundation/NSPredicateVisitor-Protocol.h>

@class NSMutableOrderedSet, NSOrderedSet;

@interface DVTNSExpressionKeyPathVisitor : NSObject <NSPredicateVisitor>
{
    NSMutableOrderedSet *_keyPaths;
}

@property(retain) NSOrderedSet *keyPaths; // @synthesize keyPaths=_keyPaths;
- (void).cxx_destruct;
- (void)visitPredicateOperator:(id)arg1;
- (void)visitPredicateExpression:(id)arg1;
- (void)visitPredicate:(id)arg1;
- (void)visitAllSubexpressionsOfExpression:(id)arg1;
- (id)init;

@end

