//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface DVTObjectDeallocationMonitor : NSObject
{
}

+ (id)_referenceTreeDescriptionForObject:(id)arg1;
+ (BOOL)_getReferenceTreeDescriptionForObject:(id)arg1 monitorInfosForUncollectedObjects:(id)arg2 referenceTreeDescription:(id *)arg3 crashReportSignature:(id *)arg4;
+ (void)setLeakReportEnabled:(BOOL)arg1;
+ (BOOL)leakReportEnabled;
+ (void)logLeakedObjects;
+ (BOOL)isEnabled;

@end

