//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTDispatchLock, NSMutableDictionary;
@protocol OS_dispatch_source;

@interface DVTPinger : NSObject
{
    NSObject<OS_dispatch_source> *_source;
    unsigned short _identifier;
    int _sequenceNumber;
    double _timeout;
    NSMutableDictionary *_futures;
    DVTDispatchLock *_futuresLock;
    struct sockaddr_storage _addr;
}

+ (id)pingerWithAddress:(id)arg1;
+ (id)pingerWithSocketAddress:(const struct sockaddr *)arg1;
- (void).cxx_destruct;
@property unsigned short identifier; // @synthesize identifier=_identifier;
@property int sequenceNumber; // @synthesize sequenceNumber=_sequenceNumber;
@property(retain) DVTDispatchLock *futuresLock; // @synthesize futuresLock=_futuresLock;
@property(retain) NSMutableDictionary *futures; // @synthesize futures=_futures;
@property struct sockaddr_storage addr; // @synthesize addr=_addr;
@property double timeout; // @synthesize timeout=_timeout;
- (id)ping;
- (void)_promiseWithSequenceNumber:(unsigned long long)arg1 endedAt:(double)arg2;
- (id)_createSourceIfNecessary;
- (void)dealloc;

@end

