//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <DVTFoundation/NSCopying-Protocol.h>

@class NSString;

@interface DVTRegularExpression : NSObject <NSCopying>
{
    NSString *_expressionString;
    struct URegularExpression *_compiledExpression;
    int _options;
}

+ (struct URegularExpression *)testAndCompileExpressionString:(id)arg1 options:(int)arg2 error:(id *)arg3;
+ (id)descriptionForParseError:(struct UParseError *)arg1;
+ (void)initialize;
- (void).cxx_destruct;
@property int options; // @synthesize options=_options;
@property struct URegularExpression *compiledExpression; // @synthesize compiledExpression=_compiledExpression;
@property(copy) NSString *expressionString; // @synthesize expressionString=_expressionString;
- (id)description;
- (BOOL)enumerateMatchesInString:(id)arg1 error:(id *)arg2 usingBlock:(CDUnknownBlockType)arg3;
- (BOOL)enumerateMatchesInString:(id)arg1 searchRange:(struct _NSRange)arg2 error:(id *)arg3 usingBlock:(CDUnknownBlockType)arg4;
- (id)matchString:(id)arg1 error:(id *)arg2;
- (id)matchString:(id)arg1 searchRange:(struct _NSRange)arg2 error:(id *)arg3;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
@property(readonly) unsigned long long groupCount;
- (id)initWithExpressionString:(id)arg1 options:(int)arg2 error:(id *)arg3;

@end

