//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  6 2019 20:12:56).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <DVTFoundation/DVTAccountBasedSession-Protocol.h>

@class DVTDeveloperAccount, DVTDeveloperAccountSession, DVTDispatchLock, DVTLogAspect, NSData, NSNumber, NSString;

@interface DVTServicesAccountBasedSession : NSObject <DVTAccountBasedSession>
{
    id _wrappingLogHandlerToken;
    DVTServicesAccountBasedSession *_parentSession;
    DVTDispatchLock *_sessionIDLock;
    DVTLogAspect *_backingLogAspect;
    DVTDeveloperAccount *_account;
    long long _executionContext;
    NSString *_portalSessionID;
    DVTLogAspect *_logAspect;
    DVTDeveloperAccountSession *_accountSession;
}

+ (id)_servicesSessionErrorFromAccountError:(id)arg1 account:(id)arg2;
+ (id)servicesSessionWithDeveloperAccountSession:(id)arg1 executionContext:(long long)arg2;
+ (id)sessionForAuthenticatingAccount:(id)arg1;
+ (id)servicesSessionByLoggingInWithAccount:(id)arg1 executionContext:(long long)arg2 error:(id *)arg3;
@property(retain, nonatomic) DVTDeveloperAccountSession *accountSession; // @synthesize accountSession=_accountSession;
@property(retain, nonatomic) DVTLogAspect *logAspect; // @synthesize logAspect=_logAspect;
@property(readonly) long long executionContext; // @synthesize executionContext=_executionContext;
@property(readonly) DVTDeveloperAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
@property(readonly) NSString *portalServiceHostname;
- (void)updateWithResponseHeaders:(id)arg1;
- (id)authenticationHeadersForRequest:(id)arg1;
- (void)_clearWrappingLogAspect;
- (void)_setWrappingLogAspect:(id)arg1;
@property(readonly) NSData *sessionData;
@property(copy, nonatomic) NSString *portalSessionID; // @synthesize portalSessionID=_portalSessionID;
@property(readonly) NSString *sessionID;
@property(readonly) NSNumber *portalServicePort;
@property(readonly) NSString *portalServiceScheme;
- (void)dealloc;
- (id)initWithAccount:(id)arg1 accountSession:(id)arg2 parentSession:(id)arg3 executionContext:(long long)arg4 logAspect:(id)arg5;
- (id)sessionWithAdditionalLogAspect:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

