//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSMutableDictionary.h>

@interface NSMutableDictionary (DVTFoundationClassAdditions)
- (void)dvt_intersectKeys:(id)arg1;
- (void)dvt_setObject:(id)arg1 forKeyIfNonNil:(id)arg2;
- (void)dvt_setObjectIfNonNil:(id)arg1 forKey:(id)arg2;
- (id)dvt_objectForKey:(id)arg1 creatingIfNecessaryWithBlock:(CDUnknownBlockType)arg2;
- (id)dvt_objectForKey:(id)arg1 creatingIfNecessaryFromClass:(Class)arg2;
- (id)dvt_extractObjectForKey:(id)arg1;
- (void)dvt_recursivelyRemoveAllObjects;
- (void)dvt_setRect:(struct CGRect)arg1 forKey:(id)arg2;
- (void)dvt_setSize:(struct CGSize)arg1 forKey:(id)arg2;
- (void)dvt_setPoint:(struct CGPoint)arg1 forKey:(id)arg2;
- (void)dvt_setDouble:(double)arg1 forKey:(id)arg2;
- (void)dvt_setFloat:(float)arg1 forKey:(id)arg2;
- (void)dvt_setBool:(BOOL)arg1 forKey:(id)arg2;
- (void)dvt_setInteger:(long long)arg1 forKey:(id)arg2;
- (void)dvt_removeObject:(id)arg1 fromCollectionForKey:(id)arg2;
- (void)dvt_addObject:(id)arg1 toOrderedSetForKey:(id)arg2;
- (void)dvt_addObject:(id)arg1 toSetForKey:(id)arg2;
- (void)dvt_addObject:(id)arg1 toArrayForKey:(id)arg2;
- (void)dvt_setObject:(id)arg1 forKey:(id)arg2 inDictionaryForKey:(id)arg3;
@end

