//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface NSObject (SharedObserverConvenienceInternals)
- (void)_dvt_removeObserverFromSharedObserver:(id)arg1 withTrackingIndex:(unsigned int)arg2 fromKeyPath:(id)arg3;
- (id)_dvt_addSharedObserverForKeyPath:(id)arg1 observeInitial:(BOOL)arg2 block:(CDUnknownBlockType)arg3;
@end

