//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSRecursiveLock.h>

#import <DVTFoundation/DVTLocking-Protocol.h>

@interface NSRecursiveLock (DVTFoundationExtensions) <DVTLocking>
- (void)dvt_asyncPerformLockedBlock:(CDUnknownBlockType)arg1;
- (void)dvt_performLockedBlock:(CDUnknownBlockType)arg1;
@end

