//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSTimer.h>

@interface NSTimer (DVTMainThreadLatencyCheckerAdditions)
+ (id)dvt_scheduledTimerWithTimeInterval:(double)arg1 repeats:(BOOL)arg2 handler:(CDUnknownBlockType)arg3;
- (id)__DVTMainThreadLatencyChecker__initWithFireDate:(id)arg1 interval:(double)arg2 target:(id)arg3 selector:(SEL)arg4 userInfo:(id)arg5 repeats:(BOOL)arg6;
@end

