//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSUserDefaults.h>

#import <DVTFoundation/DVTUserDefaults-Protocol.h>

@class NSString;

@interface NSUserDefaults (DVTNSUserDefaultsAdditions) <DVTUserDefaults>
- (void)dvt_setupDefaultsFromEnvironment;
- (void)dvt_setFilePath:(id)arg1 forKey:(id)arg2;
- (id)dvt_filePathForKey:(id)arg1;
- (BOOL)dvt_objectIsChangedForKey:(id)arg1;
- (id)dvt_objectForKey:(id)arg1 inVolatileDomainForName:(id)arg2;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (id)objectForKeyedSubscript:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

