//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  6 2019 20:12:56).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@interface _TtC15IDESourceEditorP33_6772E1C07DD5AD6ED17A9E42E51A286E22ChangeGutterMarginView : NSView
{
}

- (BOOL)isFlipped;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

// Remaining properties
@property(nonatomic, readonly) BOOL flipped;

@end

