//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTFoundation/DVTFindResult.h>

__attribute__((visibility("hidden")))
@interface _TtC15IDESourceEditor17RefactoringResult : DVTFindResult
{
    // Error parsing type: , name: replacement
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)initWithFoundLocation:(id)arg1 withRange:(struct _NSRange)arg2 inContext:(id)arg3;
- (id)stringForReplacementString:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

