//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_$s12SourceEditor0aB29NotificationFeatureControllerCN.h"

@interface _TtC15IDESourceEditor42IDEConsoleEditorViewThemeFeatureController : _$s12SourceEditor0aB29NotificationFeatureControllerCN
{
}

@end

