//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTFoundation/DVTDocumentLocation.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC15IDESourceEditor24CodeRollDocumentLocation : DVTDocumentLocation
{
    MISSING_TYPE *url;
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithDocumentURL:(id)arg1 timestamp:(id)arg2;
- (id)initWithCoder:(id)arg1;

@end

