//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSScrollView.h>

__attribute__((visibility("hidden")))
@interface _TtC15IDESourceEditor20EmbeddableScrollView : NSScrollView
{
}

+ (BOOL)isCompatibleWithResponsiveScrolling;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)scrollWheel:(id)arg1;

@end

