//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSArray, NSString;

__attribute__((visibility("hidden")))
@interface _TtC15IDESourceEditor19CodeRollNavItemRoot : NSObject
{
    MISSING_TYPE *workspace;
    MISSING_TYPE *parent;
    MISSING_TYPE *workspaceObserver;
    MISSING_TYPE *codeRollNavItems;
}

+ (id)keyPathsForValuesAffectingNavigableItem_childRepresentedObjects;
- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSString *description;
@property(nonatomic, readonly) NSArray *navigableItem_childRepresentedObjects;
@property(nonatomic, readonly) NSString *navigableItem_name;
@property(nonatomic, copy) NSArray *codeRollNavItems;

@end

