//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  6 2019 20:12:56).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class IDECodeSnippet, _TtC15IDESourceEditor31IDECodeSnippetLibraryDetailView;

@protocol _TtP15IDESourceEditor39IDECodeSnippetLibraryDetailViewDelegate_
- (void)codeSnippetLibraryDeleteView:(_TtC15IDESourceEditor31IDECodeSnippetLibraryDetailView *)arg1 userDidDeleteSnippet:(IDECodeSnippet *)arg2;
@end

