//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class IDECodeSnippet, _TtC15IDESourceEditor31IDECodeSnippetLibraryDetailView;

@protocol _TtP15IDESourceEditor39IDECodeSnippetLibraryDetailViewDelegate_
- (void)codeSnippetLibraryDeleteView:(_TtC15IDESourceEditor31IDECodeSnippetLibraryDetailView *)arg1 userDidDeleteSnippet:(IDECodeSnippet *)arg2;
@end

