//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSArray, NSString;
@protocol IDEConsoleTextViewObjectiveCExpressionRangeDelegate, IDEConsoleTextViewStandardIODelegate;

@protocol DVTConsoleTextViewProtocol
- (void)setCompletionStrategies:(NSArray *)arg1;
- (id)textStorage;
- (void)setSelectedRange:(struct _NSRange)arg1;
- (struct _NSRange)rangeForUserTextChange;
- (void)themeFontsAndColorsUpdates;
- (void)repeatInput:(NSString *)arg1;
@property(nonatomic, retain) id <IDEConsoleTextViewStandardIODelegate> standardIODelegate;
- (void)appendConsoleItemsImmediatelyWithoutScrolling:(NSArray *)arg1;
- (void)appendConsoleItemsAfterDelay:(NSArray *)arg1;
- (void)clearConsoleItems;
@property(nonatomic) int logMode;

@optional
- (void)findPrevious:(id)arg1;
- (void)findNext:(id)arg1;
@property(nonatomic, retain) id <IDEConsoleTextViewObjectiveCExpressionRangeDelegate> openingBracketLocationDelegate;
@end

