//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSArray, NSString;
@protocol DVTSourceLandmarkItemProtocol;

@protocol DVTSourceLandmarkItemProtocol
- (BOOL)needsUpdate;
- (NSString *)landmarkItemTypeName;
- (unsigned long long)landmarkItemType;
- (struct _NSRange)landmarkItemNameRange;
- (struct _NSRange)landmarkItemRange;
- (NSString *)landmarkItemName;
- (NSArray *)childLandmarkItems;
- (long long)numberOfChildLandmarkItems;
- (id <DVTSourceLandmarkItemProtocol>)parentLandmarkItem;
@end

