//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  6 2019 20:12:56).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSString;

@protocol IDESourceKitAvailableRefactoring
@property(nonatomic, readonly) NSString *name;
@property(nonatomic, readonly) long long ident;
@property(nonatomic, readonly) long long kind;
@end

