//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 30 2020 21:18:12).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSArray, NSString;

@protocol IDESourceKitRefactoringFileRenameRanges
@property(nonatomic, readonly) NSArray *categorizedRanges;
@property(nonatomic, readonly) BOOL shouldRenameFile;
@property(nonatomic, readonly) NSString *filePath;
@end

