//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 30 2018 09:30:25).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class NSLayoutConstraint, NSTextField, _TtC15IDESourceEditor11RenameLabel;

__attribute__((visibility("hidden")))
@interface _TtC15IDESourceEditor29CodeRollSymbolicEditSliceCell : NSTableCellView
{
    // Error parsing type: , name: propertyNameField
    // Error parsing type: , name: propertyValueField
    // Error parsing type: , name: propertyNameWidthConstraint
    // Error parsing type: , name: propertyNameSpacingConstraint
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) NSLayoutConstraint *propertyNameSpacingConstraint; // @synthesize propertyNameSpacingConstraint;
@property(nonatomic, retain) NSLayoutConstraint *propertyNameWidthConstraint; // @synthesize propertyNameWidthConstraint;
@property(nonatomic, retain) _TtC15IDESourceEditor11RenameLabel *propertyValueField; // @synthesize propertyValueField;
@property(nonatomic, retain) NSTextField *propertyNameField; // @synthesize propertyNameField;

@end

